--1

Create table uk_rrbs_dm.dim_rrbs_data_cdrType
(
sk_cdr_type int generated by default as identity (1,1),
cdrtype_id smallint,
cdrtype_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	cdrtype_id
	)
;

--2

Create table uk_rrbs_dm.dim_rrbs_data_serviceid
(
sk_serviceid int generated by default as identity (1,1),
service_id smallint,
serviceid_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	service_id
	)
;

--3

/*Create table uk_rrbs_dm.dim_rrbs_data_roamflag
(
sk_roamflag_id int generated by default as identity (1,1),
roamflag_id smallint,
roamflag_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	roamflag_id
	)
;*/

--4

Create table uk_rrbs_dm.dim_rrbs_data_subscriberType
(
sk_subscriberType int generated by default as identity (1,1),
subscriberType_id smallint,
subscriberType_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	subscriberType_id
	)
;


---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS uk_rrbs_dm.dim_rrbs_data_codetext
(
	sk_codetext INTEGER  DEFAULT default_identity(100947, 0, '1,1'::text) ENCODE lzo
	,code_param VARCHAR(100)   ENCODE RAW
	,code_param_id SMALLINT   ENCODE lzo
	,code_param_val VARCHAR(100)   ENCODE lzo
	,code_param_desc VARCHAR(250)   ENCODE lzo
	,valid_from TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp without time zone ENCODE lzo
	,valid_to TIMESTAMP WITHOUT TIME ZONE  DEFAULT '9999-12-31 00:00:00'::timestamp without time zone ENCODE lzo
	,is_recent SMALLINT   ENCODE lzo
	,batch_id SMALLINT   ENCODE lzo
)
DISTSTYLE ALL
 SORTKEY (
	code_param
	)
;
---------------------------------------------------------------------------
