version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  build:
    commands:
      - make build_rrbs
      - make build_data_exporter
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
