create table log_batch_files_ggsn
(
    batch_id                integer encode az64 distkey,
    file_source             varchar(50),
    file_id                 integer encode az64,
    file_name               varchar(50),
    batch_from              timestamp encode az64,
    batch_to                timestamp encode az64,
    record_count            integer encode az64,
    dm_normal_count         integer encode az64,
    dm_latecdr_count        integer encode az64,
    ldm_latecdr_count       integer encode az64,
    dm_normal_dbdupl_count  integer encode az64,
    dm_latecdr_dbdupl_count integer encode az64,
    is_valid                varchar(20),
    batch_createtime        timestamp encode az64
)
    diststyle key;

create table log_batch_status_ggsn
(
    batch_id                    integer encode az64,
    s3_batchreadcount           integer encode az64,
    s3_filecount                integer encode az64,
    intrabatch_new_normal_count integer encode az64,
    intrabatch_new_late_count   integer encode az64,
    intrabatch_dupl_count       integer encode az64,
    intrabatch_dist_dupl_count  integer encode az64,
    intrabatch_dedupl_status    varchar(20),
    dm_normal_count             integer encode az64,
    dm_normal_dbdupl_count      integer encode az64,
    dm_normal_status            varchar(20),
    ldm_latecdr_count           integer encode az64,
    ldm_latecdr_dbdupl_count    integer encode az64,
    ldm_latecdr_status          varchar(20),
    batch_start_dt              timestamp encode az64,
    batch_end_dt                timestamp encode az64,
    batch_status                varchar(50)
);

create table fact_ggsn_duplcdr
(
    sk_ggsn                          bigint default default_identity(159739, 0, ('1,1'::character varying)::text) encode zstd,
    recordtype                       varchar(10),
    servedimsi                       bigint encode az64 distkey,
    p_gwaddress                      varchar(100),
    chargingid                       varchar(20),
    servingnodeaddress               varchar(200),
    accesspointnameni                varchar(100),
    pdppdntype                       varchar(10),
    servedpdppdnaddress              varchar(50),
    dynamicaddressflag               varchar(10),
    recordopeningtime                varchar(50),
    duration                         integer encode az64,
    causeforrecclosing               varchar(150),
    diagnostics                      varchar(10),
    recordsequencenumber             varchar(10),
    nodeid                           varchar(20),
    localsequencenumber              varchar(20),
    apnselectionmode                 varchar(100),
    servedmsisdn                     bigint encode az64,
    chargingcharacteristics          varchar(50),
    chchselectionmode                varchar(50),
    imssignalingcontext              varchar(50),
    externalchargingid               varchar(50),
    servingnodeplmnidentifier        varchar(50),
    psfreeformatdata                 varchar(50),
    psffdappendindicator             varchar(50),
    servedimeisv                     varchar(50),
    rattype                          varchar(10),
    mstimezone                       varchar(50),
    userlocationinformation          varchar(50),
    camelcharginginformation         varchar(50),
    servingnodetype                  varchar(50),
    servedmnnai                      varchar(50),
    p_gwplmnidentifier               varchar(50),
    starttime                        varchar(50),
    stoptime                         varchar(50),
    served3gpp2meid                  varchar(50),
    pdnconnectionchargingid          varchar(50),
    threegpp2userlocationinformation varchar(50),
    servedpdppdnaddressext           varchar(100),
    dynamicaddressflagext            varchar(50),
    dummy                            varchar(200),
    total_uplink                     bigint encode az64,
    total_downlink                   bigint encode az64,
    change_date                      varchar(100),
    url                              varchar(500),
    ratinggroup                      varchar(500),
    failurehand                      varchar(500),
    conditionchange                  varchar(500),
    rulebasename                     varchar(500),
    timeoffirstusage                 varchar(500),
    timeoflastusage                  varchar(500),
    timeusage                        varchar(500),
    timeofreport                     varchar(500),
    recordopening_date               date encode az64,
    recordopening_date_num           integer,
    recordopening_month              integer,
    total_uplink_mb                  numeric(20, 4) encode az64,
    total_downlink_mb                numeric(20, 4) encode az64,
    accesspointnameni_code           varchar(10),
    recordopening_time_gmt           timestamp encode az64,
    recordopening_dt_month_gmt       integer encode az64,
    recordopening_dt_num_gmt         integer encode az64,
    recordopening_dt_hour_gmt        integer encode az64,
    filename                         varchar(50),
    batch_id                         integer encode az64,
    created_date                     timestamp encode az64,
    rec_checksum                     varchar(32)
)
    diststyle key
    sortkey (recordopening_month, recordopening_date_num, accesspointnameni);

create table fact_ggsn
(
    sk_ggsn                          bigint default default_identity(166498, 0, ('1,1'::character varying)::text) encode zstd,
    recordtype                       varchar(10) encode zstd,
    servedimsi                       bigint encode az64 distkey,
    p_gwaddress                      varchar(100) encode zstd,
    chargingid                       varchar(20) encode zstd,
    servingnodeaddress               varchar(200) encode zstd,
    accesspointnameni                varchar(100),
    pdppdntype                       varchar(10) encode zstd,
    servedpdppdnaddress              varchar(50) encode zstd,
    dynamicaddressflag               varchar(10) encode zstd,
    recordopeningtime                timestamp encode az64,
    duration                         integer encode az64,
    causeforrecclosing               varchar(150) encode zstd,
    diagnostics                      varchar(10) encode zstd,
    recordsequencenumber             varchar(10) encode zstd,
    nodeid                           varchar(20) encode zstd,
    localsequencenumber              varchar(20) encode zstd,
    apnselectionmode                 varchar(100) encode zstd,
    servedmsisdn                     bigint encode az64,
    chargingcharacteristics          varchar(50) encode zstd,
    chchselectionmode                varchar(50) encode zstd,
    imssignalingcontext              varchar(50) encode zstd,
    externalchargingid               varchar(50) encode zstd,
    servingnodeplmnidentifier        varchar(50) encode zstd,
    psfreeformatdata                 varchar(50) encode zstd,
    psffdappendindicator             varchar(50) encode zstd,
    servedimeisv                     varchar(50) encode zstd,
    rattype                          varchar(10) encode zstd,
    mstimezone                       varchar(50) encode zstd,
    userlocationinformation          varchar(50) encode zstd,
    camelcharginginformation         varchar(50) encode zstd,
    servingnodetype                  varchar(50) encode zstd,
    servedmnnai                      varchar(50) encode zstd,
    p_gwplmnidentifier               varchar(50) encode zstd,
    starttime                        timestamp encode az64,
    stoptime                         timestamp encode az64,
    served3gpp2meid                  varchar(50),
    pdnconnectionchargingid          varchar(50),
    threegpp2userlocationinformation varchar(50),
    servedpdppdnaddressext           varchar(100),
    dynamicaddressflagext            varchar(50),
    dummy                            varchar(200),
    total_uplink                     bigint encode az64,
    total_downlink                   bigint encode az64,
    change_date                      varchar(100),
    url                              varchar(500),
    ratinggroup                      varchar(500),
    failurehand                      varchar(500),
    conditionchange                  varchar(500),
    rulebasename                     varchar(500),
    timeoffirstusage                 varchar(500),
    timeoflastusage                  varchar(500),
    timeusage                        varchar(500),
    timeofreport                     varchar(500),
    recordopening_date               date encode az64,
    recordopening_date_num           integer,
    recordopening_month              integer,
    total_uplink_mb                  numeric(20, 4) encode az64,
    total_downlink_mb                numeric(20, 4) encode az64,
    accesspointnameni_code           varchar(10),
    recordopening_time_gmt           timestamp encode az64,
    recordopening_dt_month_gmt       integer encode az64,
    recordopening_dt_num_gmt         integer encode az64,
    recordopening_dt_hour_gmt        integer encode az64,
    filename                         varchar(50),
    batch_id                         integer encode az64,
    created_date                     timestamp encode az64,
    rec_checksum                     varchar(32)
)
    diststyle key
    sortkey (recordopening_month, recordopening_date_num, accesspointnameni);

create table fact_ggsn_latecdr
(
    sk_ggsn                          bigint default default_identity(159742, 0, ('1,1'::character varying)::text) encode zstd,
    recordtype                       varchar(10),
    servedimsi                       bigint encode az64 distkey,
    p_gwaddress                      varchar(100),
    chargingid                       varchar(20),
    servingnodeaddress               varchar(200),
    accesspointnameni                varchar(100),
    pdppdntype                       varchar(10),
    servedpdppdnaddress              varchar(50),
    dynamicaddressflag               varchar(10),
    recordopeningtime                varchar(50),
    duration                         integer encode az64,
    causeforrecclosing               varchar(150),
    diagnostics                      varchar(10),
    recordsequencenumber             varchar(10),
    nodeid                           varchar(20),
    localsequencenumber              varchar(20),
    apnselectionmode                 varchar(100),
    servedmsisdn                     bigint encode az64,
    chargingcharacteristics          varchar(50),
    chchselectionmode                varchar(50),
    imssignalingcontext              varchar(50),
    externalchargingid               varchar(50),
    servingnodeplmnidentifier        varchar(50),
    psfreeformatdata                 varchar(50),
    psffdappendindicator             varchar(50),
    servedimeisv                     varchar(50),
    rattype                          varchar(10),
    mstimezone                       varchar(50),
    userlocationinformation          varchar(50),
    camelcharginginformation         varchar(50),
    servingnodetype                  varchar(50),
    servedmnnai                      varchar(50),
    p_gwplmnidentifier               varchar(50),
    starttime                        varchar(50),
    stoptime                         varchar(50),
    served3gpp2meid                  varchar(50),
    pdnconnectionchargingid          varchar(50),
    threegpp2userlocationinformation varchar(50),
    servedpdppdnaddressext           varchar(100),
    dynamicaddressflagext            varchar(50),
    dummy                            varchar(200),
    total_uplink                     bigint encode az64,
    total_downlink                   bigint encode az64,
    change_date                      varchar(100),
    url                              varchar(500),
    ratinggroup                      varchar(500),
    failurehand                      varchar(500),
    conditionchange                  varchar(500),
    rulebasename                     varchar(500),
    timeoffirstusage                 varchar(500),
    timeoflastusage                  varchar(500),
    timeusage                        varchar(500),
    timeofreport                     varchar(500),
    recordopening_date               date encode az64,
    recordopening_date_num           integer,
    recordopening_month              integer,
    total_uplink_mb                  numeric(20, 4) encode az64,
    total_downlink_mb                numeric(20, 4) encode az64,
    accesspointnameni_code           varchar(10),
    recordopening_time_gmt           timestamp encode az64,
    recordopening_dt_month_gmt       integer encode az64,
    recordopening_dt_num_gmt         integer encode az64,
    recordopening_dt_hour_gmt        integer encode az64,
    filename                         varchar(50),
    batch_id                         integer encode az64,
    created_date                     timestamp encode az64,
    rec_checksum                     varchar(32)
)
    diststyle key
    sortkey (recordopening_month, recordopening_date_num, accesspointnameni);

