create table log_batch_status_mno
(
    batch_id                    integer encode az64 distkey,
    s3_batchreadcount           integer encode az64,
    s3_filecount                integer encode az64,
    intrabatch_new_normal_count integer encode az64,
    intrabatch_new_late_count   integer encode az64,
    intrabatch_dupl_count       integer encode az64,
    intrabatch_dist_dupl_count  integer encode az64,
    intrabatch_dedupl_status    varchar(20),
    dm_normal_count             integer encode az64,
    dm_normal_dbdupl_count      integer encode az64,
    dm_normal_status            varchar(20),
    ldm_latecdr_count           integer encode az64,
    ldm_latecdr_dbdupl_count    integer encode az64,
    ldm_latecdr_status          varchar(20),
    batch_start_dt              timestamp encode az64,
    batch_end_dt                timestamp encode az64,
    batch_status                varchar(50)
)
    diststyle key;

create table log_batch_files_mno
(
    batch_id                integer encode az64 distkey,
    file_source             varchar(50),
    file_id                 integer encode az64,
    file_name               varchar(50),
    batch_from              timestamp encode az64,
    batch_to                timestamp encode az64,
    record_count            integer encode az64,
    dm_normal_count         integer encode az64,
    dm_latecdr_count        integer encode az64,
    ldm_latecdr_count       integer encode az64,
    dm_normal_dbdupl_count  integer encode az64,
    dm_latecdr_dbdupl_count integer encode az64,
    is_valid                varchar(20),
    batch_createtime        timestamp encode az64
)
    diststyle key;

create table fact_mno_o2_duplcdr
(
    sk_mno_o2                 bigint default default_identity(158608, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type                  smallint encode az64,
    cdr_id                    varchar(12) encode zstd,
    network_call_reference    varchar(10),
    subscriber_imsi           bigint encode az64 distkey,
    a_number                  varchar(21) encode zstd,
    b_number                  varchar(21) encode zstd,
    dialled_digits            varchar(21) encode zstd,
    location                  varchar(5) encode zstd,
    call_forwarding_flag      varchar(1),
    smsc_address              varchar(21) encode zstd,
    charging_timestamp        timestamp encode az64,
    duration                  integer encode az64,
    rate_class                varchar(6) encode zstd,
    charge                    numeric(22, 6) encode az64,
    fragment_number           varchar(3),
    last_fragment_indicator   varchar(1),
    record_sequence_number    varchar(21) encode zstd,
    provider_id               varchar(5) encode zstd,
    service_type              varchar(10) encode zstd,
    imei                      varchar(21) encode zstd,
    message_type              varchar(11) encode zstd,
    end_user_charge           numeric(22, 6) encode az64,
    premium_sms_delivery_flag smallint encode az64,
    lyca_number               varchar(21),
    filename                  varchar(50) encode zstd,
    batch_id                  integer encode az64,
    created_date              timestamp encode az64,
    rec_checksum              varchar(32) encode zstd,
    charging_dt               date encode az64,
    charging_month            integer,
    charging_dt_num           integer,
    charging_dt_hour          integer encode az64,
    charging_timestamp_gmt    timestamp encode az64,
    charging_month_gmt        integer encode az64,
    charging_dt_num_gmt       integer encode az64,
    charging_dt_hour_gmt      integer encode az64,
    duration_min              integer encode az64
)
    diststyle key
    sortkey (charging_month, charging_dt_num);

create table fact_mno_o2_latecdr
(
    sk_mno_o2                 bigint default default_identity(158611, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type                  smallint encode az64,
    cdr_id                    varchar(12) encode zstd,
    network_call_reference    varchar(10),
    subscriber_imsi           bigint encode az64 distkey,
    a_number                  varchar(21) encode zstd,
    b_number                  varchar(21) encode zstd,
    dialled_digits            varchar(21) encode zstd,
    location                  varchar(5) encode zstd,
    call_forwarding_flag      varchar(1),
    smsc_address              varchar(21) encode zstd,
    charging_timestamp        timestamp encode az64,
    duration                  integer encode az64,
    rate_class                varchar(6) encode zstd,
    charge                    numeric(22, 6) encode az64,
    fragment_number           varchar(3),
    last_fragment_indicator   varchar(1),
    record_sequence_number    varchar(21) encode zstd,
    provider_id               varchar(5) encode zstd,
    service_type              varchar(10) encode zstd,
    imei                      varchar(21) encode zstd,
    message_type              varchar(11) encode zstd,
    end_user_charge           numeric(22, 6) encode az64,
    premium_sms_delivery_flag smallint encode az64,
    lyca_number               varchar(21),
    filename                  varchar(50) encode zstd,
    batch_id                  integer encode az64,
    created_date              timestamp encode az64,
    rec_checksum              varchar(32) encode zstd,
    charging_dt               date encode az64,
    charging_month            integer,
    charging_dt_num           integer,
    charging_dt_hour          integer encode az64,
    charging_timestamp_gmt    timestamp encode az64,
    charging_month_gmt        integer encode az64,
    charging_dt_num_gmt       integer encode az64,
    charging_dt_hour_gmt      integer encode az64,
    duration_min              integer encode az64
)
    diststyle key
    sortkey (charging_month, charging_dt_num);

create table fact_mno_o2
(
    sk_mno_o2                 bigint default default_identity(158614, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type                  smallint encode az64,
    cdr_id                    varchar(12) encode zstd,
    network_call_reference    varchar(10),
    subscriber_imsi           bigint encode az64 distkey,
    a_number                  varchar(21) encode zstd,
    b_number                  varchar(21) encode zstd,
    dialled_digits            varchar(21) encode zstd,
    location                  varchar(5) encode zstd,
    call_forwarding_flag      varchar(1),
    smsc_address              varchar(21) encode zstd,
    charging_timestamp        timestamp encode az64,
    duration                  integer encode az64,
    rate_class                varchar(6) encode zstd,
    charge                    numeric(22, 6) encode az64,
    fragment_number           varchar(3),
    last_fragment_indicator   varchar(1),
    record_sequence_number    varchar(21) encode zstd,
    provider_id               varchar(5) encode zstd,
    service_type              varchar(10) encode zstd,
    imei                      varchar(21) encode zstd,
    message_type              varchar(11) encode zstd,
    end_user_charge           numeric(22, 6) encode az64,
    premium_sms_delivery_flag smallint encode az64,
    lyca_number               varchar(21),
    filename                  varchar(50) encode zstd,
    batch_id                  integer encode az64,
    created_date              timestamp encode az64,
    rec_checksum              varchar(32) encode zstd,
    charging_dt               date encode az64,
    charging_month            integer,
    charging_dt_num           integer,
    charging_dt_hour          integer encode az64,
    charging_timestamp_gmt    timestamp encode az64,
    charging_month_gmt        integer encode az64,
    charging_dt_num_gmt       integer encode az64,
    charging_dt_hour_gmt      integer encode az64,
    duration_min              integer encode az64
)
    diststyle key
    sortkey (charging_month, charging_dt_num);

create table fact_mno_o2_data_duplcdr
(
    sk_mno_o2_data         bigint default default_identity(158617, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type               varchar(2) encode zstd,
    cdr_id                 varchar(12) encode zstd,
    imsi                   bigint encode az64 distkey,
    msisdn                 varchar(16) encode zstd,
    imei                   varchar(21) encode zstd,
    location               varchar(5) encode zstd,
    apn_ni                 varchar(63) encode zstd,
    apn_oi                 varchar(37) encode zstd,
    charging_timestamp     timestamp encode az64,
    duration               integer encode az64,
    data_volume_download   integer encode az64,
    data_volume_upload     integer encode az64,
    data_volume_total      integer encode az64,
    username               varchar(63) encode zstd,
    network_element_id     varchar(39) encode zstd,
    ggsn_address           varchar(39) encode zstd,
    charging_id            varchar(10) encode zstd,
    fragment_number        varchar(7) encode zstd,
    fragment_indicator     varchar(1) encode zstd,
    recordsequencenumber   varchar(21) encode zstd,
    content_source         varchar(30) encode zstd,
    rate_class             varchar(6) encode zstd,
    charge                 numeric(22, 6) encode zstd,
    end_user_charge        numeric(22, 6) encode az64,
    data_usage             numeric(22, 6) encode az64,
    charging_dt            date encode zstd,
    charging_month         integer encode az64,
    charging_dt_num        integer encode az64,
    charging_dt_hour       integer encode az64,
    charging_timestamp_gmt timestamp encode az64,
    charging_month_gmt     integer encode az64,
    charging_dt_num_gmt    integer encode az64,
    charging_dt_hour_gmt   integer encode az64,
    duration_min           integer encode az64,
    filename               varchar(50) encode zstd,
    batch_id               integer encode az64,
    created_date           timestamp encode az64,
    rec_checksum           varchar(32) encode zstd
)
    diststyle key
    sortkey (charging_month, charging_dt_num);

create table fact_mno_o2_data_latecdr
(
    sk_mno_o2_data         bigint default default_identity(158620, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type               varchar(2) encode zstd,
    cdr_id                 varchar(12) encode zstd,
    imsi                   bigint encode az64 distkey,
    msisdn                 varchar(16) encode zstd,
    imei                   varchar(21) encode zstd,
    location               varchar(5) encode zstd,
    apn_ni                 varchar(63) encode zstd,
    apn_oi                 varchar(37) encode zstd,
    charging_timestamp     timestamp encode az64,
    duration               integer encode az64,
    data_volume_download   integer encode az64,
    data_volume_upload     integer encode az64,
    data_volume_total      integer encode az64,
    username               varchar(63) encode zstd,
    network_element_id     varchar(39) encode zstd,
    ggsn_address           varchar(39) encode zstd,
    charging_id            varchar(10) encode zstd,
    fragment_number        varchar(7) encode zstd,
    fragment_indicator     varchar(1) encode zstd,
    recordsequencenumber   varchar(21) encode zstd,
    content_source         varchar(30) encode zstd,
    rate_class             varchar(6) encode zstd,
    charge                 numeric(22, 6) encode zstd,
    end_user_charge        numeric(22, 6) encode az64,
    data_usage             numeric(22, 6) encode az64,
    charging_dt            date encode zstd,
    charging_month         integer encode az64,
    charging_dt_num        integer encode az64,
    charging_dt_hour       integer encode az64,
    charging_timestamp_gmt timestamp encode az64,
    charging_month_gmt     integer encode az64,
    charging_dt_num_gmt    integer encode az64,
    charging_dt_hour_gmt   integer encode az64,
    duration_min           integer encode az64,
    filename               varchar(50) encode zstd,
    batch_id               integer encode az64,
    created_date           timestamp encode az64,
    rec_checksum           varchar(32) encode zstd
)
    diststyle key
    sortkey (charging_month, charging_dt_num);

create table fact_mno_o2_data
(
    sk_mno_o2_data         bigint default default_identity(158623, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type               varchar(2) encode zstd,
    cdr_id                 varchar(12) encode zstd,
    imsi                   bigint encode az64 distkey,
    msisdn                 varchar(16) encode zstd,
    imei                   varchar(21) encode zstd,
    location               varchar(5) encode zstd,
    apn_ni                 varchar(63) encode zstd,
    apn_oi                 varchar(37) encode zstd,
    charging_timestamp     timestamp encode az64,
    duration               integer encode az64,
    data_volume_download   integer encode az64,
    data_volume_upload     integer encode az64,
    data_volume_total      integer encode az64,
    username               varchar(63) encode zstd,
    network_element_id     varchar(39) encode zstd,
    ggsn_address           varchar(39) encode zstd,
    charging_id            varchar(10) encode zstd,
    fragment_number        varchar(7) encode zstd,
    fragment_indicator     varchar(1) encode zstd,
    recordsequencenumber   varchar(21) encode zstd,
    content_source         varchar(30) encode zstd,
    rate_class             varchar(6) encode zstd,
    charge                 numeric(22, 6) encode zstd,
    end_user_charge        numeric(22, 6) encode az64,
    data_usage             numeric(22, 6) encode az64,
    charging_dt            date encode zstd,
    charging_month         integer encode az64,
    charging_dt_num        integer encode az64,
    charging_dt_hour       integer encode az64,
    charging_timestamp_gmt timestamp encode az64,
    charging_month_gmt     integer encode az64,
    charging_dt_num_gmt    integer encode az64,
    charging_dt_hour_gmt   integer encode az64,
    duration_min           integer encode az64,
    filename               varchar(50) encode zstd,
    batch_id               integer encode az64,
    created_date           timestamp encode az64,
    rec_checksum           varchar(32) encode zstd
)
    diststyle key
    sortkey (charging_month, charging_dt_num);