create table log_batch_status_acinfolm
(
    batch_id                    integer encode az64,
    s3_batchreadcount           integer encode az64,
    s3_filecount                integer encode az64,
    intrabatch_new_normal_count integer encode az64,
    intrabatch_new_late_count   integer encode az64,
    intrabatch_dupl_count       integer encode az64,
    intrabatch_dist_dupl_count  integer encode az64,
    intrabatch_dedupl_status    varchar(65535),
    dm_normal_count             integer encode az64,
    dm_normal_dbdupl_count      integer encode az64,
    dm_normal_status            varchar(65535),
    ldm_latecdr_count           integer encode az64,
    ldm_latecdr_dbdupl_count    integer encode az64,
    ldm_latecdr_status          varchar(65535),
    batch_start_dt              varchar(65535),
    batch_end_dt                varchar(65535),
    batch_status                varchar(65535)
);

create table log_batch_files_acinfolm
(
    batch_id                integer encode az64 distkey,
    file_source             varchar(50),
    file_id                 integer encode az64,
    file_name               varchar(50),
    batch_from              timestamp encode az64,
    batch_to                timestamp encode az64,
    record_count            integer encode az64,
    dm_normal_count         integer encode az64,
    dm_latecdr_count        integer encode az64,
    ldm_latecdr_count       integer encode az64,
    dm_normal_dbdupl_count  integer encode az64,
    dm_latecdr_dbdupl_count integer encode az64,
    is_valid                varchar(20),
    batch_createtime        timestamp encode az64
)
    diststyle key;

create table lm_mnp_portout_request
(
    id                  bigint encode az64,
    requestid           varchar(30),
    msisdn              varchar(20),
    iccid               varchar(30),
    paccode             varchar(20),
    paccreateddate      timestamp encode az64,
    pacexpireddate      timestamp encode az64,
    portoutdate         timestamp encode az64,
    ono                 varchar(4),
    rno                 varchar(4),
    dno                 varchar(4),
    rsp                 varchar(4),
    dsp                 varchar(4),
    status              integer encode az64,
    smsstate            integer encode az64,
    errcode             varchar(50),
    recordlock          integer encode az64,
    numbertype          varchar(10),
    channel             varchar(5),
    note                varchar(100),
    blockcode           varchar(20),
    blockreason         varchar(100),
    portid              varchar(2),
    createddate         timestamp encode az64,
    createdby           varchar(50),
    completeddate       timestamp encode az64,
    poutfilename        varchar(30),
    requestfrom         varchar(20),
    preferredlanguage   varchar(20),
    smserrstate         varchar(10),
    completeddate_month integer encode az64,
    batch_id            integer encode az64,
    created_date        timestamp encode az64,
    rec_checksum        varchar(32)
);

create table lm_mnp_portout_request_duplcdr
(
    id                  bigint encode az64,
    requestid           varchar(30),
    msisdn              varchar(20),
    iccid               varchar(30),
    paccode             varchar(20),
    paccreateddate      timestamp encode az64,
    pacexpireddate      timestamp encode az64,
    portoutdate         timestamp encode az64,
    ono                 varchar(4),
    rno                 varchar(4),
    dno                 varchar(4),
    rsp                 varchar(4),
    dsp                 varchar(4),
    status              integer encode az64,
    smsstate            integer encode az64,
    errcode             varchar(50),
    recordlock          integer encode az64,
    numbertype          varchar(10),
    channel             varchar(5),
    note                varchar(100),
    blockcode           varchar(20),
    blockreason         varchar(100),
    portid              varchar(2),
    createddate         timestamp encode az64,
    createdby           varchar(50),
    completeddate       timestamp encode az64,
    poutfilename        varchar(30),
    requestfrom         varchar(20),
    preferredlanguage   varchar(20),
    smserrstate         varchar(10),
    completeddate_month integer encode az64,
    batch_id            integer encode az64,
    created_date        timestamp encode az64,
    rec_checksum        varchar(32)
);

create table lm_mnp_portin_request
(
    id                   bigint encode az64,
    requestid            varchar(30),
    msisdn               varchar(20),
    imsi                 varchar(50),
    iccid                varchar(20),
    piccid               varchar(20),
    pmsisdn              varchar(20),
    channel              varchar(10),
    requestdate          timestamp encode az64,
    status               integer encode az64,
    smsstate             integer encode az64,
    errcode              varchar(50),
    recordlock           integer encode az64,
    msgtime              timestamp encode az64,
    rno                  varchar(4),
    dno                  varchar(4),
    ono                  varchar(4),
    rsp                  varchar(4),
    dsp                  varchar(4),
    portindate           timestamp encode az64,
    note                 varchar(100),
    balance              varchar(50),
    oldbalance           varchar(50),
    newbalance           varchar(50),
    pac                  varchar(50),
    pacexpiry            timestamp encode az64,
    createddate          timestamp encode az64,
    createdby            varchar(100),
    completeddate        timestamp encode az64,
    requestfrom          varchar(20),
    firstname            varchar(100),
    lastname             varchar(100),
    email                varchar(150),
    rejectcode           varchar(10),
    attacheddocumentname varchar(100),
    preferredlanguage    varchar(20),
    smserrstate          varchar(10),
    cip                  varchar(10),
    originalmsisdn       varchar(50),
    ntype                varchar(10),
    completeddate_month  integer encode az64,
    batch_id             integer encode az64,
    created_date         timestamp encode az64,
    rec_checksum         varchar(32)
);

create table lm_mnp_portin_request_duplcdr
(
    id                   bigint encode az64,
    requestid            varchar(30),
    msisdn               varchar(20),
    imsi                 varchar(50),
    iccid                varchar(20),
    piccid               varchar(20),
    pmsisdn              varchar(20),
    channel              varchar(10),
    requestdate          timestamp encode az64,
    status               integer encode az64,
    smsstate             integer encode az64,
    errcode              varchar(50),
    recordlock           integer encode az64,
    msgtime              timestamp encode az64,
    rno                  varchar(4),
    dno                  varchar(4),
    ono                  varchar(4),
    rsp                  varchar(4),
    dsp                  varchar(4),
    portindate           timestamp encode az64,
    note                 varchar(100),
    balance              varchar(50),
    oldbalance           varchar(50),
    newbalance           varchar(50),
    pac                  varchar(50),
    pacexpiry            timestamp encode az64,
    createddate          timestamp encode az64,
    createdby            varchar(100),
    completeddate        timestamp encode az64,
    requestfrom          varchar(20),
    firstname            varchar(100),
    lastname             varchar(100),
    email                varchar(150),
    rejectcode           varchar(10),
    attacheddocumentname varchar(100),
    preferredlanguage    varchar(20),
    smserrstate          varchar(10),
    cip                  varchar(10),
    originalmsisdn       varchar(50),
    ntype                varchar(10),
    completeddate_month  integer encode az64,
    batch_id             integer encode az64,
    created_date         timestamp encode az64,
    rec_checksum         varchar(32)
);

create table lm_mnp_sp_master
(
    id               bigint encode az64,
    onocode          varchar(5),
    spcode           varchar(5),
    spdesc           varchar(50),
    status           integer encode az64,
    lastmodifiedby   varchar(50),
    lastmodifieddate timestamp encode az64,
    batch_id         integer encode az64,
    created_date     timestamp encode az64,
    rec_checksum     varchar(32)
);

create table lm_mnp_sp_master_duplcdr
(
    id               bigint encode az64,
    onocode          varchar(5),
    spcode           varchar(5),
    spdesc           varchar(50),
    status           integer encode az64,
    lastmodifiedby   varchar(50),
    lastmodifieddate timestamp encode az64,
    batch_id         integer encode az64,
    created_date     timestamp encode az64,
    rec_checksum     varchar(32)
);

create table lm_first_usage
(
    id                      bigint encode az64,
    msisdn                  varchar(20),
    imsi                    varchar(20),
    iccidprefix             varchar(15),
    iccid                   varchar(15),
    activationdate          timestamp encode az64,
    resellerid              varchar(50),
    lastusagedate           timestamp encode az64,
    retailerid              varchar(50),
    distributorid           varchar(50),
    facevalue               numeric(18) encode az64,
    processed_flag          varchar(50),
    hotspotid               varchar(50),
    accmgrid                varchar(50),
    offmgrid                varchar(50),
    swap_status             varchar(15),
    old_msisdn              varchar(15),
    old_activationdate      timestamp encode az64,
    cip_processedflag       integer encode az64,
    fcabundle_processedflag integer encode az64,
    firsttopupdate          timestamp encode az64,
    topupdate               timestamp encode az64,
    retailerid_indirect     varchar(50),
    brand                   varchar(10),
    first_iccid             varchar(100),
    iccidcomputed           varchar(15),
    fcatype                 integer encode az64,
    batch_id                integer encode az64,
    created_date            timestamp encode az64,
    rec_checksum            varchar(32)
);

create table lm_first_usage_duplcdr
(
    id                      bigint encode az64,
    msisdn                  varchar(20),
    imsi                    varchar(20),
    iccidprefix             varchar(15),
    iccid                   varchar(15),
    activationdate          timestamp encode az64,
    resellerid              varchar(50),
    lastusagedate           timestamp encode az64,
    retailerid              varchar(50),
    distributorid           varchar(50),
    facevalue               numeric(18) encode az64,
    processed_flag          varchar(50),
    hotspotid               varchar(50),
    accmgrid                varchar(50),
    offmgrid                varchar(50),
    swap_status             varchar(15),
    old_msisdn              varchar(15),
    old_activationdate      timestamp encode az64,
    cip_processedflag       integer encode az64,
    fcabundle_processedflag integer encode az64,
    firsttopupdate          timestamp encode az64,
    topupdate               timestamp encode az64,
    retailerid_indirect     varchar(50),
    brand                   varchar(10),
    first_iccid             varchar(100),
    iccidcomputed           varchar(15),
    fcatype                 integer encode az64,
    batch_id                integer encode az64,
    created_date            timestamp encode az64,
    rec_checksum            varchar(32)
);

create table lm_dsm_retailer
(
    id                          integer encode az64,
    retailerid                  varchar(25),
    hotspotid                   varchar(25),
    accmgrid                    varchar(25),
    offmgrid                    varchar(25),
    fname                       varchar(50),
    lname                       varchar(50),
    country                     varchar(50),
    state                       varchar(50),
    postcode                    varchar(10),
    houseno                     varchar(50),
    streetno                    varchar(50),
    street                      varchar(100),
    address1                    varchar(100),
    address2                    varchar(100),
    cityname                    varchar(50),
    pin                         varchar(15),
    landlineno                  varchar(15),
    mobileno                    varchar(200),
    email                       varchar(500),
    username                    varchar(100),
    contactperson               varchar(50),
    status                      integer encode az64,
    invoicetype                 varchar(25),
    createdby                   varchar(50),
    createddate                 timestamp encode az64,
    threshold                   integer encode az64,
    updatedby                   varchar(50),
    updateddate                 timestamp encode az64,
    authlevel                   integer encode az64,
    comments                    varchar(200),
    optionalstatus              smallint encode az64,
    delauthlevel                integer encode az64,
    editauthlevel               integer encode az64,
    historyid                   integer encode az64,
    alternatemobileno           varchar(25),
    bankaddress                 varchar(200),
    accountholdername           varchar(100),
    accountsortcode             varchar(20),
    accountnumber               varchar(20),
    bankname                    varchar(50),
    sitecode                    varchar(3),
    password                    varchar(100),
    shoptype                    varchar(50),
    whitelistmsisdn             varchar(16),
    transfer_balance            numeric(38, 10) encode az64,
    cc_balance                  numeric(38, 10) encode az64,
    accumulated_discount        numeric(38, 10) encode az64,
    groupid                     integer encode az64,
    retailermode                integer encode az64,
    virtual_msisdn              varchar(20),
    virtualtorealdate           timestamp encode az64,
    floorno                     varchar(50),
    passexpiredate              timestamp encode az64,
    lastlogindate               timestamp encode az64,
    isthreshold                 integer encode az64,
    secretquestion              varchar(200),
    secretanswer                varchar(100),
    issecqnalert                integer encode az64,
    unique_urn                  varchar(20),
    thresholdexcludedon         timestamp encode az64,
    iscredithigherlayer         integer encode az64,
    preferlanguage              varchar(50),
    is_specialretailer          smallint encode az64,
    spl_retupd_date             timestamp encode az64,
    commision_groupid           integer encode az64,
    loginattempt                integer encode az64,
    lockeddatetime              timestamp encode az64,
    area                        varchar(100),
    district                    varchar(100),
    vatno                       varchar(100),
    simactivationamount2        numeric(38, 10) encode az64,
    creditlimitamt              numeric(38, 10) encode az64,
    creditlimitauthdate         timestamp encode az64,
    stockotp                    varchar(20),
    stock_modifiedby            varchar(50),
    stock_modifieddate          timestamp encode az64,
    isbalancenegative           smallint encode az64,
    is_mailsent                 smallint encode az64,
    stocknotification           smallint encode az64,
    notificationonoffuploaddate timestamp encode az64,
    isreplicate                 smallint encode az64,
    sbtretaileredit             smallint encode az64,
    streetnumber                varchar(100),
    estate                      varchar(100),
    airtime_transfer            smallint encode az64,
    ispwdsent                   smallint encode az64,
    division                    varchar(100),
    requested_by                varchar(100),
    requested_date              timestamp encode az64,
    preapproved_by              varchar(100),
    preapproved_date            timestamp encode az64,
    approved_by                 varchar(100),
    approved_date               timestamp encode az64,
    freeze_status               integer encode az64,
    freezereason                varchar(500),
    edit_reason                 varchar(1000),
    tran_pin                    varchar(50),
    pinretryattempts            integer encode az64,
    pinlockeddate               timestamp encode az64,
    ret_auto_ballimit           numeric(38, 10) encode az64,
    ret_auto_topupamt           numeric(38, 10) encode az64,
    ret_auto_lmtfreq            integer encode az64,
    ret_auto_maxlmt             integer encode az64,
    ret_autotopup_chk           integer encode az64,
    ret_auto_frmdt              timestamp encode az64,
    ret_auto_todt               timestamp encode az64,
    ret_auto_prscnt             integer encode az64,
    ret_uuid                    varchar(100),
    agentmsisdn                 varchar(16),
    agentpin                    varchar(15),
    isagent                     integer encode az64,
    taxid                       varchar(100),
    businessregistrationno      varchar(100),
    socialsecurityno            varchar(100),
    batch_id                    integer encode az64,
    created_date                timestamp encode az64,
    rec_checksum                varchar(32)
);

create table lm_dsm_retailer_duplcdr
(
    id                          integer encode az64,
    retailerid                  varchar(25),
    hotspotid                   varchar(25),
    accmgrid                    varchar(25),
    offmgrid                    varchar(25),
    fname                       varchar(50),
    lname                       varchar(50),
    country                     varchar(50),
    state                       varchar(50),
    postcode                    varchar(10),
    houseno                     varchar(50),
    streetno                    varchar(50),
    street                      varchar(100),
    address1                    varchar(100),
    address2                    varchar(100),
    cityname                    varchar(50),
    pin                         varchar(15),
    landlineno                  varchar(15),
    mobileno                    varchar(200),
    email                       varchar(500),
    username                    varchar(100),
    contactperson               varchar(50),
    status                      integer encode az64,
    invoicetype                 varchar(25),
    createdby                   varchar(50),
    createddate                 timestamp encode az64,
    threshold                   integer encode az64,
    updatedby                   varchar(50),
    updateddate                 timestamp encode az64,
    authlevel                   integer encode az64,
    comments                    varchar(200),
    optionalstatus              smallint encode az64,
    delauthlevel                integer encode az64,
    editauthlevel               integer encode az64,
    historyid                   integer encode az64,
    alternatemobileno           varchar(25),
    bankaddress                 varchar(200),
    accountholdername           varchar(100),
    accountsortcode             varchar(20),
    accountnumber               varchar(20),
    bankname                    varchar(50),
    sitecode                    varchar(3),
    password                    varchar(100),
    shoptype                    varchar(50),
    whitelistmsisdn             varchar(16),
    transfer_balance            numeric(38, 10) encode az64,
    cc_balance                  numeric(38, 10) encode az64,
    accumulated_discount        numeric(38, 10) encode az64,
    groupid                     integer encode az64,
    retailermode                integer encode az64,
    virtual_msisdn              varchar(20),
    virtualtorealdate           timestamp encode az64,
    floorno                     varchar(50),
    passexpiredate              timestamp encode az64,
    lastlogindate               timestamp encode az64,
    isthreshold                 integer encode az64,
    secretquestion              varchar(200),
    secretanswer                varchar(100),
    issecqnalert                integer encode az64,
    unique_urn                  varchar(20),
    thresholdexcludedon         timestamp encode az64,
    iscredithigherlayer         integer encode az64,
    preferlanguage              varchar(50),
    is_specialretailer          smallint encode az64,
    spl_retupd_date             timestamp encode az64,
    commision_groupid           integer encode az64,
    loginattempt                integer encode az64,
    lockeddatetime              timestamp encode az64,
    area                        varchar(100),
    district                    varchar(100),
    vatno                       varchar(100),
    simactivationamount2        numeric(38, 10) encode az64,
    creditlimitamt              numeric(38, 10) encode az64,
    creditlimitauthdate         timestamp encode az64,
    stockotp                    varchar(20),
    stock_modifiedby            varchar(50),
    stock_modifieddate          timestamp encode az64,
    isbalancenegative           smallint encode az64,
    is_mailsent                 smallint encode az64,
    stocknotification           smallint encode az64,
    notificationonoffuploaddate timestamp encode az64,
    isreplicate                 smallint encode az64,
    sbtretaileredit             smallint encode az64,
    streetnumber                varchar(100),
    estate                      varchar(100),
    airtime_transfer            smallint encode az64,
    ispwdsent                   smallint encode az64,
    division                    varchar(100),
    requested_by                varchar(100),
    requested_date              timestamp encode az64,
    preapproved_by              varchar(100),
    preapproved_date            timestamp encode az64,
    approved_by                 varchar(100),
    approved_date               timestamp encode az64,
    freeze_status               integer encode az64,
    freezereason                varchar(500),
    edit_reason                 varchar(1000),
    tran_pin                    varchar(50),
    pinretryattempts            integer encode az64,
    pinlockeddate               timestamp encode az64,
    ret_auto_ballimit           numeric(38, 10) encode az64,
    ret_auto_topupamt           numeric(38, 10) encode az64,
    ret_auto_lmtfreq            integer encode az64,
    ret_auto_maxlmt             integer encode az64,
    ret_autotopup_chk           integer encode az64,
    ret_auto_frmdt              timestamp encode az64,
    ret_auto_todt               timestamp encode az64,
    ret_auto_prscnt             integer encode az64,
    ret_uuid                    varchar(100),
    agentmsisdn                 varchar(16),
    agentpin                    varchar(15),
    isagent                     integer encode az64,
    taxid                       varchar(100),
    businessregistrationno      varchar(100),
    socialsecurityno            varchar(100),
    batch_id                    integer encode az64,
    created_date                timestamp encode az64,
    rec_checksum                varchar(32)
);

create table lm_mnp_onorange
(
    id               bigint encode az64,
    onocode          varchar(5),
    prefix           bigint encode az64,
    status           integer encode az64,
    lastmodifiedby   varchar(50),
    lastmodifieddate timestamp encode az64,
    batch_id         integer encode az64,
    created_date     timestamp encode az64,
    rec_checksum     varchar(32)
);

create table lm_mnp_onorange_duplcdr
(
    id               bigint encode az64,
    onocode          varchar(5),
    prefix           bigint encode az64,
    status           integer encode az64,
    lastmodifiedby   varchar(50),
    lastmodifieddate timestamp encode az64,
    batch_id         integer encode az64,
    created_date     timestamp encode az64,
    rec_checksum     varchar(32)
);

create table lm_mnp_lycasp_master
(
    id               bigint encode az64,
    onocode          varchar(5),
    spcode           varchar(5),
    spdesc           varchar(50),
    status           integer encode az64,
    url              varchar(500),
    uid              varchar(50),
    pwd              varchar(50),
    lastmodifiedby   varchar(50),
    lastmodifieddate timestamp encode az64,
    batch_id         integer encode az64,
    created_date     timestamp encode az64,
    rec_checksum     varchar(32)
);

create table lm_mnp_lycasp_master_duplcdr
(
    id               bigint encode az64,
    onocode          varchar(5),
    spcode           varchar(5),
    spdesc           varchar(50),
    status           integer encode az64,
    url              varchar(500),
    uid              varchar(50),
    pwd              varchar(50),
    lastmodifiedby   varchar(50),
    lastmodifieddate timestamp encode az64,
    batch_id         integer encode az64,
    created_date     timestamp encode az64,
    rec_checksum     varchar(32)
);

create table lm_mnp_ono_master
(
    id               bigint encode az64,
    onocode          varchar(5),
    description      varchar(50),
    ccndc            varchar(50),
    status           integer encode az64,
    lastmodifiedby   varchar(50),
    lastmodifieddate timestamp encode az64,
    ftncode          varchar(10),
    batch_id         integer encode az64,
    created_date     timestamp encode az64,
    rec_checksum     varchar(32)
);

create table lm_mnp_ono_master_duplcdr
(
    id               bigint encode az64,
    onocode          varchar(5),
    description      varchar(50),
    ccndc            varchar(50),
    status           integer encode az64,
    lastmodifiedby   varchar(50),
    lastmodifieddate timestamp encode az64,
    ftncode          varchar(10),
    batch_id         integer encode az64,
    created_date     timestamp encode az64,
    rec_checksum     varchar(32)
);

create table lm_trn_voucher_activation
(
    voucherid             integer encode az64,
    sitecode              varchar(3),
    card_id               varchar(4),
    source_batch_id       varchar(6),
    serial_fr             varchar(4),
    serial_to             varchar(4),
    totalcards            integer encode az64,
    resellerid            varchar(25),
    actstate              integer encode az64,
    expiryyy              integer encode az64,
    expirymm              integer encode az64,
    expirydd              integer encode az64,
    facevalue             numeric(38, 10) encode az64,
    sellprice             numeric(38, 10) encode az64,
    vat                   integer encode az64,
    discount              numeric(5, 2) encode az64,
    netprice              numeric(38, 10) encode az64,
    validity              integer encode az64,
    invoicenumber         varchar(17),
    submitby              varchar(25),
    submitdate            timestamp encode az64,
    crcheckby             varchar(25),
    crcheckdate           timestamp encode az64,
    preactby              varchar(25),
    preactdate            timestamp encode az64,
    authby                varchar(25),
    authdate              timestamp encode az64,
    blockby               varchar(25),
    blockdate             timestamp encode az64,
    blockreason           varchar(100),
    huaweisubmitstate     varchar(1),
    huaweierrcode         varchar(4),
    recordlock            varchar(1),
    processid             integer encode az64,
    ponumber              varchar(200),
    activated_vouchers    integer encode az64,
    record_processed_time timestamp encode az64,
    vouchertype           integer encode az64,
    card_currency         varchar(50),
    description           varchar(100),
    bundlecode            integer encode az64,
    bundlecost            numeric(38, 10) encode az64,
    total_fee_amt         numeric(38, 10) encode az64,
    fee_breakup           varchar(500),
    batch_id              integer encode az64,
    created_date          timestamp encode az64,
    rec_checksum          varchar(32)
);

create table lm_trn_voucher_activation_duplcdr
(
    voucherid             integer encode az64,
    sitecode              varchar(3),
    card_id               varchar(4),
    source_batch_id       varchar(6),
    serial_fr             varchar(4),
    serial_to             varchar(4),
    totalcards            integer encode az64,
    resellerid            varchar(25),
    actstate              integer encode az64,
    expiryyy              integer encode az64,
    expirymm              integer encode az64,
    expirydd              integer encode az64,
    facevalue             numeric(38, 10) encode az64,
    sellprice             numeric(38, 10) encode az64,
    vat                   integer encode az64,
    discount              numeric(5, 2) encode az64,
    netprice              numeric(38, 10) encode az64,
    validity              integer encode az64,
    invoicenumber         varchar(17),
    submitby              varchar(25),
    submitdate            timestamp encode az64,
    crcheckby             varchar(25),
    crcheckdate           timestamp encode az64,
    preactby              varchar(25),
    preactdate            timestamp encode az64,
    authby                varchar(25),
    authdate              timestamp encode az64,
    blockby               varchar(25),
    blockdate             timestamp encode az64,
    blockreason           varchar(100),
    huaweisubmitstate     varchar(1),
    huaweierrcode         varchar(4),
    recordlock            varchar(1),
    processid             integer encode az64,
    ponumber              varchar(200),
    activated_vouchers    integer encode az64,
    record_processed_time timestamp encode az64,
    vouchertype           integer encode az64,
    card_currency         varchar(50),
    description           varchar(100),
    bundlecode            integer encode az64,
    bundlecost            numeric(38, 10) encode az64,
    total_fee_amt         numeric(38, 10) encode az64,
    fee_breakup           varchar(500),
    batch_id              integer encode az64,
    created_date          timestamp encode az64,
    rec_checksum          varchar(32)
);

create table lm_trn_re_credit
(
    id             integer encode az64,
    msisdn         varchar(20),
    recreditamt    numeric(38, 10) encode az64,
    ticketid       bigint encode az64,
    reason         varchar(20),
    dialledmsisdn  varchar(15),
    dialleddate    varchar(20),
    duration       varchar(10),
    comments       varchar(200),
    requestdate    timestamp encode az64,
    submitedby     varchar(50),
    status         varchar(20),
    authorisedby   varchar(50),
    authoriseddate timestamp encode az64,
    oldbal         numeric(38, 10) encode az64,
    newbal         numeric(38, 10) encode az64,
    channel        varchar(15),
    authcomments   varchar(200),
    transactionid  varchar(20),
    smsdate        timestamp encode az64,
    batch_id       integer encode az64,
    created_date   timestamp encode az64,
    rec_checksum   varchar(32)
);

create table lm_trn_debit
(
    id             integer encode az64,
    msisdn         varchar(20),
    debitamt       numeric(38, 10) encode az64,
    ticketid       bigint encode az64,
    reason         varchar(20),
    comments       varchar(200),
    requestdate    timestamp encode az64,
    submitedby     varchar(50),
    status         varchar(20),
    authorisedby   varchar(50),
    authoriseddate timestamp encode az64,
    oldbal         numeric(38, 10) encode az64,
    newbal         numeric(38, 10) encode az64,
    channel        varchar(15),
    authcomments   varchar(200),
    batch_id       integer encode az64,
    created_date   timestamp encode az64,
    rec_checksum   varchar(32)
);

create table lm_trn_debit_duplcdr
(
    id             integer encode az64,
    msisdn         varchar(20),
    debitamt       numeric(38, 10) encode az64,
    ticketid       bigint encode az64,
    reason         varchar(20),
    comments       varchar(200),
    requestdate    timestamp encode az64,
    submitedby     varchar(50),
    status         varchar(20),
    authorisedby   varchar(50),
    authoriseddate timestamp encode az64,
    oldbal         numeric(38, 10) encode az64,
    newbal         numeric(38, 10) encode az64,
    channel        varchar(15),
    authcomments   varchar(200),
    batch_id       integer encode az64,
    created_date   timestamp encode az64,
    rec_checksum   varchar(32)
);

create table lm_tbl_wp_transaction_log_duplcdr
(
    id                          integer encode az64,
    subscriberid                varchar(20),
    cardnumber                  varchar(200),
    transactionid               varchar(30),
    transactiontype             varchar(2),
    orderid                     varchar(20),
    orderdescription            varchar(50),
    orderdatetime               timestamp encode az64,
    merchantcode                varchar(30),
    paymentmethodcode           varchar(30),
    statuscode                  varchar(30),
    responsecode                varchar(10),
    responsedescription         varchar(1000),
    responsedatetime            timestamp encode az64,
    sessionid                   varchar(50),
    echodata                    varchar(20),
    riskscore                   varchar(10),
    cvcresultcode               varchar(50),
    avsresultcode               varchar(50),
    aavaddressresultcode        varchar(50),
    aavpostcoderesultcode       varchar(50),
    aavcardholdernameresultcode varchar(50),
    aavtelephoneresultcode      varchar(50),
    aavemailresultcode          varchar(50),
    createddate                 timestamp encode az64,
    apmmac                      varchar(50),
    apmreferenceid              varchar(50),
    issuerurl                   varchar(1000),
    rgprofileid                 varchar(50),
    vatid                       varchar(30),
    capturedrequest             varchar(5),
    capturedresponse            varchar(50),
    batch_id                    integer encode az64,
    created_date                timestamp encode az64,
    rec_checksum                varchar(32)
);

create table lm_tbl_red_transaction_log
(
    id                 integer encode az64,
    subscriberid       varchar(20),
    cardnumber         varchar(200),
    transactionid      varchar(30),
    transactiontype    varchar(2),
    redorderid         varchar(20),
    divisionnumber     varchar(20),
    redkeyid           integer encode az64,
    requestid          varchar(20),
    requesttypecode    varchar(20),
    statuscode         varchar(20),
    responsecode       varchar(20),
    responsedate       timestamp encode az64,
    fraudstatuscode    varchar(20),
    redtdsstatuscode   varchar(20),
    reddtssig          varchar(20),
    redtdseci          varchar(20),
    redorderdatetime   timestamp encode az64,
    redauthnumber      varchar(20),
    redresponsemessage varchar(50),
    redavscode         varchar(20),
    redseccode         varchar(20),
    fraudresponsecode  varchar(20),
    fraudusecode       varchar(20),
    fraudrcf           varchar(20),
    createddate        timestamp encode az64,
    tdsacsurl          varchar(65535),
    ebt_name           varchar(50),
    ebt_service        varchar(50),
    vatid              varchar(30),
    connectortxnid     varchar(50),
    bankname           varchar(100),
    bankcountry        varchar(50),
    buildnumber        varchar(20),
    ndc                varchar(50),
    riskscore          varchar(10),
    batch_id           integer encode az64,
    created_date       timestamp encode az64,
    rec_checksum       varchar(32)
);

create table lm_tbl_red_transaction_log_duplcdr
(
    id                 integer encode az64,
    subscriberid       varchar(20),
    cardnumber         varchar(200),
    transactionid      varchar(30),
    transactiontype    varchar(2),
    redorderid         varchar(20),
    divisionnumber     varchar(20),
    redkeyid           integer encode az64,
    requestid          varchar(20),
    requesttypecode    varchar(20),
    statuscode         varchar(20),
    responsecode       varchar(20),
    responsedate       timestamp encode az64,
    fraudstatuscode    varchar(20),
    redtdsstatuscode   varchar(20),
    reddtssig          varchar(20),
    redtdseci          varchar(20),
    redorderdatetime   timestamp encode az64,
    redauthnumber      varchar(20),
    redresponsemessage varchar(50),
    redavscode         varchar(20),
    redseccode         varchar(20),
    fraudresponsecode  varchar(20),
    fraudusecode       varchar(20),
    fraudrcf           varchar(20),
    createddate        timestamp encode az64,
    tdsacsurl          varchar(65535),
    ebt_name           varchar(50),
    ebt_service        varchar(50),
    vatid              varchar(30),
    connectortxnid     varchar(50),
    bankname           varchar(100),
    bankcountry        varchar(50),
    buildnumber        varchar(20),
    ndc                varchar(50),
    riskscore          varchar(10),
    batch_id           integer encode az64,
    created_date       timestamp encode az64,
    rec_checksum       varchar(32)
);

create table lm_tbl_ingenico_transaction_log
(
    id                       integer encode az64,
    transactionid            varchar(30),
    subscriberid             varchar(20),
    cardnumber               varchar(200),
    cardexpirydate           date encode az64,
    transactiontype          varchar(2),
    orderid                  varchar(20),
    merchantcode             varchar(30),
    paymentmethodcode        varchar(30),
    statuscode               varchar(30),
    responsecode             varchar(20),
    responsedescription      varchar(4000),
    cvcresultcode            varchar(50),
    avsresultcode            varchar(50),
    paymentid                varchar(30),
    paymentrefernce          varchar(200),
    merchantreference        varchar(200),
    paymentmethod            varchar(30),
    paymentproductid         integer encode az64,
    authorizationcode        varchar(20),
    fraudserviceresult       varchar(30),
    iscancelable             varchar(10),
    isauthorized             varchar(10),
    statuscodechangedatetime timestamp encode az64,
    additionalreference      varchar(30),
    externalreference        varchar(30),
    cavv                     varchar(30),
    cavvalgorithm            varchar(100),
    eci                      varchar(100),
    validationresult         varchar(30),
    xid                      varchar(30),
    isrecurring              varchar(10),
    returnurl                varchar(1000),
    tokenid                  varchar(200),
    isnewtoken               varchar(10),
    createddate              timestamp encode az64,
    batch_id                 integer encode az64,
    created_date             timestamp encode az64,
    rec_checksum             varchar(32)
);

create table lm_tbl_wp_transaction_log
(
    id                          integer encode az64,
    subscriberid                varchar(20),
    cardnumber                  varchar(200),
    transactionid               varchar(30),
    transactiontype             varchar(2),
    orderid                     varchar(20),
    orderdescription            varchar(50),
    orderdatetime               timestamp encode az64,
    merchantcode                varchar(30),
    paymentmethodcode           varchar(30),
    statuscode                  varchar(30),
    responsecode                varchar(10),
    responsedescription         varchar(1000),
    responsedatetime            timestamp encode az64,
    sessionid                   varchar(50),
    echodata                    varchar(20),
    riskscore                   varchar(10),
    cvcresultcode               varchar(50),
    avsresultcode               varchar(50),
    aavaddressresultcode        varchar(50),
    aavpostcoderesultcode       varchar(50),
    aavcardholdernameresultcode varchar(50),
    aavtelephoneresultcode      varchar(50),
    aavemailresultcode          varchar(50),
    createddate                 timestamp encode az64,
    apmmac                      varchar(50),
    apmreferenceid              varchar(50),
    issuerurl                   varchar(1000),
    rgprofileid                 varchar(50),
    vatid                       varchar(30),
    capturedrequest             varchar(5),
    capturedresponse            varchar(50),
    batch_id                    integer encode az64,
    created_date                timestamp encode az64,
    rec_checksum                varchar(32)
);

create table lm_tbl_ingenico_transaction_log_duplcdr
(
    id                       integer encode az64,
    transactionid            varchar(30),
    subscriberid             varchar(20),
    cardnumber               varchar(200),
    cardexpirydate           date encode az64,
    transactiontype          varchar(2),
    orderid                  varchar(20),
    merchantcode             varchar(30),
    paymentmethodcode        varchar(30),
    statuscode               varchar(30),
    responsecode             varchar(20),
    responsedescription      varchar(4000),
    cvcresultcode            varchar(50),
    avsresultcode            varchar(50),
    paymentid                varchar(30),
    paymentrefernce          varchar(200),
    merchantreference        varchar(200),
    paymentmethod            varchar(30),
    paymentproductid         integer encode az64,
    authorizationcode        varchar(20),
    fraudserviceresult       varchar(30),
    iscancelable             varchar(10),
    isauthorized             varchar(10),
    statuscodechangedatetime timestamp encode az64,
    additionalreference      varchar(30),
    externalreference        varchar(30),
    cavv                     varchar(30),
    cavvalgorithm            varchar(100),
    eci                      varchar(100),
    validationresult         varchar(30),
    xid                      varchar(30),
    isrecurring              varchar(10),
    returnurl                varchar(1000),
    tokenid                  varchar(200),
    isnewtoken               varchar(10),
    createddate              timestamp encode az64,
    batch_id                 integer encode az64,
    created_date             timestamp encode az64,
    rec_checksum             varchar(32)
);

create table lm_recycled_firstusage
(
    id                integer encode az64,
    month             varchar(20),
    network_id        varchar(10),
    msisdn            varchar(20),
    msisdn_swap       varchar(20),
    iccidprefix       varchar(20),
    iccid             varchar(30),
    imsi              varchar(30),
    imsi2             varchar(30),
    last_usage_date   timestamp encode az64,
    balance           numeric(18) encode az64,
    production_status varchar(100),
    activationdate    timestamp encode az64,
    registrationdate  timestamp encode az64,
    last_call_date    varchar(30),
    last_msg_date     varchar(30),
    last_top_date     varchar(30),
    hlrid             varchar(10),
    deactivationdate  timestamp encode az64,
    initialbal        numeric(18) encode az64,
    acc_id            varchar(50),
    resellerid        varchar(50),
    offmgrid          varchar(50),
    accmgrid          varchar(50),
    hotspotid         varchar(50),
    retailerid        varchar(50),
    distributorid     varchar(50),
    filedate          date encode az64,
    facevalue         numeric(18) encode az64,
    first_iccid       varchar(100),
    batch_id          integer encode az64,
    created_date      timestamp encode az64,
    rec_checksum      varchar(32)
);

create table lm_recycled_firstusage_duplcdr
(
    id                integer encode az64,
    month             varchar(20),
    network_id        varchar(10),
    msisdn            varchar(20),
    msisdn_swap       varchar(20),
    iccidprefix       varchar(20),
    iccid             varchar(30),
    imsi              varchar(30),
    imsi2             varchar(30),
    last_usage_date   timestamp encode az64,
    balance           numeric(18) encode az64,
    production_status varchar(100),
    activationdate    timestamp encode az64,
    registrationdate  timestamp encode az64,
    last_call_date    varchar(30),
    last_msg_date     varchar(30),
    last_top_date     varchar(30),
    hlrid             varchar(10),
    deactivationdate  timestamp encode az64,
    initialbal        numeric(18) encode az64,
    acc_id            varchar(50),
    resellerid        varchar(50),
    offmgrid          varchar(50),
    accmgrid          varchar(50),
    hotspotid         varchar(50),
    retailerid        varchar(50),
    distributorid     varchar(50),
    filedate          date encode az64,
    facevalue         numeric(18) encode az64,
    first_iccid       varchar(100),
    batch_id          integer encode az64,
    created_date      timestamp encode az64,
    rec_checksum      varchar(32)
);

create table lm_mstswapimsi
(
    reqid                integer encode az64,
    oldmsisdn            varchar(20),
    oldiccid             varchar(20),
    oldimsi              varchar(15),
    newmsisdn            varchar(20),
    newiccid             varchar(20),
    newimsi              varchar(15),
    ticketid             integer encode az64,
    requestby            varchar(50),
    requestdate          timestamp encode az64,
    status               varchar(4),
    authorisedby         varchar(50),
    authoriseddate       timestamp encode az64,
    frequentcallednumber varchar(15),
    topupamount          numeric(38, 10) encode az64,
    topupdate            timestamp encode az64,
    cip                  varchar(4),
    pannumber            varchar(20),
    admin_comments       varchar(250),
    firstname            varchar(200),
    dob                  timestamp encode az64,
    docno                varchar(50),
    doctype              varchar(50),
    doe                  timestamp encode az64,
    zipcode              varchar(40),
    channel              varchar(40),
    migration            varchar(40),
    batch_id             integer encode az64,
    created_date         timestamp encode az64,
    rec_checksum         varchar(32)
);

create table lm_mst_swap_imsi_duplcdr
(
    reqid                integer encode az64,
    oldmsisdn            varchar(20),
    oldiccid             varchar(20),
    oldimsi              varchar(15),
    newmsisdn            varchar(20),
    newiccid             varchar(20),
    newimsi              varchar(15),
    ticketid             integer encode az64,
    requestby            varchar(50),
    requestdate          timestamp encode az64,
    status               varchar(4),
    authorisedby         varchar(50),
    authoriseddate       timestamp encode az64,
    frequentcallednumber varchar(15),
    topupamount          numeric(38, 10) encode az64,
    topupdate            timestamp encode az64,
    cip                  varchar(4),
    pannumber            varchar(20),
    admin_comments       varchar(250),
    firstname            varchar(200),
    dob                  timestamp encode az64,
    docno                varchar(50),
    doctype              varchar(50),
    doe                  timestamp encode az64,
    zipcode              varchar(40),
    channel              varchar(40),
    migration            varchar(40),
    batch_id             integer encode az64,
    created_date         timestamp encode az64,
    rec_checksum         varchar(32)
);

create table lm_mst_mvno_account
(
    id                       bigint encode az64,
    msisdn                   varchar(20),
    msisdn_swap              varchar(20),
    custcode                 varchar(8),
    batchcode                integer encode az64,
    serialcode               integer encode az64,
    iccidprefix              varchar(8),
    iccid                    varchar(20),
    imsi                     varchar(20),
    swapimsi                 varchar(20),
    imsi2                    varchar(20),
    pin1                     varchar(10),
    pin2                     varchar(10),
    puk1                     varchar(8),
    puk2                     varchar(8),
    scpsubmitstate           varchar(1),
    scperrcode               varchar(4),
    recordlock               varchar(1),
    processid                integer encode az64,
    status                   integer encode az64,
    pim                      integer encode az64,
    msisdn_flag              smallint encode az64,
    tariffclassname          varchar(20),
    initialbal               varchar(50),
    initiallang              varchar(50),
    mo_calls                 integer encode az64,
    mt_calls                 integer encode az64,
    mo_roam_calls            integer encode az64,
    mt_roam_calls            integer encode az64,
    mo_sms                   integer encode az64,
    mt_sms                   integer encode az64,
    mo_roam_sms              integer encode az64,
    mt_roam_sms              integer encode az64,
    ivr                      integer encode az64,
    ussd                     integer encode az64,
    vms                      integer encode az64,
    sms_topup                integer encode az64,
    mha                      integer encode az64,
    mca                      integer encode az64,
    gprs                     integer encode az64,
    crbt                     integer encode az64,
    hlrid                    varchar(10),
    mhaaccid                 varchar(20),
    mhapin                   varchar(20),
    smsmarketing             integer encode az64,
    actdate                  timestamp encode az64,
    iccidcomputed            varchar(15),
    cip                      varchar(4),
    mask_mode                smallint encode az64,
    eatariffchangestatus     integer encode az64,
    eatariffclassname        varchar(15),
    suspendsimswaprequest    smallint encode az64,
    suspendmsisdnswaprequest smallint encode az64,
    suspendportoutrequest    smallint encode az64,
    resellerid               varchar(25),
    batch_id                 integer encode az64,
    created_date             timestamp encode az64,
    rec_checksum             varchar(32)
);

create table lm_mst_mvno_account_duplcdr
(
    id                       bigint encode az64,
    msisdn                   varchar(20),
    msisdn_swap              varchar(20),
    custcode                 varchar(8),
    batchcode                integer encode az64,
    serialcode               integer encode az64,
    iccidprefix              varchar(8),
    iccid                    varchar(20),
    imsi                     varchar(20),
    swapimsi                 varchar(20),
    imsi2                    varchar(20),
    pin1                     varchar(10),
    pin2                     varchar(10),
    puk1                     varchar(8),
    puk2                     varchar(8),
    scpsubmitstate           varchar(1),
    scperrcode               varchar(4),
    recordlock               varchar(1),
    processid                integer encode az64,
    status                   integer encode az64,
    pim                      integer encode az64,
    msisdn_flag              smallint encode az64,
    tariffclassname          varchar(20),
    initialbal               varchar(50),
    initiallang              varchar(50),
    mo_calls                 integer encode az64,
    mt_calls                 integer encode az64,
    mo_roam_calls            integer encode az64,
    mt_roam_calls            integer encode az64,
    mo_sms                   integer encode az64,
    mt_sms                   integer encode az64,
    mo_roam_sms              integer encode az64,
    mt_roam_sms              integer encode az64,
    ivr                      integer encode az64,
    ussd                     integer encode az64,
    vms                      integer encode az64,
    sms_topup                integer encode az64,
    mha                      integer encode az64,
    mca                      integer encode az64,
    gprs                     integer encode az64,
    crbt                     integer encode az64,
    hlrid                    varchar(10),
    mhaaccid                 varchar(20),
    mhapin                   varchar(20),
    smsmarketing             integer encode az64,
    actdate                  timestamp encode az64,
    iccidcomputed            varchar(15),
    cip                      varchar(4),
    mask_mode                smallint encode az64,
    eatariffchangestatus     integer encode az64,
    eatariffclassname        varchar(15),
    suspendsimswaprequest    smallint encode az64,
    suspendmsisdnswaprequest smallint encode az64,
    suspendportoutrequest    smallint encode az64,
    resellerid               varchar(25),
    batch_id                 integer encode az64,
    created_date             timestamp encode az64,
    rec_checksum             varchar(32)
);

create table lm_mst_swap_imsi
(
    reqid                integer encode az64,
    oldmsisdn            varchar(20),
    oldiccid             varchar(20),
    oldimsi              varchar(15),
    newmsisdn            varchar(20),
    newiccid             varchar(20),
    newimsi              varchar(15),
    ticketid             integer encode az64,
    requestby            varchar(50),
    requestdate          timestamp encode az64,
    status               varchar(4),
    authorisedby         varchar(50),
    authoriseddate       timestamp encode az64,
    frequentcallednumber varchar(15),
    topupamount          numeric(38, 10) encode az64,
    topupdate            timestamp encode az64,
    cip                  varchar(4),
    pannumber            varchar(20),
    admin_comments       varchar(250),
    firstname            varchar(200),
    dob                  timestamp encode az64,
    docno                varchar(50),
    doctype              varchar(50),
    doe                  timestamp encode az64,
    zipcode              varchar(40),
    channel              varchar(40),
    migration            varchar(40),
    batch_id             integer encode az64,
    created_date         timestamp encode az64,
    rec_checksum         varchar(32)
);

create table lm_mst_free_sim_customer_activation
(
    id                      integer encode az64,
    transactionid           varchar(50),
    redorderid              varchar(50),
    pinnumber               varchar(20),
    status                  varchar(3),
    postcode                varchar(100),
    typeofsim               varchar(20),
    topupamount             numeric(38, 10) encode az64,
    cardid                  varchar(10),
    nabundleamount          numeric(38, 10) encode az64,
    inabundleamount         numeric(38, 10) encode az64,
    nabundlecode            integer encode az64,
    inabundlecode           integer encode az64,
    imsi                    varchar(20),
    msisdn_real             varchar(20),
    msisdn_dummy            varchar(20),
    activateddate           timestamp encode az64,
    activatedchannel        varchar(20),
    errordesc               varchar(200),
    requestdate             timestamp encode az64,
    processeddate           timestamp encode az64,
    modeofpayment           varchar(20),
    autorenewal             varchar(5),
    planid                  integer encode az64,
    promocode               varchar(20),
    promoofferid            integer encode az64,
    promotype               varchar(2),
    promodiscounttype       varchar(2),
    promodiscountvalue      numeric(38, 10) encode az64,
    shippingamount          numeric(38, 10) encode az64,
    shippingpromocode       varchar(20),
    shippingdiscounttype    varchar(2),
    shippingdiscountvalue   numeric(38, 10) encode az64,
    shippromodiscountstatus varchar(5),
    totaltax                numeric(38, 10) encode az64,
    tax                     numeric(38, 10) encode az64,
    obacreditdue            numeric(38, 10) encode az64,
    subtransactionid        varchar(50),
    vattransid              varchar(16),
    vatamount               numeric(38, 10) encode az64,
    vatperc                 numeric(5, 2) encode az64,
    bundlemonths            integer encode az64,
    appliedmonths           integer encode az64,
    firstinstalment         numeric(38, 10) encode az64,
    remaininginstalment     numeric(38, 10) encode az64,
    amountperterm           numeric(38, 10) encode az64,
    issubsidized            varchar(10),
    isobarenewal            integer encode az64,
    orderid                 varchar(50),
    tax_amt_breakup         varchar(200),
    tax_amt_breakup_desc    varchar(500),
    parentcustomer          varchar(20),
    medium                  varchar(50),
    source_name             varchar(50),
    campaign                varchar(50),
    sim_flag                smallint encode az64,
    reason                  varchar(500),
    blockedby               varchar(50),
    blockeddate             timestamp encode az64,
    fee_breakupdesc         varchar(500),
    fee_breakupamt          varchar(500),
    totalfeeamount          numeric(38, 2) encode az64,
    feerefundflag           varchar(50),
    taxrefundflag           varchar(50),
    payment_mode            varchar(100),
    pricesplitup            varchar(1000),
    calcon                  varchar(50),
    nus_id                  varchar(15),
    nus_expiredate          timestamp encode az64,
    nus_flag                smallint encode az64,
    nus_applied             smallint encode az64,
    installment_info        varchar(500),
    frequency               integer encode az64,
    gateway                 varchar(150),
    merchant_id             varchar(150),
    pin_expire_date         timestamp encode az64,
    reactivate_count        integer encode az64,
    batch_id                integer encode az64,
    created_date            timestamp encode az64,
    rec_checksum            varchar(32)
);

create table lm_mst_free_sim_customer_activation_duplcdr
(
    id                      integer encode az64,
    transactionid           varchar(50),
    redorderid              varchar(50),
    pinnumber               varchar(20),
    status                  varchar(3),
    postcode                varchar(100),
    typeofsim               varchar(20),
    topupamount             numeric(38, 10) encode az64,
    cardid                  varchar(10),
    nabundleamount          numeric(38, 10) encode az64,
    inabundleamount         numeric(38, 10) encode az64,
    nabundlecode            integer encode az64,
    inabundlecode           integer encode az64,
    imsi                    varchar(20),
    msisdn_real             varchar(20),
    msisdn_dummy            varchar(20),
    activateddate           timestamp encode az64,
    activatedchannel        varchar(20),
    errordesc               varchar(200),
    requestdate             timestamp encode az64,
    processeddate           timestamp encode az64,
    modeofpayment           varchar(20),
    autorenewal             varchar(5),
    planid                  integer encode az64,
    promocode               varchar(20),
    promoofferid            integer encode az64,
    promotype               varchar(2),
    promodiscounttype       varchar(2),
    promodiscountvalue      numeric(38, 10) encode az64,
    shippingamount          numeric(38, 10) encode az64,
    shippingpromocode       varchar(20),
    shippingdiscounttype    varchar(2),
    shippingdiscountvalue   numeric(38, 10) encode az64,
    shippromodiscountstatus varchar(5),
    totaltax                numeric(38, 10) encode az64,
    tax                     numeric(38, 10) encode az64,
    obacreditdue            numeric(38, 10) encode az64,
    subtransactionid        varchar(50),
    vattransid              varchar(16),
    vatamount               numeric(38, 10) encode az64,
    vatperc                 numeric(5, 2) encode az64,
    bundlemonths            integer encode az64,
    appliedmonths           integer encode az64,
    firstinstalment         numeric(38, 10) encode az64,
    remaininginstalment     numeric(38, 10) encode az64,
    amountperterm           numeric(38, 10) encode az64,
    issubsidized            varchar(10),
    isobarenewal            integer encode az64,
    orderid                 varchar(50),
    tax_amt_breakup         varchar(200),
    tax_amt_breakup_desc    varchar(500),
    parentcustomer          varchar(20),
    medium                  varchar(50),
    source_name             varchar(50),
    campaign                varchar(50),
    sim_flag                smallint encode az64,
    reason                  varchar(500),
    blockedby               varchar(50),
    blockeddate             timestamp encode az64,
    fee_breakupdesc         varchar(500),
    fee_breakupamt          varchar(500),
    totalfeeamount          numeric(38, 2) encode az64,
    feerefundflag           varchar(50),
    taxrefundflag           varchar(50),
    payment_mode            varchar(100),
    pricesplitup            varchar(1000),
    calcon                  varchar(50),
    nus_id                  varchar(15),
    nus_expiredate          timestamp encode az64,
    nus_flag                smallint encode az64,
    nus_applied             smallint encode az64,
    installment_info        varchar(500),
    frequency               integer encode az64,
    gateway                 varchar(150),
    merchant_id             varchar(150),
    pin_expire_date         timestamp encode az64,
    reactivate_count        integer encode az64,
    batch_id                integer encode az64,
    created_date            timestamp encode az64,
    rec_checksum            varchar(32)
);

create table lm_recycle_master
(
    id                integer encode az64,
    month             varchar(50),
    network_id        smallint encode az64,
    msisdn            bigint encode az64,
    msisdn_swap       varchar(50),
    iccid_prefix      bigint encode az64,
    iccid             bigint encode az64,
    imsi              bigint encode az64,
    imsi2             bigint encode az64,
    last_usage_date   timestamp encode az64,
    balance           numeric(22, 6) encode az64,
    production_status varchar(100),
    activation_date   timestamp encode az64,
    last_call_date    varchar(50),
    last_msg_date     varchar(50),
    last_top_date     varchar(50),
    hlrid             varchar(50),
    deactivation_date varchar(50),
    initialbal        varchar(50),
    acc_id            varchar(50),
    resellerid        varchar(50),
    offmgrid          varchar(50),
    accmgrid          varchar(50),
    hotspotid         varchar(50),
    retailerid        varchar(50),
    distributorid     varchar(50),
    valid_month       integer encode az64,
    valid_date        date encode az64,
    batch_id          integer encode az64,
    created_date      timestamp encode az64,
    rec_checksum      varchar(32)
);

create table lm_recycle_master_duplcdr
(
    id                integer encode az64,
    month             varchar(50),
    network_id        smallint encode az64,
    msisdn            bigint encode az64,
    msisdn_swap       varchar(50),
    iccid_prefix      bigint encode az64,
    iccid             bigint encode az64,
    imsi              bigint encode az64,
    imsi2             bigint encode az64,
    last_usage_date   timestamp encode az64,
    balance           numeric(22, 6) encode az64,
    production_status varchar(100),
    activation_date   timestamp encode az64,
    last_call_date    varchar(50),
    last_msg_date     varchar(50),
    last_top_date     varchar(50),
    hlrid             varchar(50),
    deactivation_date varchar(50),
    initialbal        varchar(50),
    acc_id            varchar(50),
    resellerid        varchar(50),
    offmgrid          varchar(50),
    accmgrid          varchar(50),
    hotspotid         varchar(50),
    retailerid        varchar(50),
    distributorid     varchar(50),
    valid_month       integer encode az64,
    valid_date        date encode az64,
    batch_id          integer encode az64,
    created_date      timestamp encode az64,
    rec_checksum      varchar(32)
);

create table lm_trn_activation
(
    facevalue         numeric(22, 6) encode az64,
    sellprice         varchar(50),
    vat               varchar(50),
    discount          numeric(22, 6) encode az64,
    netprice          varchar(50),
    validity          varchar(50),
    invoicenumber     varchar(50),
    submitby          varchar(50),
    submitdate        timestamp encode az64,
    crcheckby         varchar(50),
    crcheckdate       timestamp encode az64,
    preactby          varchar(50),
    preactdate        timestamp encode az64,
    authby            varchar(50),
    authdate          timestamp encode az64,
    blockby           varchar(50),
    blockdate         varchar(50),
    blockreason       varchar(50),
    huaweisubmitstate varchar(50),
    huaweierrcode     varchar(50),
    recordlock        varchar(50),
    processid         varchar(50),
    freemin           numeric(22, 6) encode az64,
    ponumber          varchar(50),
    bundlecode        integer encode az64,
    planid            varchar(50),
    description       varchar(50),
    bundlecost        numeric(22, 6) encode az64,
    bundletext        varchar(50),
    total_fee_amt     numeric(22, 6) encode az64,
    fee_breakup       varchar(50),
    isfamily          varchar(50),
    sim_expirydate    date encode az64,
    authdate_month    integer encode az64,
    batch_id          integer encode az64,
    created_date      timestamp encode az64,
    rec_checksum      varchar(32)
);

create table lm_trn_activation_duplcdr
(
    facevalue         numeric(22, 6) encode az64,
    sellprice         varchar(50),
    vat               varchar(50),
    discount          numeric(22, 6) encode az64,
    netprice          varchar(50),
    validity          varchar(50),
    invoicenumber     varchar(50),
    submitby          varchar(50),
    submitdate        timestamp encode az64,
    crcheckby         varchar(50),
    crcheckdate       timestamp encode az64,
    preactby          varchar(50),
    preactdate        timestamp encode az64,
    authby            varchar(50),
    authdate          timestamp encode az64,
    blockby           varchar(50),
    blockdate         varchar(50),
    blockreason       varchar(50),
    huaweisubmitstate varchar(50),
    huaweierrcode     varchar(50),
    recordlock        varchar(50),
    processid         varchar(50),
    freemin           numeric(22, 6) encode az64,
    ponumber          varchar(50),
    bundlecode        integer encode az64,
    planid            varchar(50),
    description       varchar(50),
    bundlecost        numeric(22, 6) encode az64,
    bundletext        varchar(50),
    total_fee_amt     numeric(22, 6) encode az64,
    fee_breakup       varchar(50),
    isfamily          varchar(50),
    sim_expirydate    date encode az64,
    authdate_month    integer encode az64,
    batch_id          integer encode az64,
    created_date      timestamp encode az64,
    rec_checksum      varchar(32)
);

create table lm_trn_activation_bundle_cost_duplcdr
(
    activateid         integer encode az64,
    bundlecost         numeric(22, 6) encode az64,
    createddate        timestamp encode az64,
    bundlecode         integer encode az64,
    planid             varchar(50),
    noofmonths         varchar(50),
    priority           varchar(50),
    isprocess          varchar(50),
    bundletext         varchar(100),
    total_fee_amt      numeric(22, 6) encode az64,
    fee_breakup        varchar(100),
    family_bundle_type varchar(50),
    batch_id           integer encode az64,
    created_date       timestamp encode az64,
    rec_checksum       varchar(32)
);

create table lm_trn_activation_bundle_cost
(
    activateid         integer encode az64,
    bundlecost         numeric(22, 6) encode az64,
    createddate        timestamp encode az64,
    bundlecode         integer encode az64,
    planid             varchar(50),
    noofmonths         varchar(50),
    priority           varchar(50),
    isprocess          varchar(50),
    bundletext         varchar(100),
    total_fee_amt      numeric(22, 6) encode az64,
    fee_breakup        varchar(100),
    family_bundle_type varchar(50),
    batch_id           integer encode az64,
    created_date       timestamp encode az64,
    rec_checksum       varchar(32)
);

create table lm_trn_vouchers
(
    voucherid       bigint encode az64,
    card_id         varchar(4),
    source_batch_id varchar(8),
    serial_id       varchar(4),
    cardnumber      varchar(50),
    card_pin        varchar(50),
    face_value      numeric(38, 10) encode az64,
    card_currency   varchar(50),
    create_date     timestamp encode az64,
    expired_date    timestamp encode az64,
    useddate        timestamp encode az64,
    reseller_id     varchar(25),
    sitecode        varchar(3),
    printed_price   numeric(38, 10) encode az64,
    validity        varchar(4),
    voucherstatusid integer encode az64,
    msisdn          varchar(20),
    plan_id         integer encode az64,
    is_sbtprintable smallint encode az64,
    is_bundle       integer encode az64,
    is_assigned     smallint encode az64,
    bundle_code     integer encode az64,
    vouchertype     integer encode az64,
    transaction_id  varchar(50),
    serviceid       integer encode az64,
    bundlecost      numeric(38, 10) encode az64,
    useddate_month  integer encode az64,
    batch_id        integer encode az64,
    created_date    timestamp encode az64,
    rec_checksum    varchar(32)
);

create table lm_trn_vouchers_duplcdr
(
    voucherid       bigint encode az64,
    card_id         varchar(4),
    source_batch_id varchar(8),
    serial_id       varchar(4),
    cardnumber      varchar(50),
    card_pin        varchar(50),
    face_value      numeric(38, 10) encode az64,
    card_currency   varchar(50),
    create_date     timestamp encode az64,
    expired_date    timestamp encode az64,
    useddate        timestamp encode az64,
    reseller_id     varchar(25),
    sitecode        varchar(3),
    printed_price   numeric(38, 10) encode az64,
    validity        varchar(4),
    voucherstatusid integer encode az64,
    msisdn          varchar(20),
    plan_id         integer encode az64,
    is_sbtprintable smallint encode az64,
    is_bundle       integer encode az64,
    is_assigned     smallint encode az64,
    bundle_code     integer encode az64,
    vouchertype     integer encode az64,
    transaction_id  varchar(50),
    serviceid       integer encode az64,
    bundlecost      numeric(38, 10) encode az64,
    useddate_month  integer encode az64,
    batch_id        integer encode az64,
    created_date    timestamp encode az64,
    rec_checksum    varchar(32)
);

create table lm_srt_trn_vouchers_log
(
    voucherid       bigint encode az64,
    card_id         varchar(4),
    source_batch_id varchar(8),
    serial_id       varchar(4),
    cardnumber      varchar(50),
    card_pin        varchar(50),
    face_value      numeric(38, 10) encode az64,
    card_currency   varchar(50),
    create_date     timestamp encode az64,
    expired_date    timestamp encode az64,
    useddate        timestamp encode az64,
    reseller_id     varchar(25),
    sitecode        varchar(3),
    printed_price   numeric(38, 10) encode az64,
    validity        varchar(4),
    voucherstatusid integer encode az64,
    msisdn          varchar(20),
    plan_id         integer encode az64,
    is_sbtprintable smallint encode az64,
    is_bundle       integer encode az64,
    is_assigned     smallint encode az64,
    bundle_code     integer encode az64,
    vouchertype     integer encode az64,
    transaction_id  varchar(50),
    serviceid       integer encode az64,
    bundlecost      numeric(38, 10) encode az64,
    recycledby      varchar(200),
    recycledon      timestamp encode az64,
    useddate_month  integer encode az64,
    batch_id        integer encode az64,
    created_date    timestamp encode az64,
    rec_checksum    varchar(32)
);

create table lm_srt_trn_vouchers_log_duplcdr
(
    voucherid       bigint encode az64,
    card_id         varchar(4),
    source_batch_id varchar(8),
    serial_id       varchar(4),
    cardnumber      varchar(50),
    card_pin        varchar(50),
    face_value      numeric(38, 10) encode az64,
    card_currency   varchar(50),
    create_date     timestamp encode az64,
    expired_date    timestamp encode az64,
    useddate        timestamp encode az64,
    reseller_id     varchar(25),
    sitecode        varchar(3),
    printed_price   numeric(38, 10) encode az64,
    validity        varchar(4),
    voucherstatusid integer encode az64,
    msisdn          varchar(20),
    plan_id         integer encode az64,
    is_sbtprintable smallint encode az64,
    is_bundle       integer encode az64,
    is_assigned     smallint encode az64,
    bundle_code     integer encode az64,
    vouchertype     integer encode az64,
    transaction_id  varchar(50),
    serviceid       integer encode az64,
    bundlecost      numeric(38, 10) encode az64,
    recycledby      varchar(200),
    recycledon      timestamp encode az64,
    useddate_month  integer encode az64,
    batch_id        integer encode az64,
    created_date    timestamp encode az64,
    rec_checksum    varchar(32)
);

create table lm_srt_trnvouchers_used_log
(
    voucherid       bigint encode az64,
    card_id         varchar(4),
    source_batch_id varchar(8),
    serial_id       varchar(4),
    cardnumber      varchar(50),
    card_pin        varchar(50),
    face_value      numeric(38, 10) encode az64,
    card_currency   varchar(50),
    create_date     timestamp encode az64,
    expired_date    timestamp encode az64,
    reseller_id     varchar(25),
    sitecode        varchar(3),
    printed_price   numeric(38, 10) encode az64,
    validity        varchar(4),
    voucherstatusid integer encode az64,
    useddate        timestamp encode az64,
    msisdn          varchar(20),
    plan_id         integer encode az64,
    is_sbtprintable smallint encode az64,
    is_bundle       integer encode az64,
    is_assigned     smallint encode az64,
    bundle_code     integer encode az64,
    transaction_id  varchar(50),
    serviceid       integer encode az64,
    vouchertype     integer encode az64,
    bundlecost      numeric(38, 10) encode az64,
    recycledby      varchar(200),
    recycledon      timestamp encode az64,
    useddate_month  integer encode az64,
    batch_id        integer encode az64,
    created_date    timestamp encode az64,
    rec_checksum    varchar(32)
);

create table lm_srt_trnvouchers_used_log_duplcdr
(
    voucherid       bigint encode az64,
    card_id         varchar(4),
    source_batch_id varchar(8),
    serial_id       varchar(4),
    cardnumber      varchar(50),
    card_pin        varchar(50),
    face_value      numeric(38, 10) encode az64,
    card_currency   varchar(50),
    create_date     timestamp encode az64,
    expired_date    timestamp encode az64,
    reseller_id     varchar(25),
    sitecode        varchar(3),
    printed_price   numeric(38, 10) encode az64,
    validity        varchar(4),
    voucherstatusid integer encode az64,
    useddate        timestamp encode az64,
    msisdn          varchar(20),
    plan_id         integer encode az64,
    is_sbtprintable smallint encode az64,
    is_bundle       integer encode az64,
    is_assigned     smallint encode az64,
    bundle_code     integer encode az64,
    transaction_id  varchar(50),
    serviceid       integer encode az64,
    vouchertype     integer encode az64,
    bundlecost      numeric(38, 10) encode az64,
    recycledby      varchar(200),
    recycledon      timestamp encode az64,
    useddate_month  integer encode az64,
    batch_id        integer encode az64,
    created_date    timestamp encode az64,
    rec_checksum    varchar(32)
);

create table lm_trn_vouchers_used
(
    voucherid       bigint encode az64,
    card_id         varchar(4) encode zstd,
    source_batch_id varchar(8) encode zstd,
    serial_id       varchar(4) encode zstd,
    cardnumber      varchar(50) encode zstd,
    card_pin        varchar(50) encode zstd,
    face_value      numeric(38, 10) encode az64,
    card_currency   varchar(50) encode zstd,
    create_date     timestamp encode az64,
    expired_date    timestamp encode az64,
    reseller_id     varchar(50) encode zstd,
    sitecode        varchar(3) encode zstd,
    printed_price   numeric(38, 10) encode az64,
    validity        varchar(4) encode zstd,
    voucherstatusid integer encode az64,
    useddate        timestamp encode az64,
    msisdn          varchar(20) encode zstd,
    plan_id         integer encode az64,
    is_sbtprintable smallint encode az64,
    is_bundle       integer encode az64,
    is_assigned     smallint encode az64,
    bundle_code     integer encode az64,
    transaction_id  varchar(50) encode zstd,
    serviceid       integer encode az64,
    vouchertype     integer encode az64,
    bundlecost      numeric(38, 10) encode az64,
    useddate_month  integer encode az64,
    batch_id        integer encode az64,
    created_date    timestamp encode az64,
    rec_checksum    varchar(32)
);

create table lm_trn_vouchers_used_duplcdr
(
    voucherid       bigint encode az64,
    card_id         varchar(4),
    source_batch_id varchar(8),
    serial_id       varchar(4),
    cardnumber      varchar(50),
    card_pin        varchar(50),
    face_value      numeric(38, 10) encode az64,
    card_currency   varchar(50),
    create_date     timestamp encode az64,
    expired_date    timestamp encode az64,
    reseller_id     varchar(50),
    sitecode        varchar(3),
    printed_price   numeric(38, 10) encode az64,
    validity        varchar(4),
    voucherstatusid integer encode az64,
    useddate        timestamp encode az64,
    msisdn          varchar(20),
    plan_id         integer encode az64,
    is_sbtprintable smallint encode az64,
    is_bundle       integer encode az64,
    is_assigned     smallint encode az64,
    bundle_code     integer encode az64,
    transaction_id  varchar(50),
    serviceid       integer encode az64,
    vouchertype     integer encode az64,
    bundlecost      numeric(38, 10) encode az64,
    useddate_month  integer encode az64,
    batch_id        integer encode az64,
    created_date    timestamp encode az64,
    rec_checksum    varchar(32)
);

