create table temp_fact_ggsn_latecdr
(
    recordtype                       varchar(100),
    servedimsi                       bigint encode az64,
    p_gwaddress                      varchar(100),
    chargingid                       varchar(100),
    servingnodeaddress               varchar(100),
    accesspointnameni                varchar(100),
    pdppdntype                       varchar(100),
    servedpdppdnaddress              varchar(100),
    dynamicaddressflag               varchar(100),
    recordopeningtime                timestamp encode az64,
    duration                         integer encode az64,
    causeforrecclosing               varchar(100),
    diagnostics                      varchar(100),
    recordsequencenumber             varchar(100),
    nodeid                           varchar(100),
    localsequencenumber              varchar(100),
    apnselectionmode                 varchar(100),
    servedmsisdn                     bigint encode az64,
    chargingcharacteristics          varchar(100),
    chchselectionmode                varchar(100),
    imssignalingcontext              varchar(100),
    externalchargingid               varchar(100),
    servingnodeplmnidentifier        varchar(100),
    psfreeformatdata                 varchar(100),
    psffdappendindicator             varchar(100),
    servedimeisv                     varchar(100),
    rattype                          varchar(100),
    mstimezone                       varchar(100),
    userlocationinformation          varchar(100),
    camelcharginginformation         varchar(100),
    servingnodetype                  varchar(100),
    servedmnnai                      varchar(100),
    p_gwplmnidentifier               varchar(100),
    starttime                        timestamp encode az64,
    stoptime                         timestamp encode az64,
    served3gpp2meid                  varchar(100),
    pdnconnectionchargingid          varchar(100),
    threegpp2userlocationinformation varchar(100),
    servedpdppdnaddressext           varchar(100),
    dynamicaddressflagext            varchar(100),
    dummy                            varchar(100),
    total_uplink                     bigint encode az64,
    total_downlink                   bigint encode az64,
    change_date                      varchar(100),
    url                              varchar(100),
    ratinggroup                      varchar(100),
    failurehand                      varchar(100),
    rulebasename                     varchar(100),
    timeoffirstusage                 varchar(100),
    timeoflastusage                  varchar(100),
    timeusage                        varchar(100),
    timeofreport                     varchar(100),
    fct_free_text_1                  varchar(50) encode zstd,
    fct_free_text_2                  varchar(50) encode zstd,
    fct_free_text_3                  varchar(50) encode zstd,
    fct_free_text_4                  varchar(50) encode zstd,
    fct_free_text_5                  varchar(50) encode zstd,
    fct_free_text_6                  varchar(50) encode zstd,
    fct_free_text_7                  varchar(50) encode zstd,
    fct_free_text_8                  varchar(50) encode zstd,
    fct_free_text_9                  varchar(50) encode zstd,
    fct_free_text_10                 varchar(50) encode zstd,
    fct_free_text_11                 varchar(50) encode zstd,
    fct_free_text_12                 varchar(50) encode zstd,
    fct_free_text_13                 varchar(50) encode zstd,
    fct_free_text_14                 varchar(50) encode zstd,
    fct_free_text_15                 varchar(50) encode zstd,
    fct_free_text_16                 varchar(50) encode zstd,
    fct_free_text_17                 varchar(50) encode zstd,
    fct_free_text_18                 varchar(50) encode zstd,
    fct_free_text_19                 varchar(50) encode zstd,
    fct_free_text_20                 varchar(50) encode zstd,
    recordopening_date               date encode az64,
    recordopening_date_num           integer encode az64,
    recordopening_month              integer encode az64,
    total_uplink_mb                  numeric(22, 6) encode az64,
    total_downlink_mb                numeric(22, 6) encode az64,
    accesspointnameni_code           varchar(100),
    recordopening_time_gmt           timestamp encode az64,
    recordopening_dt_month_gmt       integer encode az64,
    recordopening_dt_num_gmt         integer encode az64,
    recordopening_dt_hour_gmt        integer encode az64,
    filename                         varchar(100) not null,
    batch_id                         integer encode az64,
    created_date                     timestamp      not null encode az64,
    rec_checksum                     varchar(100) not null
);
