create table fact_ggsn_duplcdr
(
    sk_ggsn                          bigint default default_identity(159739, 0, ('1,1'::character varying)::text) encode zstd,
    recordtype                       varchar(10),
    servedimsi                       bigint encode az64 distkey,
    p_gwaddress                      varchar(100),
    chargingid                       varchar(20),
    servingnodeaddress               varchar(200),
    accesspointnameni                varchar(100),
    pdppdntype                       varchar(10),
    servedpdppdnaddress              varchar(50),
    dynamicaddressflag               varchar(10),
    recordopeningtime                varchar(50),
    duration                         integer encode az64,
    causeforrecclosing               varchar(150),
    diagnostics                      varchar(10),
    recordsequencenumber             varchar(10),
    nodeid                           varchar(20),
    localsequencenumber              varchar(20),
    apnselectionmode                 varchar(100),
    servedmsisdn                     bigint encode az64,
    chargingcharacteristics          varchar(50),
    chchselectionmode                varchar(50),
    imssignalingcontext              varchar(50),
    externalchargingid               varchar(50),
    servingnodeplmnidentifier        varchar(50),
    psfreeformatdata                 varchar(50),
    psffdappendindicator             varchar(50),
    servedimeisv                     varchar(50),
    rattype                          varchar(10),
    mstimezone                       varchar(50),
    userlocationinformation          varchar(50),
    camelcharginginformation         varchar(50),
    servingnodetype                  varchar(50),
    servedmnnai                      varchar(50),
    p_gwplmnidentifier               varchar(50),
    starttime                        varchar(50),
    stoptime                         varchar(50),
    served3gpp2meid                  varchar(50),
    pdnconnectionchargingid          varchar(50),
    threegpp2userlocationinformation varchar(50),
    servedpdppdnaddressext           varchar(100),
    dynamicaddressflagext            varchar(50),
    dummy                            varchar(200),
    total_uplink                     bigint encode az64,
    total_downlink                   bigint encode az64,
    change_date                      varchar(100),
    url                              varchar(500),
    ratinggroup                      varchar(500),
    failurehand                      varchar(500),
    conditionchange                  varchar(500),
    rulebasename                     varchar(500),
    timeoffirstusage                 varchar(500),
    timeoflastusage                  varchar(500),
    timeusage                        varchar(500),
    timeofreport                     varchar(500),
    fct_free_text_1                  varchar(50) encode zstd,
    fct_free_text_2                  varchar(50) encode zstd,
    fct_free_text_3                  varchar(50) encode zstd,
    fct_free_text_4                  varchar(50) encode zstd,
    fct_free_text_5                  varchar(50) encode zstd,
    fct_free_text_6                  varchar(50) encode zstd,
    fct_free_text_7                  varchar(50) encode zstd,
    fct_free_text_8                  varchar(50) encode zstd,
    fct_free_text_9                  varchar(50) encode zstd,
    fct_free_text_10                 varchar(50) encode zstd,
    fct_free_text_11                 varchar(50) encode zstd,
    fct_free_text_12                 varchar(50) encode zstd,
    fct_free_text_13                 varchar(50) encode zstd,
    fct_free_text_14                 varchar(50) encode zstd,
    fct_free_text_15                 varchar(50) encode zstd,
    fct_free_text_16                 varchar(50) encode zstd,
    fct_free_text_17                 varchar(50) encode zstd,
    fct_free_text_18                 varchar(50) encode zstd,
    fct_free_text_19                 varchar(50) encode zstd,
    fct_free_text_20                 varchar(50) encode zstd,
    recordopening_date               date encode az64,
    recordopening_date_num           integer,
    recordopening_month              integer,
    total_uplink_mb                  numeric(20, 4) encode az64,
    total_downlink_mb                numeric(20, 4) encode az64,
    accesspointnameni_code           varchar(10),
    recordopening_time_gmt           timestamp encode az64,
    recordopening_dt_month_gmt       integer encode az64,
    recordopening_dt_num_gmt         integer encode az64,
    recordopening_dt_hour_gmt        integer encode az64,
    filename                         varchar(50),
    batch_id                         integer encode az64,
    created_date                     timestamp encode az64,
    rec_checksum                     varchar(32)
)
    diststyle key
    sortkey (recordopening_month, recordopening_date_num, accesspointnameni);
