create table fact_ggsn
(
    sk_ggsn                          bigint default default_identity(166498, 0, ('1,1'::character varying)::text) encode zstd,
    recordtype                       varchar(10) encode zstd,
    servedimsi                       bigint encode az64 distkey,
    p_gwaddress                      varchar(100) encode zstd,
    chargingid                       varchar(20) encode zstd,
    servingnodeaddress               varchar(200) encode zstd,
    accesspointnameni                varchar(100),
    pdppdntype                       varchar(10) encode zstd,
    servedpdppdnaddress              varchar(50) encode zstd,
    dynamicaddressflag               varchar(10) encode zstd,
    recordopeningtime                timestamp encode az64,
    duration                         integer encode az64,
    causeforrecclosing               varchar(150) encode zstd,
    diagnostics                      varchar(10) encode zstd,
    recordsequencenumber             varchar(10) encode zstd,
    nodeid                           varchar(20) encode zstd,
    localsequencenumber              varchar(20) encode zstd,
    apnselectionmode                 varchar(100) encode zstd,
    servedmsisdn                     bigint encode az64,
    chargingcharacteristics          varchar(50) encode zstd,
    chchselectionmode                varchar(50) encode zstd,
    imssignalingcontext              varchar(50) encode zstd,
    externalchargingid               varchar(50) encode zstd,
    servingnodeplmnidentifier        varchar(50) encode zstd,
    psfreeformatdata                 varchar(50) encode zstd,
    psffdappendindicator             varchar(50) encode zstd,
    servedimeisv                     varchar(50) encode zstd,
    rattype                          varchar(10) encode zstd,
    mstimezone                       varchar(50) encode zstd,
    userlocationinformation          varchar(50) encode zstd,
    camelcharginginformation         varchar(50) encode zstd,
    servingnodetype                  varchar(50) encode zstd,
    servedmnnai                      varchar(50) encode zstd,
    p_gwplmnidentifier               varchar(50) encode zstd,
    starttime                        timestamp encode az64,
    stoptime                         timestamp encode az64,
    served3gpp2meid                  varchar(50),
    pdnconnectionchargingid          varchar(50),
    threegpp2userlocationinformation varchar(50),
    servedpdppdnaddressext           varchar(100),
    dynamicaddressflagext            varchar(50),
    dummy                            varchar(200),
    total_uplink                     bigint encode az64,
    total_downlink                   bigint encode az64,
    change_date                      varchar(100),
    url                              varchar(500),
    ratinggroup                      varchar(500),
    failurehand                      varchar(500),
    conditionchange                  varchar(500),
    rulebasename                     varchar(500),
    timeoffirstusage                 varchar(500),
    timeoflastusage                  varchar(500),
    timeusage                        varchar(500),
    timeofreport                     varchar(500),
    fct_free_text_1                  varchar(50) encode zstd,
    fct_free_text_2                  varchar(50) encode zstd,
    fct_free_text_3                  varchar(50) encode zstd,
    fct_free_text_4                  varchar(50) encode zstd,
    fct_free_text_5                  varchar(50) encode zstd,
    fct_free_text_6                  varchar(50) encode zstd,
    fct_free_text_7                  varchar(50) encode zstd,
    fct_free_text_8                  varchar(50) encode zstd,
    fct_free_text_9                  varchar(50) encode zstd,
    fct_free_text_10                 varchar(50) encode zstd,
    fct_free_text_11                 varchar(50) encode zstd,
    fct_free_text_12                 varchar(50) encode zstd,
    fct_free_text_13                 varchar(50) encode zstd,
    fct_free_text_14                 varchar(50) encode zstd,
    fct_free_text_15                 varchar(50) encode zstd,
    fct_free_text_16                 varchar(50) encode zstd,
    fct_free_text_17                 varchar(50) encode zstd,
    fct_free_text_18                 varchar(50) encode zstd,
    fct_free_text_19                 varchar(50) encode zstd,
    fct_free_text_20                 varchar(50) encode zstd,
    recordopening_date               date encode az64,
    recordopening_date_num           integer,
    recordopening_month              integer,
    total_uplink_mb                  numeric(20, 4) encode az64,
    total_downlink_mb                numeric(20, 4) encode az64,
    accesspointnameni_code           varchar(10),
    recordopening_time_gmt           timestamp encode az64,
    recordopening_dt_month_gmt       integer encode az64,
    recordopening_dt_num_gmt         integer encode az64,
    recordopening_dt_hour_gmt        integer encode az64,
    filename                         varchar(50),
    batch_id                         integer encode az64,
    created_date                     timestamp encode az64,
    rec_checksum                     varchar(32)
)
    diststyle key
    sortkey (recordopening_month, recordopening_date_num, accesspointnameni);

