create table fact_rrbs_voice
(
    sk_rrbs_voice                     bigint default default_identity(167829, 0, ('1,1'::character varying)::text) encode zstd,
    voice_call_cdr                    integer encode az64,
    network_id                        integer,
    call_type                         integer,
    call_feature                      integer encode az64,
    tariffplan_id                     integer encode az64,
    service_id                        integer encode az64,
    cli                               bigint encode az64,
    dialed_number                     varchar(50) encode zstd,
    charged_party_number              bigint encode az64,
    imsi                              bigint encode az64 distkey,
    serving_node                      bigint encode az64,
    mcc                               integer encode az64,
    mnc                               integer encode az64,
    lac                               integer encode az64,
    calling_cell_id                   integer encode az64,
    cellzone_code                     varchar(30) encode zstd,
    cellzone_name                     varchar(30) encode zstd,
    original_dialed_number            bigint encode az64,
    destination_zone                  integer encode az64,
    destination_area_code             bigint encode az64,
    destinationzone_name              varchar(30) encode bytedict,
    roaming_area_code                 varchar(20) encode zstd,
    roaming_zone_name                 varchar(30) encode zstd,
    roam_flag                         smallint,
    roam_area_number                  integer encode az64,
    granted_time                      integer encode az64,
    granted_money                     numeric(22, 6) encode zstd,
    call_duration                     integer encode az64,
    chargeable_used_time              integer encode az64,
    call_date                         timestamp encode zstd,
    call_termination_time             timestamp encode zstd,
    initial_account_balance           numeric(22, 6) encode zstd,
    talk_charge                       numeric(22, 6) encode zstd,
    balance                           numeric(22, 6) encode zstd,
    free_minutes_account_balance      numeric(22, 6) encode zstd,
    account_id                        integer encode az64,
    dept_id                           integer encode az64,
    free_zone_id                      integer encode az64,
    trace_id                          varchar(50) encode zstd,
    last_topup_type                   smallint encode az64,
    bundle_code                       varchar(10) encode zstd,
    free_zone_expiry_date             varchar(50) encode zstd,
    ringing_duration                  varchar(3) encode zstd,
    ring_indicator                    varchar(1) encode zstd,
    national_bundle_code              varchar(10) encode zstd,
    national_used_minutes             varchar(10) encode zstd,
    national_charge                   varchar(10) encode zstd,
    pool_number                       varchar(20) encode zstd,
    bundle_used_seconds               varchar(10) encode zstd,
    bundle_call_charge                varchar(10) encode zstd,
    bundle_balance                    varchar(10) encode zstd,
    bundle_plan_id                    varchar(5) encode zstd,
    final_unit_indicator              varchar(1) encode zstd,
    ncall_free_units                  varchar(10) encode zstd,
    local_roam_country_code           varchar(4) encode zstd,
    cdr_time_stamp                    timestamp encode zstd,
    bucket_type                       integer encode az64,
    conversion_unit                   varchar(50) encode zstd,
    intial_free_units                 integer encode az64,
    subscriber_type                   integer encode az64,
    call_forwarding_indicator         integer encode az64,
    cdr_sequence_number               integer encode az64,
    sub_acct_id                       integer encode az64,
    announcement_time                 integer encode az64,
    family_id                         integer encode az64,
    idp_time                          varchar(100) encode zstd,
    cs_free_mins                      varchar(50) encode zstd,
    free_units_detected               integer encode az64,
    multileg_charging_flag            integer encode az64,
    extension_record                  integer encode az64,
    connect_number                    varchar(50) encode zstd,
    dialed_number1                    varchar(50) encode zstd,
    service_description               varchar(100) encode zstd,
    alternate_plan_id                 varchar(50) encode zstd,
    serving_node_name                 varchar(50) encode zstd,
    fixed_charge                      integer encode az64,
    fixed_charge_resource_impact      varchar(50) encode zstd,
    bundle_version_name               varchar(50) encode zstd,
    flh_reward_slab_id                integer encode az64,
    bundle_version_id                 integer encode az64,
    rate_id                           varchar(50) encode zstd,
    pricing_plan_id                   varchar(50) encode zstd,
    pocket_id                         varchar(50) encode zstd,
    consumed_promo_amount             varchar(50) encode zstd,
    pervious_call_trace_id            varchar(50) encode zstd,
    termination_cause                 integer encode az64,
    non_chargeable_unit               integer encode az64,
    call_forward_msisdn               varchar(50) encode zstd,
    service_type                      varchar(50) encode zstd,
    used_time_in_previous_grant       integer encode az64,
    rlh_charging_indicator            integer encode az64,
    surcharge_consumed                integer encode az64,
    excess_used_units_received        integer encode az64,
    failcause                         integer encode az64,
    roaming_partner_id                integer encode az64,
    bundle_units_used_in_overage_plan varchar(50) encode zstd,
    fct_free_text_1                   varchar(50) encode zstd,
    fct_free_text_2                   varchar(50) encode zstd,
    fct_free_text_3                   varchar(50) encode zstd,
    fct_free_text_4                   varchar(50) encode zstd,
    fct_free_text_5                   varchar(50) encode zstd,
    fct_free_text_6                   varchar(50) encode zstd,
    fct_free_text_7                   varchar(50) encode zstd,
    fct_free_text_8                   varchar(50) encode zstd,
    fct_free_text_9                   varchar(50) encode zstd,
    fct_free_text_10                  varchar(50) encode zstd,
    fct_free_text_11                  varchar(50) encode zstd,
    fct_free_text_12                  varchar(50) encode zstd,
    fct_free_text_13                  varchar(50) encode zstd,
    fct_free_text_14                  varchar(50) encode zstd,
    fct_free_text_15                  varchar(50) encode zstd,
    fct_free_text_16                  varchar(50) encode zstd,
    fct_free_text_17                  varchar(50) encode zstd,
    fct_free_text_18                  varchar(50) encode zstd,
    fct_free_text_19                  varchar(50) encode zstd,
    fct_free_text_20                  varchar(50) encode zstd,
    call_date_month                   integer,
    call_date_dt                      date encode az64,
    call_date_num                     integer encode az64,
    call_date_hour                    integer encode az64,
    call_date_month_gmt               integer encode az64,
    call_date_time_gmt                timestamp encode zstd,
    call_date_num_gmt                 integer encode az64,
    call_date_hour_gmt                integer encode az64,
    call_duration_min                 integer encode az64,
    chargeable_used_time_min          integer encode az64,
    roaming_partner_name              varchar(50) encode zstd,
    filename                          varchar(100) not null encode zstd,
    batch_id                          integer      not null encode zstd,
    created_date                      timestamp    not null encode zstd,
    rec_checksum                      varchar(32) encode zstd
)
    diststyle key
    sortkey (call_date_month, call_date_num, network_id, roam_flag, call_type);