create table fact_rrbs_topup_duplcdr
(
    sk_rrbs_topup                            bigint default default_identity(167847, 0, ('1,1'::character varying)::text) encode zstd,
    operation_code                           smallint,
    network_id                               smallint,
    recharge_type                            smallint encode az64,
    msisdn                                   bigint encode az64,
    imsi                                     bigint encode az64 distkey,
    account_pin_number                       varchar(100) encode zstd,
    voucher_card_id                          integer encode az64,
    special_topup_amount                     numeric(22, 6) encode az64,
    transaction_id                           varchar(100) encode zstd,
    new_balance                              numeric(22, 6) encode az64,
    face_value                               numeric(22, 6) encode az64,
    recharge_amount                          numeric(22, 6) encode az64,
    promo_validity_date                      date encode az64,
    free_minutes                             integer encode az64,
    free_voucher_onnet_minutes               integer encode az64,
    free_minutes_expiry_date                 date encode az64,
    free_sms                                 integer encode az64,
    free_voucher_onnet_sms                   integer encode az64,
    free_sms_expiry_date                     date encode az64,
    free_offnet_minutes                      integer encode az64,
    free_voucher_offnet_minutes              integer encode az64,
    free_offnet_minutes_expiry_date          date encode az64,
    free_offnet_sms                          integer encode az64,
    free_voucher_offnet_sms                  integer encode az64,
    free_offnet_sms_expiry_date              date encode az64,
    free_offnet2_minutes                     integer encode az64,
    free_vouchercard_offnet2_minutes         integer encode az64,
    free_offnet2_minutes_expiry_date         date encode az64,
    free_offnet2_sms                         integer encode az64,
    free_vouchercard_offnet2_sms             integer encode az64,
    free_offnet2_sms_expiry_date             date encode az64,
    free_offnet3_minutes                     integer encode az64,
    free_vouchercard_offnet3_minutes         integer encode az64,
    free_offnet3_minutes_expiry_date         date encode az64,
    free_offnet3_sms                         integer encode az64,
    free_vouchercard_offnet3_sms             integer encode az64,
    free_offnet3_sms_expiry_date             date encode az64,
    free_data                                bigint encode az64,
    free_voucher_data                        bigint encode az64,
    free_data_expirydate                     date encode az64,
    account_validity_date                    date encode az64,
    lyca_voucher_card_id                     varchar(100) encode zstd,
    planid                                   smallint encode az64,
    topup_counter                            smallint encode az64,
    bundle_code                              integer encode az64,
    imei                                     varchar(100) encode zstd,
    voucher_onnet_mins_expdt                 date encode az64,
    voucher_onnet_sms_expdt                  date encode az64,
    voucher_offnet_mins_expdt1               date encode az64,
    voucher_offnet_sms_expdt1                date encode az64,
    voucher_offnet_mins_expdt2               date encode az64,
    voucher_offnet_sms_expdt2                date encode az64,
    voucher_offnet_mins_expdt3               date encode az64,
    voucher_offnet_sms_expdt3                date encode az64,
    voucher_free_dataexp                     date encode az64,
    retailer_msisdn                          varchar(100) encode zstd,
    staff_msisdn                             varchar(100) encode zstd,
    wlm_topupmode                            varchar(100) encode zstd,
    face_value_1                             numeric(22, 6) encode az64,
    promo_validity_days                      integer encode az64,
    oldplanid                                integer encode az64,
    onnet_mt_mins                            integer encode az64,
    voucher_onnet_mt_mins                    integer encode az64,
    onnet_mt_sms                             integer encode az64,
    voucher_onnet_mt_sms                     integer encode az64,
    onnet_mt_exp_dt                          date encode az64,
    voucher_onnet_mt_expiry_date             date encode az64,
    offnet_mt_mins                           integer encode az64,
    voucher_offnet_mt_mins                   integer encode az64,
    offnet_mt_sms                            integer encode az64,
    voucher_offnet_mt_sms                    integer encode az64,
    offnet_mt_exp_dt                         date encode az64,
    voucher_offnet_mt_expiry_date            date encode az64,
    bundle_name                              varchar(100) encode zstd,
    old_account_balance                      numeric(22, 6) encode az64,
    parent_msisdn                            varchar(100) encode zstd,
    rrbs_transaction_id                      varchar(100) encode zstd,
    override_bundle                          integer encode az64,
    vouchernetworkid                         smallint encode az64,
    accid                                    varchar(100) encode zstd,
    deptid                                   varchar(100) encode zstd,
    bundle_catery                            smallint encode az64,
    plan_validity_days                       smallint encode az64,
    account_id                               bigint encode az64,
    sim_number                               bigint encode az64,
    cdr_time_stamp                           timestamp encode zstd,
    reservation                              smallint encode az64,
    discount_promo_code                      varchar(100) encode zstd,
    discount_promo_amount                    numeric(22, 6) encode az64,
    primary_bundle_code                      integer encode az64,
    family_account_id                        varchar(100) encode zstd,
    tax                                      numeric(22, 6) encode az64,
    number_of_installments                   integer encode az64,
    oba_bundle_flag                          smallint encode az64,
    oba_due_amount                           numeric(22, 6) encode az64,
    parent_bundle_code                       integer encode az64,
    bundle_unit_type                         smallint encode az64,
    contract_start_date                      date encode az64,
    contract_end_date                        varchar(100) encode zstd,
    flh_flag                                 smallint encode az64,
    exibs_retailer_transaction_id            varchar(100) encode zstd,
    operation_flag                           smallint encode az64,
    vat_amount                               numeric(22, 6) encode az64,
    special_discount_code                    varchar(100) encode zstd,
    special_discount_amount                  numeric(22, 6) encode az64,
    number_of_installments_discounts_applied varchar(100) encode zstd,
    actual_bundle_cost                       numeric(22, 6) encode az64,
    reservation_reference_transaction_id     varchar(100) encode zstd,
    bundle_expiry_type                       smallint encode az64,
    bundle_balance                           numeric(22, 6) encode az64,
    muv_indicator                            smallint encode az64,
    bundle_group_type                        smallint encode az64,
    sequence_number                          smallint encode az64,
    amount_refunded                          numeric(22, 6) encode az64,
    forcible_cancellation                    varchar(100) encode zstd,
    payment_mode_indicator                   varchar(100) encode zstd,
    amount                                   numeric(22, 6) encode zstd,
    version_id                               smallint encode az64,
    refund_entity_type                       smallint encode az64,
    refund_provided_to                       varchar(100) encode zstd,
    topup_validity_days                      integer encode az64,
    reserve_amount                           numeric(22, 6) encode az64,
    preloaded_bundle_flag                    smallint encode az64,
    staff_indicator                          smallint encode az64,
    child_addition_discount                  numeric(22, 6) encode az64,
    payg_family_indicator                    smallint encode az64,
    payg_prorate_flag                        smallint encode az64,
    payg_child_index                         smallint encode az64,
    parent_msisdn1                           varchar(100) encode zstd,
    payg_member_count                        integer encode az64,
    direct_addon_flag                        smallint encode az64,
    action_flag                              smallint encode az64,
    bundle_topup_timestamp                   varchar(100) encode zstd,
    sim_with_bundle_code                     integer encode az64,
    taxation_details                         varchar(100) encode zstd,
    reserved                                 varchar(100) encode zstd,
    bundle_purchase_date                     timestamp encode zstd,
    bundle_start_date                        timestamp encode zstd,
    renewal_payment_mode                     smallint encode az64,
    iot_bundle_flag                          smallint encode az64,
    veekbundleflag                           smallint encode az64,
    validity_overridden                      smallint encode az64,
    link_type                                smallint encode az64,
    overwrite_bundle_cost_flag               smallint encode az64,
    order_id                                 varchar(100) encode zstd,
    pocket_id                                varchar(100) encode zstd,
    da_track                                 numeric(22, 6) encode az64,
    da_principal_amount                      numeric(22, 6) encode az64,
    is_loan_request                          smallint encode az64,
    migrated_ortel_subscriber_flag           smallint encode az64,
    reward_purchased                         smallint encode az64,
    feebuffer                                varchar(100) encode zstd,
    tax_buffer                               varchar(100) encode zstd,
    paymentgateway                           varchar(100) encode zstd,
    zipcode                                  varchar(100) encode zstd,
    professional_channel_name                varchar(100) encode zstd,
    topupcriteriaflag                        smallint encode az64,
    nus_id                                   varchar(100) encode zstd,
    nus_applied                              smallint encode az64,
    slotid                                   varchar(100) encode zstd,
    reserved_bundle_cost                     varchar(100) encode zstd,
    additional_channel_info                  varchar(500) encode zstd,
    autoflag                                 varchar(500) encode zstd,
    bundleexpirydate                         varchar(500) encode zstd,
    portinofferflag                          varchar(500) encode zstd,
    portinoffervaliditydays                  varchar(500) encode zstd,
    refunded_bundle_allowance_info           varchar(500) encode zstd,
    voucher_bundle_flag                      varchar(500) encode zstd,
    vouche_eligible_flag                     varchar(500) encode zstd,
    bundle_implicit_promo                    varchar(500) encode zstd,
    free_credit                              varchar(500) encode zstd,
    voucher_remaining_amount                 varchar(500) encode zstd,
    promo_code_type                          varchar(500) encode zstd,
    free_credit_offered_month                varchar(500) encode zstd,
    free_credit_type                         varchar(500) encode zstd,
    free_credit_promo_balance_validit_days   varchar(500) encode zstd,
    exempt_min_bal_checkexpiry_date          varchar(500) encode zstd,
    varibalepromoappliedinstallinfo          varchar(500) encode zstd,
    variablepromocardinfo                    varchar(500) encode zstd,
    new_exempt_in_bal_check_expiry_date      varchar(500) encode zstd,
    refund_transaction_id                    varchar(500) encode zstd,
    oba_cancellation_type                    varchar(500) encode zstd,
    oba_credit_consumed                      varchar(500) encode zstd,
    bypass_validation_for_special_bundles    varchar(500) encode zstd,
    campaign_flag                            varchar(500) encode zstd,
    campaign_key                             varchar(500) encode zstd,
    fct_free_text_1                          varchar(100) encode zstd,
    fct_free_text_2                          varchar(100) encode zstd,
    fct_free_text_3                          varchar(100) encode zstd,
    fct_free_text_4                          varchar(100) encode zstd,
    fct_free_text_5                          varchar(100) encode zstd,
    fct_free_text_6                          varchar(100) encode zstd,
    fct_free_text_7                          varchar(100) encode zstd,
    fct_free_text_8                          varchar(100) encode zstd,
    fct_free_text_9                          varchar(100) encode zstd,
    fct_free_text_10                         varchar(100) encode zstd,
    fct_free_text_11                         varchar(100) encode zstd,
    fct_free_text_12                         varchar(100) encode zstd,
    fct_free_text_13                         varchar(100) encode zstd,
    fct_free_text_14                         varchar(100) encode zstd,
    fct_free_text_15                         varchar(100) encode zstd,
    fct_free_text_16                         varchar(100) encode zstd,
    fct_free_text_17                         varchar(100) encode zstd,
    fct_free_text_18                         varchar(100) encode zstd,
    fct_free_text_19                         varchar(100) encode zstd,
    fct_free_text_20                         varchar(100) encode zstd,
    cdr_dt                                   date encode az64,
    cdr_dt_month                             integer,
    cdr_dt_num                               integer encode az64,
    is_bundle_loyalty                        smallint encode az64,
    bundle_usage_1                           numeric(22, 6) encode az64,
    bundle_usage_2                           numeric(22, 6) encode az64,
    cdr_dt_gmt                               timestamp encode zstd,
    cdr_dt_month_gmt                         integer encode az64,
    cdr_dt_num_gmt                           integer encode az64,
    cdr_dt_hour_gmt                          integer encode az64,
    expiry_date_derived                      date encode az64,
    expiry_date_derived_num                  integer encode az64,
    expiry_date_month_derived                integer encode az64,
    roaming_partner_name                     varchar(100) encode zstd,
    filename                                 varchar(100) not null encode zstd,
    batch_id                                 integer     not null encode zstd,
    created_date                             timestamp   not null encode zstd,
    rec_checksum                             varchar(100) encode zstd
)
    diststyle key
    sortkey (cdr_dt_month, cdr_dt_num, network_id, operation_code);