create table fact_rrbs_sms
(
    sk_rrbs_sms                     bigint default default_identity(167820, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_types                       smallint,
    network_id                      smallint,
    call_type                       smallint,
    plan_id                         integer encode az64,
    service_id                      smallint encode az64,
    cli                             bigint encode az64,
    dialed_number                   varchar(50) encode zstd,
    imsi                            bigint encode az64 distkey,
    serving_node                    bigint encode az64,
    destination_area_code           integer encode az64,
    destination_zone_code           integer encode az64,
    destination_zone_name           varchar(50) encode zstd,
    roam_flag                       integer,
    roaming_node                    integer encode az64,
    roaming_area_code               integer encode az64,
    roaming_zone_name               varchar(50) encode zstd,
    sms_feature                     integer encode az64,
    number_of_sms_charged           integer encode az64,
    number_of_free_sms              integer encode az64,
    initial_account_balance         numeric(22, 6) encode az64,
    msg_cost                        numeric(22, 6) encode az64,
    balance                         numeric(22, 6) encode az64,
    free_sms_account_balance        integer encode az64,
    instance_id_session_id          varchar(20) encode zstd,
    account_id                      integer encode az64,
    dept_id                         integer encode az64,
    free_zone_id                    integer encode az64,
    last_topup_type                 smallint encode az64,
    bundle_code                     integer encode az64,
    free_zone_expiry_date           date encode zstd,
    bundle_sms_charge               numeric(22, 6) encode az64,
    bundle_balance                  numeric(22, 6) encode az64,
    bundle_plan_id                  integer encode az64,
    nsms_free_units                 integer encode az64,
    local_roam_country_code         smallint encode az64,
    msg_date                        timestamp encode zstd,
    bucket_type                     smallint encode az64,
    initial_free_units              numeric(22, 6) encode zstd,
    subscriber_type                 smallint encode az64,
    sub_acct_id                     bigint encode az64,
    family_id                       varchar(50) encode zstd,
    concat_message_flag             smallint encode az64,
    concat_message_reference_number integer encode az64,
    concat_message_total_chunks     integer encode az64,
    concat_message_current_chunk    integer encode az64,
    trace_id                        varchar(50) encode zstd,
    idp_time                        varchar(50) encode zstd,
    extension_record                smallint encode az64,
    call_indicator                  smallint encode az64,
    serving_node_name               varchar(50) encode zstd,
    bundle_version_name             varchar(50) encode zstd,
    flh_reward_slab_id              integer encode az64,
    bundle_version_id               smallint encode az64,
    rate_id                         integer encode az64,
    pricing_plan_id                 smallint encode az64,
    pocket_id                       bigint encode az64,
    consumed_promo_amount           numeric(22, 6) encode az64,
    rlh_charging_indicator          smallint encode az64,
    surcharge_consumed              varchar(50) encode zstd,
    roaming_partner_id              varchar(50) encode zstd,
    smsc_gt                         varchar(50) encode zstd,
    fct_free_text_1                 varchar(50) encode zstd,
    fct_free_text_2                 varchar(50) encode zstd,
    fct_free_text_3                 varchar(50) encode zstd,
    fct_free_text_4                 varchar(50) encode zstd,
    fct_free_text_5                 varchar(50) encode zstd,
    fct_free_text_6                 varchar(50) encode zstd,
    fct_free_text_7                 varchar(50) encode zstd,
    fct_free_text_8                 varchar(50) encode zstd,
    fct_free_text_9                 varchar(50) encode zstd,
    fct_free_text_10                varchar(50) encode zstd,
    fct_free_text_11                varchar(50) encode zstd,
    fct_free_text_12                varchar(50) encode zstd,
    fct_free_text_13                varchar(50) encode zstd,
    fct_free_text_14                varchar(50) encode zstd,
    fct_free_text_15                varchar(50) encode zstd,
    fct_free_text_16                varchar(50) encode zstd,
    fct_free_text_17                varchar(50) encode zstd,
    fct_free_text_18                varchar(50) encode zstd,
    fct_free_text_19                varchar(50) encode zstd,
    fct_free_text_20                varchar(50) encode zstd,
    msg_date_month                  integer,
    msg_date_dt                     date encode az64,
    msg_date_num                    integer encode az64,
    msg_date_hour                   integer encode az64,
    msg_date_month_gmt              integer encode az64,
    msg_date_num_gmt                integer encode az64,
    msg_date_hour_gmt               integer encode az64,
    msg_date_time_gmt               timestamp encode zstd,
    free_zone_expiry_date_num       integer encode az64,
    roaming_partner_name            varchar(50) encode zstd,
    filename                        varchar(100) not null encode zstd,
    batch_id                        integer      not null encode zstd,
    created_date                    timestamp    not null encode zstd,
    rec_checksum                    varchar(32) encode zstd
)
    diststyle key
    sortkey (msg_date_month, msg_date_num, network_id, cdr_types, roam_flag, call_type);