create table fact_rrbs_gprs
(
    sk_rrbs_gprs                     bigint default default_identity(167838, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type                         smallint encode az64,
    network_id                       smallint encode az64,
    data_feature                     smallint encode az64,
    tariffplan_id                    smallint encode az64,
    service_id                       smallint encode az64,
    msisdn                           bigint encode az64,
    apn                              varchar(100) encode zstd,
    pdp_address                      varchar(50) encode zstd,
    cellid                           varchar(50) encode zstd,
    imei                             varchar(50) encode zstd,
    imsi                             bigint encode az64 distkey,
    serving_node                     varchar(30) encode zstd,
    ggsn_address                     varchar(50) encode zstd,
    roaming_zone_name                varchar(30) encode zstd,
    roam_flag                        smallint encode az64,
    granted_bytes_cumulative         bigint encode az64,
    granted_money                    numeric(22, 6) encode az64,
    total_used_bytes                 bigint encode az64,
    chargeable_used_bytes            bigint encode az64,
    uploaded_bytes                   bigint encode az64,
    downloaded_bytes                 bigint encode az64,
    data_connection_time             timestamp encode zstd,
    data_termination_time            timestamp encode zstd,
    time_duration                    integer encode az64,
    initial_account_balance          numeric(22, 6) encode az64,
    data_charge                      numeric(22, 6) encode az64,
    final_account_balance            numeric(22, 6) encode az64,
    free_bytes                       bigint encode az64,
    sessionid                        varchar(50) encode zstd,
    last_topup_type                  smallint encode az64,
    free_data_expiry_date            date encode zstd,
    charge_indicator                 smallint encode az64,
    final_unit_indicator             smallint encode az64,
    bundle_code                      varchar(10),
    accid                            varchar(11) encode zstd,
    deptid                           varchar(15) encode zstd,
    bundle_used_data                 varchar(10) encode zstd,
    bundle_data_charge               numeric(22, 6) encode az64,
    bundle_balance                   numeric(22, 6) encode az64,
    bundle_plan_id                   varchar(5) encode zstd,
    local_roam_country_code          smallint encode az64,
    sdfid                            smallint encode az64,
    rategroupid                      smallint encode az64,
    serviceid                        varchar(4) encode zstd,
    cdr_time_stamp                   timestamp encode zstd,
    intial_free_units                bigint encode az64,
    subscriber_type                  smallint encode az64,
    cdr_sequence_number              integer encode az64,
    sub_acct_id                      bigint encode az64,
    ggsn_time                        varchar(100) encode zstd,
    tariff_plan_change_id            smallint encode az64,
    used_unit_bfr_tariff_plan_change bigint encode az64,
    family_account_id                integer encode az64,
    bundle_version_name              varchar(50) encode zstd,
    bundle_versionid                 smallint encode az64,
    reward_slab_id                   smallint encode az64,
    pricing_plan_id                  smallint encode az64,
    rate_id                          integer encode az64,
    pocket_id                        integer encode az64,
    consumed_promo_amount            numeric(22, 6) encode az64,
    consumed_surcharge               numeric(22, 6) encode az64,
    rlh_charging_indicator           smallint encode az64,
    granted_bytes_current            bigint encode az64,
    roaming_partner_id               smallint encode az64,
    fct_free_text_1                  varchar(50) encode zstd,
    fct_free_text_2                  varchar(50) encode zstd,
    fct_free_text_3                  varchar(50) encode zstd,
    fct_free_text_4                  varchar(50) encode zstd,
    fct_free_text_5                  varchar(50) encode zstd,
    fct_free_text_6                  varchar(50) encode zstd,
    fct_free_text_7                  varchar(50) encode zstd,
    fct_free_text_8                  varchar(50) encode zstd,
    fct_free_text_9                  varchar(50) encode zstd,
    fct_free_text_10                 varchar(50) encode zstd,
    fct_free_text_11                 varchar(50) encode zstd,
    fct_free_text_12                 varchar(50) encode zstd,
    fct_free_text_13                 varchar(50) encode zstd,
    fct_free_text_14                 varchar(50) encode zstd,
    fct_free_text_15                 varchar(50) encode zstd,
    fct_free_text_16                 varchar(50) encode zstd,
    fct_free_text_17                 varchar(50) encode zstd,
    fct_free_text_18                 varchar(50) encode zstd,
    fct_free_text_19                 varchar(50) encode zstd,
    fct_free_text_20                 varchar(50) encode zstd,
    data_connection_month            integer,
    data_connection_dt               date encode az64,
    data_connection_dt_num           integer encode az64,
    data_connection_hour             integer encode az64,
    data_termination_month           integer encode az64,
    data_termination_dt              date encode az64,
    data_termination_dt_num          integer encode az64,
    data_termination_hour            integer encode az64,
    data_connection_month_gmt        integer encode az64,
    data_connection_dt_num_gmt       integer encode az64,
    data_connection_hour_gmt         integer encode az64,
    data_connection_time_gmt         timestamp encode zstd,
    data_termination_month_gmt       integer encode az64,
    data_termination_dt_num_gmt      integer encode az64,
    data_termination_hour_gmt        integer encode az64,
    data_termination_time_gmt        timestamp encode zstd,
    total_usage_mb                   numeric(22, 6) encode az64,
    free_data_expiry_date_num        integer encode az64,
    roaming_partner_name             varchar(50) encode zstd,
    filename                         varchar(100) encode zstd,
    batch_id                         integer   not null encode zstd,
    created_date                     timestamp not null encode zstd,
    rec_checksum                     varchar(32) encode zstd
)
    diststyle key
    sortkey (data_connection_month, data_connection_dt_num, bundle_code);