create table uk_rrbs_dm.temp_fact_rrbs_gprs
(
    cdr_type                         integer encode az64,
    network_id                       integer encode az64,
    data_feature                     integer encode az64,
    tariffplan_id                    integer encode az64,
    service_id                       integer encode az64,
    msisdn                           bigint encode az64,
    apn                              varchar(100),
    pdp_address                      varchar(100),
    cellid                           varchar(100),
    imei                             varchar(100),
    imsi                             bigint encode az64,
    serving_node                     varchar(100),
    ggsn_address                     varchar(100),
    roaming_zone_name                varchar(100),
    roam_flag                        integer encode az64,
    granted_bytes_cumulative         bigint encode az64,
    granted_money                    numeric(22, 6) encode az64,
    total_used_bytes                 bigint encode az64,
    chargeable_used_bytes            bigint encode az64,
    uploaded_bytes                   bigint encode az64,
    downloaded_bytes                 bigint encode az64,
    data_connection_time             timestamp encode az64,
    data_termination_time            timestamp encode az64,
    time_duration                    integer encode az64,
    initial_account_balance          numeric(22, 6) encode az64,
    data_charge                      numeric(22, 6) encode az64,
    final_account_balance            numeric(22, 6) encode az64,
    free_bytes                       bigint encode az64,
    sessionid                        varchar(100),
    last_topup_type                  integer encode az64,
    free_data_expiry_date            date encode az64,
    charge_indicator                 integer encode az64,
    final_unit_indicator             integer encode az64,
    bundle_code                      varchar(100),
    accid                            varchar(100),
    deptid                           varchar(100),
    bundle_used_data                 varchar(100),
    bundle_data_charge               numeric(22, 6) encode az64,
    bundle_balance                   numeric(22, 6) encode az64,
    bundle_plan_id                   varchar(100),
    local_roam_country_code          integer encode az64,
    sdfid                            integer encode az64,
    rategroupid                      integer encode az64,
    serviceid                        varchar(100),
    cdr_time_stamp                   timestamp encode az64,
    intial_free_units                bigint encode az64,
    subscriber_type                  integer encode az64,
    cdr_sequence_number              integer encode az64,
    sub_acct_id                      bigint encode az64,
    ggsn_time                        varchar(100),
    tariff_plan_change_id            integer encode az64,
    used_unit_bfr_tariff_plan_change bigint encode az64,
    family_account_id                integer encode az64,
    bundle_version_name              varchar(100),
    bundle_versionid                 integer encode az64,
    reward_slab_id                   integer encode az64,
    pricing_plan_id                  integer encode az64,
    rate_id                          integer encode az64,
    pocket_id                        integer encode az64,
    consumed_promo_amount            numeric(22, 6) encode az64,
    consumed_surcharge               numeric(22, 6) encode az64,
    rlh_charging_indicator           integer encode az64,
    granted_bytes_current            bigint encode az64,
    roaming_partner_id               integer encode az64,
    fct_free_text_1                  varchar(100),
    fct_free_text_2                  varchar(100),
    fct_free_text_3                  varchar(100),
    fct_free_text_4                  varchar(100),
    fct_free_text_5                  varchar(100),
    fct_free_text_6                  varchar(100),
    fct_free_text_7                  varchar(100),
    fct_free_text_8                  varchar(100),
    fct_free_text_9                  varchar(100),
    fct_free_text_10                 varchar(100),
    fct_free_text_11                 varchar(100),
    fct_free_text_12                 varchar(100),
    fct_free_text_13                 varchar(100),
    fct_free_text_14                 varchar(100),
    fct_free_text_15                 varchar(100),
    fct_free_text_16                 varchar(100),
    fct_free_text_17                 varchar(100),
    fct_free_text_18                 varchar(100),
    fct_free_text_19                 varchar(100),
    fct_free_text_20                 varchar(100),
    data_connection_month            integer encode az64,
    data_connection_dt               date encode az64,
    data_connection_dt_num           integer encode az64,
    data_connection_hour             integer encode az64,
    data_termination_month           integer encode az64,
    data_termination_dt              date encode az64,
    data_termination_dt_num          integer encode az64,
    data_termination_hour            integer encode az64,
    data_connection_month_gmt        integer encode az64,
    data_connection_dt_num_gmt       integer encode az64,
    data_connection_hour_gmt         integer encode az64,
    data_connection_time_gmt         timestamp encode az64,
    data_termination_month_gmt       integer encode az64,
    data_termination_dt_num_gmt      integer encode az64,
    data_termination_hour_gmt        integer encode az64,
    data_termination_time_gmt        timestamp encode az64,
    total_usage_mb                   numeric(22, 6) encode az64,
    free_data_expiry_date_num        integer encode az64,
    roaming_partner_name             varchar(100),
    filename                         varchar(100),
    batch_id                         integer encode az64,
    created_date                     timestamp      not null encode az64,
    rec_checksum                     varchar(100) not null
);
