create table uk_rrbs_dm.temp_fact_rrbs_topup_duplcdr
(
    operation_code                           integer encode az64,
    network_id                               integer encode az64,
    recharge_type                            integer encode az64,
    msisdn                                   bigint encode az64,
    imsi                                     bigint encode az64,
    account_pin_number                       varchar(100),
    voucher_card_id                          integer encode az64,
    special_topup_amount                     numeric(22, 6) encode az64,
    transaction_id                           varchar(100),
    new_balance                              numeric(22, 6) encode az64,
    face_value                               numeric(22, 6) encode az64,
    recharge_amount                          numeric(22, 6) encode az64,
    promo_validity_date                      date encode az64,
    free_minutes                             integer encode az64,
    free_voucher_onnet_minutes               integer encode az64,
    free_minutes_expiry_date                 date encode az64,
    free_sms                                 integer encode az64,
    free_voucher_onnet_sms                   integer encode az64,
    free_sms_expiry_date                     date encode az64,
    free_offnet_minutes                      integer encode az64,
    free_voucher_offnet_minutes              integer encode az64,
    free_offnet_minutes_expiry_date          date encode az64,
    free_offnet_sms                          integer encode az64,
    free_voucher_offnet_sms                  integer encode az64,
    free_offnet_sms_expiry_date              date encode az64,
    free_offnet2_minutes                     integer encode az64,
    free_vouchercard_offnet2_minutes         integer encode az64,
    free_offnet2_minutes_expiry_date         date encode az64,
    free_offnet2_sms                         integer encode az64,
    free_vouchercard_offnet2_sms             integer encode az64,
    free_offnet2_sms_expiry_date             date encode az64,
    free_offnet3_minutes                     integer encode az64,
    free_vouchercard_offnet3_minutes         integer encode az64,
    free_offnet3_minutes_expiry_date         date encode az64,
    free_offnet3_sms                         integer encode az64,
    free_vouchercard_offnet3_sms             integer encode az64,
    free_offnet3_sms_expiry_date             date encode az64,
    free_data                                bigint encode az64,
    free_voucher_data                        bigint encode az64,
    free_data_expirydate                     date encode az64,
    account_validity_date                    date encode az64,
    lyca_voucher_card_id                     varchar(100),
    planid                                   integer encode az64,
    topup_counter                            integer encode az64,
    bundle_code                              integer encode az64,
    imei                                     varchar(100),
    voucher_onnet_mins_expdt                 timestamp encode az64,
    voucher_onnet_sms_expdt                  timestamp encode az64,
    voucher_offnet_mins_expdt1               timestamp encode az64,
    voucher_offnet_sms_expdt1                timestamp encode az64,
    voucher_offnet_mins_expdt2               timestamp encode az64,
    voucher_offnet_sms_expdt2                timestamp encode az64,
    voucher_offnet_mins_expdt3               timestamp encode az64,
    voucher_offnet_sms_expdt3                timestamp encode az64,
    voucher_free_dataexp                     timestamp encode az64,
    retailer_msisdn                          varchar(100),
    staff_msisdn                             varchar(100),
    wlm_topupmode                            varchar(100),
    face_value_1                             numeric(22, 6) encode az64,
    promo_validity_days                      integer encode az64,
    oldplanid                                integer encode az64,
    onnet_mt_mins                            integer encode az64,
    voucher_onnet_mt_mins                    integer encode az64,
    onnet_mt_sms                             integer encode az64,
    voucher_onnet_mt_sms                     integer encode az64,
    onnet_mt_exp_dt                          timestamp encode az64,
    voucher_onnet_mt_expiry_date             date encode az64,
    offnet_mt_mins                           integer encode az64,
    voucher_offnet_mt_mins                   integer encode az64,
    offnet_mt_sms                            integer encode az64,
    voucher_offnet_mt_sms                    integer encode az64,
    offnet_mt_exp_dt                         timestamp encode az64,
    voucher_offnet_mt_expiry_date            date encode az64,
    bundle_name                              varchar(100),
    old_account_balance                      numeric(22, 6) encode az64,
    parent_msisdn                            varchar(100),
    rrbs_transaction_id                      varchar(100),
    override_bundle                          integer encode az64,
    vouchernetworkid                         integer encode az64,
    accid                                    varchar(100),
    deptid                                   varchar(100),
    bundle_catery                            integer encode az64,
    plan_validity_days                       integer encode az64,
    account_id                               bigint encode az64,
    sim_number                               bigint encode az64,
    cdr_time_stamp                           timestamp encode az64,
    reservation                              integer encode az64,
    discount_promo_code                      varchar(100),
    discount_promo_amount                    numeric(22, 6) encode az64,
    primary_bundle_code                      integer encode az64,
    family_account_id                        varchar(100),
    tax                                      numeric(22, 6) encode az64,
    number_of_installments                   integer encode az64,
    oba_bundle_flag                          integer encode az64,
    oba_due_amount                           numeric(22, 6) encode az64,
    parent_bundle_code                       integer encode az64,
    bundle_unit_type                         integer encode az64,
    contract_start_date                      date encode az64,
    contract_end_date                        varchar(100),
    flh_flag                                 integer encode az64,
    exibs_retailer_transaction_id            varchar(100),
    operation_flag                           integer encode az64,
    vat_amount                               numeric(22, 6) encode az64,
    special_discount_code                    varchar(100),
    special_discount_amount                  numeric(22, 6) encode az64,
    number_of_installments_discounts_applied varchar(100),
    actual_bundle_cost                       numeric(22, 6) encode az64,
    reservation_reference_transaction_id     varchar(100),
    bundle_expiry_type                       integer encode az64,
    bundle_balance                           numeric(22, 6) encode az64,
    muv_indicator                            integer encode az64,
    bundle_group_type                        integer encode az64,
    sequence_number                          integer encode az64,
    amount_refunded                          numeric(22, 6) encode az64,
    forcible_cancellation                    varchar(100),
    payment_mode_indicator                   varchar(100),
    amount                                   numeric(22, 6) encode az64,
    version_id                               integer encode az64,
    refund_entity_type                       integer encode az64,
    refund_provided_to                       varchar(100),
    topup_validity_days                      integer encode az64,
    reserve_amount                           numeric(22, 6) encode az64,
    preloaded_bundle_flag                    integer encode az64,
    staff_indicator                          integer encode az64,
    child_addition_discount                  numeric(22, 6) encode az64,
    payg_family_indicator                    integer encode az64,
    payg_prorate_flag                        integer encode az64,
    payg_child_index                         integer encode az64,
    parent_msisdn1                           varchar(100),
    payg_member_count                        integer encode az64,
    direct_addon_flag                        integer encode az64,
    action_flag                              integer encode az64,
    bundle_topup_timestamp                   varchar(100),
    sim_with_bundle_code                     integer encode az64,
    taxation_details                         varchar(100),
    reserved                                 varchar(100),
    bundle_purchase_date                     timestamp encode az64,
    bundle_start_date                        timestamp encode az64,
    renewal_payment_mode                     integer encode az64,
    iot_bundle_flag                          integer encode az64,
    veekbundleflag                           integer encode az64,
    validity_overridden                      integer encode az64,
    link_type                                integer encode az64,
    overwrite_bundle_cost_flag               integer encode az64,
    order_id                                 varchar(100),
    pocket_id                                varchar(100),
    da_track                                 numeric(22, 6) encode az64,
    da_principal_amount                      numeric(22, 6) encode az64,
    is_loan_request                          integer encode az64,
    migrated_ortel_subscriber_flag           integer encode az64,
    reward_purchased                         integer encode az64,
    feebuffer                                varchar(100),
    tax_buffer                               varchar(100),
    paymentgateway                           varchar(100),
    zipcode                                  varchar(100),
    professional_channel_name                varchar(100),
    topupcriteriaflag                        integer encode az64,
    nus_id                                   varchar(100),
    nus_applied                              integer encode az64,
    slotid                                   varchar(100),
    reserved_bundle_cost                     varchar(100),
    additional_channel_info                  varchar(100),
    autoflag                                 varchar(100),
    bundleexpirydate                         varchar(100),
    portinofferflag                          varchar(100),
    portinoffervaliditydays                  varchar(100),
    refunded_bundle_allowance_info           varchar(100),
    voucher_bundle_flag                      varchar(100),
    vouche_eligible_flag                     varchar(100),
    bundle_implicit_promo                    varchar(100),
    free_credit                              varchar(100),
    voucher_remaining_amount                 varchar(100),
    promo_code_type                          varchar(100),
    free_credit_offered_month                varchar(100),
    free_credit_type                         varchar(100),
    free_credit_promo_balance_validit_days   varchar(100),
    exempt_min_bal_checkexpiry_date          varchar(100),
    varibalepromoappliedinstallinfo          varchar(100),
    variablepromocardinfo                    varchar(100),
    new_exempt_in_bal_check_expiry_date      varchar(100),
    refund_transaction_id                    varchar(100),
    oba_cancellation_type                    varchar(100),
    oba_credit_consumed                      varchar(100),
    bypass_validation_for_special_bundles    varchar(100),
    campaign_flag                            varchar(100),
    campaign_key                             varchar(100),
    fct_free_text_1                          varchar(100),
    fct_free_text_2                          varchar(100),
    fct_free_text_3                          varchar(100),
    fct_free_text_4                          varchar(100),
    fct_free_text_5                          varchar(100),
    fct_free_text_6                          varchar(100),
    fct_free_text_7                          varchar(100),
    fct_free_text_8                          varchar(100),
    fct_free_text_9                          varchar(100),
    fct_free_text_10                         varchar(100),
    fct_free_text_11                         varchar(100),
    fct_free_text_12                         varchar(100),
    fct_free_text_13                         varchar(100),
    fct_free_text_14                         varchar(100),
    fct_free_text_15                         varchar(100),
    fct_free_text_16                         varchar(100),
    fct_free_text_17                         varchar(100),
    fct_free_text_18                         varchar(100),
    fct_free_text_19                         varchar(100),
    fct_free_text_20                         varchar(100),
    cdr_dt                                   date encode az64,
    cdr_dt_month                             integer encode az64,
    cdr_dt_num                               integer encode az64,
    is_bundle_loyalty                        integer        not null encode az64,
    bundle_usage_1                           numeric(22, 6) encode az64,
    bundle_usage_2                           numeric(22, 6) encode az64,
    cdr_dt_gmt                               timestamp encode az64,
    cdr_dt_month_gmt                         integer encode az64,
    cdr_dt_num_gmt                           integer encode az64,
    cdr_dt_hour_gmt                          integer encode az64,
    expiry_date_derived                      date encode az64,
    expiry_date_derived_num                  integer encode az64,
    expiry_date_month_derived                integer encode az64,
    roaming_partner_name                     varchar(100),
    filename                                 varchar(100),
    batch_id                                 integer encode az64,
    created_date                             timestamp      not null encode az64,
    rec_checksum                             varchar(100) not null
);
