AWSTemplateFormatVersion: 2010-09-09
Description: SFTP to destination folder ingestion
Parameters:
  LandingBucket:
    Type: String
    Description: The bucket where files will land and move
Resources:
  FileObjects:
    Type: AWS::Lambda::Function
    Properties:
      Description: React to objects landing in the bucket by adding to the job queue
      Code: lambda/
      Handler: file_mover.lambda_handler
      Runtime: python3.8
      Timeout: 120
      Environment:
        Variables:
          MAPPING_TABLE: !Ref MappingDdb
      Role: !GetAtt FileObjectsRole.Arn
  FileObjectsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/OrganizationAccountServiceBoundariesPolicy
      Policies:
        - PolicyName: mis-dl-root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - 's3:PutObject*'
                  - 's3:DeleteObject'
                  - 's3:GetObject*'
                Resource: !Sub 'arn:aws:s3:::${LandingBucket}/*'
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                Resource:
                  - !GetAtt MappingDdb.Arn 
  FileUploadsSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-uploads
      Subscription:
        -
          Endpoint: !GetAtt FileObjects.Arn
          Protocol: lambda
  FileUploadsTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sns:Publish
            Resource: !Ref FileUploadsSnsTopic            
      Topics:
        - !Ref FileUploadsSnsTopic
          
  FilerSubmissionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt FileObjects.Arn
      Action: 'lambda:InvokeFunction'
      Principal: sns.amazonaws.com
      SourceArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AWS::StackName}-uploads
  MappingDdb:
    Type: "AWS::DynamoDB::Table"
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "SourceDir"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - 
          AttributeName: "SourceDir"
          KeyType: "HASH"
