CREATE TABLE uk_rrbs_dm.tgl_dsm_retailer
(
    id INT encode az64
	,Retailerid VARCHAR(25) encode zstd
	,HotSpotid VARCHAR(25) encode zstd
	,AccMgrid VARCHAR(25) encode zstd
	,OffMgrid VARCHAR(25) encode zstd
	,Fname VARCHAR(50) encode zstd
	,Lname VARCHAR(50) encode zstd
	,country VARCHAR(50) encode zstd
	,STATE VARCHAR(50) encode zstd
	,postcode VARCHAR(10) encode zstd
	,houseno VARCHAR(50) encode zstd
	,streetno VARCHAR(50) encode zstd
	,street VARCHAR(100) encode zstd
	,address1 VARCHAR(100) encode zstd
	,address2 VARCHAR(100) encode zstd
	,cityname VARCHAR(50) encode zstd
	,pin VARCHAR(15) encode zstd
	,landlineno VARCHAR(15) encode zstd
	,mobileno VARCHAR(200) encode zstd
	,email VARCHAR(500) encode zstd
	,username VARCHAR(100) encode zstd
	,contactperson VARCHAR(50) encode zstd
	,STATUS INT encode az64
	,Invoicetype VARCHAR(25) encode zstd
	,CreatedBy VARCHAR(50) encode zstd
	,CreatedDate DATETIME encode az64
	,threshold INT encode az64
	,UpdatedBy VARCHAR(50) encode zstd
	,UpdatedDate DATETIME encode az64
	,AuthLevel INT encode az64
	,Comments VARCHAR(200) encode zstd
	,OptionalStatus SMALLINT encode az64
	,DelAuthLevel INT encode az64
	,EditAuthLevel INT encode az64
	,HistoryID INT encode az64
	,AlternateMobileno VARCHAR(25) encode zstd
	,Bankaddress VARCHAR(200) encode zstd
	,AccountHolderName VARCHAR(100) encode zstd
	,AccountSortcode VARCHAR(20) encode zstd
	,Accountnumber VARCHAR(20) encode zstd
	,Bankname VARCHAR(50) encode zstd
	,sitecode VARCHAR(3) encode zstd
	,Password VARCHAR(100) encode zstd
	,ShopType VARCHAR(50) encode zstd
	,WhiteListMSISDN VARCHAR(16) encode zstd
	,Transfer_Balance NUMERIC(38,10) encode az64
	,CC_Balance NUMERIC(38,10) encode az64
	,Accumulated_Discount NUMERIC(38,10) encode az64
	,GROUPID INT encode az64
	,RetailerMode INT encode az64
	,virtual_msisdn VARCHAR(20) encode zstd
	,VirtualtoRealDate DATETIME encode az64
	,FLOORNO VARCHAR(50) encode zstd
	,PassExpireDate DATETIME encode az64
	,LastLoginDate DATETIME encode az64
	,IsThreshold INT encode az64
	,SecretQuestion VARCHAR(200) encode zstd
	,SecretAnswer VARCHAR(100) encode zstd
	,IsSecQnAlert INT encode az64
	,unique_urn VARCHAR(20) encode zstd
	,ThresholdExcludedOn DATETIME encode az64
	,IsCreditHigherLayer INT encode az64
	,PreferLanguage VARCHAR(50) encode zstd
	,Is_specialretailer SMALLINT encode az64
	,spl_retupd_date DATETIME encode az64
	,COMMISION_GROUPID INT encode az64
	,LoginAttempt INT encode az64
	,LockedDateTime DATETIME encode az64
	,Area VARCHAR(100) encode zstd
	,District VARCHAR(100) encode zstd
	,VATno VARCHAR(100) encode zstd
	,SimActivationAmount2 NUMERIC(38,10) encode az64
	,CreditLimitAmt NUMERIC(38,10) encode az64
	,CreditLimitAuthDate DATETIME encode az64
	,StockOTP VARCHAR(20) encode zstd
	,Stock_modifiedby VARCHAR(50) encode zstd
	,Stock_modifieddate DATETIME encode az64
	,IsBalanceNegative SMALLINT encode az64
	,Is_mailSent SMALLINT encode az64
	,StockNotification SMALLINT encode az64
	,NotificationOnOffUploadDate DATETIME encode az64
	,IsReplicate SMALLINT encode az64
	,SBTRetailerEdit SMALLINT encode az64
	,StreetNumber VARCHAR(100) encode zstd
	,Estate VARCHAR(100) encode zstd
	,Airtime_Transfer SMALLINT encode az64
	,IsPwdSent SMALLINT encode az64
	,Division VARCHAR(100) encode zstd
	,Requested_by VARCHAR(100) encode zstd
	,Requested_date DATETIME encode az64
	,PreApproved_by VARCHAR(100) encode zstd
	,PreApproved_date DATETIME encode az64
	,Approved_by VARCHAR(100) encode zstd
	,Approved_date DATETIME encode az64
	,Freeze_Status INT encode az64
	,freezereason VARCHAR(500) encode zstd
	,Edit_Reason VARCHAR(1000) encode zstd
	,Tran_PIN VARCHAR(50) encode zstd
	,PINRetryAttempts INT encode az64
	,PINLockedDate DATETIME encode az64
	,Ret_Auto_BalLimit NUMERIC(38,10) encode az64
	,Ret_Auto_TopupAmt NUMERIC(38,10) encode az64
	,Ret_Auto_LmtFreq INT encode az64
	,Ret_Auto_MaxLmt INT encode az64
	,Ret_AutoTopup_chk INT encode az64
	,Ret_Auto_FrmDt DATETIME encode az64
	,Ret_Auto_ToDt DATETIME encode az64
	,Ret_Auto_PrsCnt INT encode az64
	,Ret_UUID VARCHAR(100) encode zstd
	,AgentMSISDN VARCHAR(16) encode zstd
	,AgentPin VARCHAR(15) encode zstd
	,IsAgent INT encode az64
	,TAXID VARCHAR(100) encode zstd
	,BusinessRegistrationNo VARCHAR(100) encode zstd
	,SocialSecurityNo VARCHAR(100) encode zstd
	,batch_id INTEGER
	,created_DATE TIMESTAMP
	,rec_checksum VARCHAR(32)
);

CREATE TABLE uk_rrbs_dm.tgl_dsm_retailer_duplcdr
(
    id INT encode az64
	,Retailerid VARCHAR(25) encode zstd
	,HotSpotid VARCHAR(25) encode zstd
	,AccMgrid VARCHAR(25) encode zstd
	,OffMgrid VARCHAR(25) encode zstd
	,Fname VARCHAR(50) encode zstd
	,Lname VARCHAR(50) encode zstd
	,country VARCHAR(50) encode zstd
	,STATE VARCHAR(50) encode zstd
	,postcode VARCHAR(10) encode zstd
	,houseno VARCHAR(50) encode zstd
	,streetno VARCHAR(50) encode zstd
	,street VARCHAR(100) encode zstd
	,address1 VARCHAR(100) encode zstd
	,address2 VARCHAR(100) encode zstd
	,cityname VARCHAR(50) encode zstd
	,pin VARCHAR(15) encode zstd
	,landlineno VARCHAR(15) encode zstd
	,mobileno VARCHAR(200) encode zstd
	,email VARCHAR(500) encode zstd
	,username VARCHAR(100) encode zstd
	,contactperson VARCHAR(50) encode zstd
	,STATUS INT encode az64
	,Invoicetype VARCHAR(25) encode zstd
	,CreatedBy VARCHAR(50) encode zstd
	,CreatedDate DATETIME encode az64
	,threshold INT encode az64
	,UpdatedBy VARCHAR(50) encode zstd
	,UpdatedDate DATETIME encode az64
	,AuthLevel INT encode az64
	,Comments VARCHAR(200) encode zstd
	,OptionalStatus SMALLINT encode az64
	,DelAuthLevel INT encode az64
	,EditAuthLevel INT encode az64
	,HistoryID INT encode az64
	,AlternateMobileno VARCHAR(25) encode zstd
	,Bankaddress VARCHAR(200) encode zstd
	,AccountHolderName VARCHAR(100) encode zstd
	,AccountSortcode VARCHAR(20) encode zstd
	,Accountnumber VARCHAR(20) encode zstd
	,Bankname VARCHAR(50) encode zstd
	,sitecode VARCHAR(3) encode zstd
	,Password VARCHAR(100) encode zstd
	,ShopType VARCHAR(50) encode zstd
	,WhiteListMSISDN VARCHAR(16) encode zstd
	,Transfer_Balance NUMERIC(38,10) encode az64
	,CC_Balance NUMERIC(38,10) encode az64
	,Accumulated_Discount NUMERIC(38,10) encode az64
	,GROUPID INT encode az64
	,RetailerMode INT encode az64
	,virtual_msisdn VARCHAR(20) encode zstd
	,VirtualtoRealDate DATETIME encode az64
	,FLOORNO VARCHAR(50) encode zstd
	,PassExpireDate DATETIME encode az64
	,LastLoginDate DATETIME encode az64
	,IsThreshold INT encode az64
	,SecretQuestion VARCHAR(200) encode zstd
	,SecretAnswer VARCHAR(100) encode zstd
	,IsSecQnAlert INT encode az64
	,unique_urn VARCHAR(20) encode zstd
	,ThresholdExcludedOn DATETIME encode az64
	,IsCreditHigherLayer INT encode az64
	,PreferLanguage VARCHAR(50) encode zstd
	,Is_specialretailer SMALLINT encode az64
	,spl_retupd_date DATETIME encode az64
	,COMMISION_GROUPID INT encode az64
	,LoginAttempt INT encode az64
	,LockedDateTime DATETIME encode az64
	,Area VARCHAR(100) encode zstd
	,District VARCHAR(100) encode zstd
	,VATno VARCHAR(100) encode zstd
	,SimActivationAmount2 NUMERIC(38,10) encode az64
	,CreditLimitAmt NUMERIC(38,10) encode az64
	,CreditLimitAuthDate DATETIME encode az64
	,StockOTP VARCHAR(20) encode zstd
	,Stock_modifiedby VARCHAR(50) encode zstd
	,Stock_modifieddate DATETIME encode az64
	,IsBalanceNegative SMALLINT encode az64
	,Is_mailSent SMALLINT encode az64
	,StockNotification SMALLINT encode az64
	,NotificationOnOffUploadDate DATETIME encode az64
	,IsReplicate SMALLINT encode az64
	,SBTRetailerEdit SMALLINT encode az64
	,StreetNumber VARCHAR(100) encode zstd
	,Estate VARCHAR(100) encode zstd
	,Airtime_Transfer SMALLINT encode az64
	,IsPwdSent SMALLINT encode az64
	,Division VARCHAR(100) encode zstd
	,Requested_by VARCHAR(100) encode zstd
	,Requested_date DATETIME encode az64
	,PreApproved_by VARCHAR(100) encode zstd
	,PreApproved_date DATETIME encode az64
	,Approved_by VARCHAR(100) encode zstd
	,Approved_date DATETIME encode az64
	,Freeze_Status INT encode az64
	,freezereason VARCHAR(500) encode zstd
	,Edit_Reason VARCHAR(1000) encode zstd
	,Tran_PIN VARCHAR(50) encode zstd
	,PINRetryAttempts INT encode az64
	,PINLockedDate DATETIME encode az64
	,Ret_Auto_BalLimit NUMERIC(38,10) encode az64
	,Ret_Auto_TopupAmt NUMERIC(38,10) encode az64
	,Ret_Auto_LmtFreq INT encode az64
	,Ret_Auto_MaxLmt INT encode az64
	,Ret_AutoTopup_chk INT encode az64
	,Ret_Auto_FrmDt DATETIME encode az64
	,Ret_Auto_ToDt DATETIME encode az64
	,Ret_Auto_PrsCnt INT encode az64
	,Ret_UUID VARCHAR(100) encode zstd
	,AgentMSISDN VARCHAR(16) encode zstd
	,AgentPin VARCHAR(15) encode zstd
	,IsAgent INT encode az64
	,TAXID VARCHAR(100) encode zstd
	,BusinessRegistrationNo VARCHAR(100) encode zstd
	,SocialSecurityNo VARCHAR(100) encode zstd
	,batch_id INTEGER
	,created_DATE TIMESTAMP
	,rec_checksum VARCHAR(32)
);