
update ss_test.fact_rrbs_gprs_test
set rec_checksum = 
md5 (

nvl(nullif((	cdr_type							          :: text),''),'0')
nvl(nullif((	network_id                                    :: text),''),'0')
nvl(nullif((	data_feature                                  :: text),''),'0')
nvl(nullif((	tariffplan_id                                 :: text),''),'0')
nvl(nullif((	service_id                                    :: text),''),'0')
nvl(nullif((	msisdn                                        :: text),''),'0')
nvl(nullif((	apn                                           :: text),''),'0')
nvl(nullif((	pdp_address                                   :: text),''),'0')
nvl(nullif((	cellid                                        :: text),''),'0')
nvl(nullif((	imei                                          :: text),''),'0')
nvl(nullif((	imsi                                          :: text),''),'0')
nvl(nullif((	serving_node                                  :: text),''),'0')
nvl(nullif((	ggsn_address                                  :: text),''),'0')
nvl(nullif((	roaming_zone_name                             :: text),''),'0')
nvl(nullif((	roam_flag                                     :: text),''),'0')
nvl(nullif((	granted_bytes_cumulative                      :: text),''),'0')
nvl(nullif((	granted_money                                 :: text),''),'0')
nvl(nullif((	total_used_bytes                              :: text),''),'0')
nvl(nullif((	chargeable_used_bytes                         :: text),''),'0')
nvl(nullif((	uploaded_bytes                                :: text),''),'0')
nvl(nullif((	downloaded_bytes                              :: text),''),'0')
nvl(nullif((	data_connection_time                          :: text),''),'0')
nvl(nullif((	data_connection_dt                            :: text),''),'0')
nvl(nullif((	data_connection_dt_num                        :: text),''),'0')
nvl(nullif((	data_termination_time                         :: text),''),'0')
nvl(nullif((	data_termination_dt                           :: text),''),'0')
nvl(nullif((	data_termination_dt_num                       :: text),''),'0')
nvl(nullif((	time_duration                                 :: text),''),'0')
nvl(nullif((	initial_account_balance                       :: text),''),'0')
nvl(nullif((	data_charge                                   :: text),''),'0')
nvl(nullif((	final_account_balance                         :: text),''),'0')
nvl(nullif((	free_bytes                                    :: text),''),'0')
nvl(nullif((	sessionid                                     :: text),''),'0')
nvl(nullif((	last_topup_type                               :: text),''),'0')
nvl(nullif((	free_data_expiry_date                         :: text),''),'0')
nvl(nullif((	charge_indicator                              :: text),''),'0')
nvl(nullif((	final_unit_indicator                          :: text),''),'0')
nvl(nullif((	bundle_code                                   :: text),''),'0')
nvl(nullif((	accid                                         :: text),''),'0')
nvl(nullif((	deptid                                        :: text),''),'0')
nvl(nullif((	bundle_used_data                              :: text),''),'0')
nvl(nullif((	bundle_data_charge                            :: text),''),'0')
nvl(nullif((	bundle_balance                                :: text),''),'0')
nvl(nullif((	bundle_plan_id                                :: text),''),'0')
nvl(nullif((	local_roam_country_code                       :: text),''),'0')
nvl(nullif((	sdfid                                         :: text),''),'0')
nvl(nullif((	rategroupid                                   :: text),''),'0')
nvl(nullif((	serviceid                                     :: text),''),'0')
nvl(nullif((	cdr_time_stamp                                :: text),''),'0')
nvl(nullif((	intial_free_units                             :: text),''),'0')
nvl(nullif((	subscriber_type                               :: text),''),'0')
nvl(nullif((	cdr_sequence_number                           :: text),''),'0')
nvl(nullif((	sub_acct_id                                   :: text),''),'0')
nvl(nullif((	ggsn_time                                     :: text),''),'0')
nvl(nullif((	tariff_plan_change_id                         :: text),''),'0')
nvl(nullif((	used_units_before_tariff_plan_change          :: text),''),'0')
nvl(nullif((	family_account_id                             :: text),''),'0')
nvl(nullif((	bundle_version_name                           :: text),''),'0')
nvl(nullif((	bundle_versionid                              :: text),''),'0')
nvl(nullif((	reward_slab_id                                :: text),''),'0')
nvl(nullif((	pricing_plan_id                               :: text),''),'0')
nvl(nullif((	rate_id                                       :: text),''),'0')
nvl(nullif((	pocket_id                                     :: text),''),'0')
nvl(nullif((	consumed_promo_amount                         :: text),''),'0')
nvl(nullif((	consumed_surcharge                            :: text),''),'0')
nvl(nullif((	rlh_charging_indicator                        :: text),''),'0')
nvl(nullif((	granted_bytes_current                         :: text),''),'0')
nvl(nullif((	roaming_partner_id							  :: text),''),'0')
)
;
