--select top 5 md5(

--commit
alter table ss_test.fact_rrbs_sms_test add column rec_checksum varchar(32)
;

update ss_test.fact_rrbs_sms_test
set rec_checksum = 
md5 (
	nvl(nullif((	cdr_types	:: text),''),'0')
||	nvl(nullif((	network_id	:: text),''),'0')
||	nvl(nullif((	call_type	:: text),''),'0')
||	nvl(nullif((	plan_id	:: text),''),'0')
||	nvl(nullif((	service_id	:: text),''),'0')
||	nvl(nullif((	cli	:: text),''),'0')
||	nvl(nullif((	dialed_number	:: text),''),'0')
||	nvl(nullif((	imsi	:: text),''),'0')
||	nvl(nullif((	serving_node	:: text),''),'0')
||	nvl(nullif((	destination_area_code	:: text),''),'0')
||	nvl(nullif((	destination_zone_code	:: text),''),'0')
||	nvl(nullif((	destination_zone_name	:: text),''),'0')
||	nvl(nullif((	roam_flag	:: text),''),'0')
||	nvl(nullif((	roaming_node	:: text),''),'0')
||	nvl(nullif((	roaming_area_code	:: text),''),'0')
||	nvl(nullif((	roaming_zone_name	:: text),''),'0')
||	nvl(nullif((	sms_feature	:: text),''),'0')
||	nvl(nullif((	number_of_sms_charged	:: text),''),'0')
||	nvl(nullif((	number_of_free_sms	:: text),''),'0')
||	nvl(nullif((	initial_account_balance	:: text),''),'0')
||	nvl(nullif((	msg_cost	:: text),''),'0')
||	nvl(nullif((	balance	:: text),''),'0')
||	nvl(nullif((	free_sms_account_balance	:: text),''),'0')
||	nvl(nullif((	instance_id_session_id	:: text),''),'0')
||	nvl(nullif((	msg_date	:: text),''),'0')
||	nvl(nullif((	msg_date_dt	:: text),''),'0')
||	nvl(nullif((	msg_date_num	:: text),''),'0')
||	nvl(nullif((	account_id	:: text),''),'0')
||	nvl(nullif((	dept_id	:: text),''),'0')
||	nvl(nullif((	free_zone_id	:: text),''),'0')
||	nvl(nullif((	last_topup_type	:: text),''),'0')
||	nvl(nullif((	bundle_code	:: text),''),'0')
||	nvl(nullif((	free_zone_expiry_date	:: text),''),'0')
||	nvl(nullif((	bundle_sms_charge	:: text),''),'0')
||	nvl(nullif((	bundle_balance	:: text),''),'0')
||	nvl(nullif((	bundle_plan_id	:: text),''),'0')
||	nvl(nullif((	nsms_free_units	:: text),''),'0')
||	nvl(nullif((	local_roam_country_code	:: text),''),'0')
||	nvl(nullif((	cdr_time_stamp	:: text),''),'0')
||	nvl(nullif((	bucket_type	:: text),''),'0')
||	nvl(nullif((	initial_free_units	:: text),''),'0')
||	nvl(nullif((	subscriber_type	:: text),''),'0')
||	nvl(nullif((	sub_acct_id	:: text),''),'0')
||	nvl(nullif((	family_id	:: text),''),'0')
||	nvl(nullif((	concat_message_flag	:: text),''),'0')
||	nvl(nullif((	concat_message_reference_number	:: text),''),'0')
||	nvl(nullif((	concat_message_total_chunks	:: text),''),'0')
||	nvl(nullif((	concat_message_current_chunk	:: text),''),'0')
||	nvl(nullif((	trace_id	:: text),''),'0')
||	nvl(nullif((	idp_time	:: text),''),'0')
||	nvl(nullif((	extension_record	:: text),''),'0')
||	nvl(nullif((	call_indicator	:: text),''),'0')
||	nvl(nullif((	serving_node_name	:: text),''),'0')
||	nvl(nullif((	bundle_version_name	:: text),''),'0')
||	nvl(nullif((	flh_reward_slab_id	:: text),''),'0')
||	nvl(nullif((	bundle_version_id	:: text),''),'0')
||	nvl(nullif((	rate_id	:: text),''),'0')
||	nvl(nullif((	pricing_plan_id	:: text),''),'0')
||	nvl(nullif((	pocket_id	:: text),''),'0')
||	nvl(nullif((	consumed_promo_amount	:: text),''),'0')
||	nvl(nullif((	rlh_charging_indicator	:: text),''),'0')
||	nvl(nullif((	surcharge_consumed	:: text),''),'0')
||	nvl(nullif((	roaming_partner_id	:: text),''),'0')
)
;
--from  ss_test.fact_rrbs_sms_test
