create table fact_rrbs_balance_transfer_latecdr
(
    sk_rrbs_bt                             bigint default default_identity(167946, 0, ('1,1'::character varying)::text) encode az64,
    cdr_type                               integer,
    network_id                             integer encode az64,
    service_id                             varchar(30) encode zstd,
    msisdn_no                              bigint encode az64,
    imsi                                   bigint encode az64 distkey,
    receiver_msisdn                        varchar(30) encode zstd,
    account_balance                        numeric(22, 6) encode az64,
    amount_transferred                     numeric(22, 6) encode az64,
    final_account_balance                  numeric(22, 6) encode az64,
    operation_code                         varchar(30) encode zstd,
    transaction_id                         varchar(50) encode zstd,
    bundle_code                            integer encode az64,
    threshold_amount                       varchar(50) encode zstd,
    bytes_charged                          varchar(50) encode zstd,
    cardid                                 varchar(50) encode zstd,
    friend_type                            varchar(50) encode zstd,
    reward_point_type                      varchar(50) encode zstd,
    reward_point                           varchar(50) encode zstd,
    over_write_bundle_code                 varchar(50) encode zstd,
    over_write_bucket_id                   varchar(50) encode zstd,
    over_write_bundle_subscriber_counter   varchar(50) encode zstd,
    subscriber_counter                     varchar(50) encode zstd,
    cdr_time_stamp                         timestamp encode az64,
    amount_ind                             varchar(30) encode zstd,
    reason                                 varchar(50) encode zstd,
    new_bparty_number                      varchar(50) encode zstd,
    existing_bparty_number                 varchar(50) encode zstd,
    dedicated_account_balance              numeric(22, 6) encode az64,
    amount_detected_from_dedicated_balance numeric(22, 6) encode az64,
    final_balance_in_dedicated_account     numeric(22, 6) encode az64,
    actual_credit_limit                    numeric(22, 6) encode az64,
    available_credit_limit                 numeric(22, 6) encode az64,
    amount_detected_from_credit            numeric(22, 6) encode az64,
    vat_amount                             numeric(22, 6) encode az64,
    da_track                               varchar(50) encode zstd,
    da_principal_amount                    varchar(50) encode zstd,
    pocket_id                              varchar(50) encode zstd,
    account_id                             varchar(50) encode zstd,
    channel_transaction_id                 varchar(50) encode zstd,
    reserved1                              varchar(50) encode zstd,
    reserved2                              varchar(50) encode zstd,
    reserved3                              varchar(50) encode zstd,
    reserved4                              varchar(50) encode zstd,
    reserved5                              varchar(50) encode zstd,
    reserved6                              varchar(50) encode zstd,
    fct_free_text_1                        varchar(50) encode zstd,
    fct_free_text_2                        varchar(50) encode zstd,
    fct_free_text_3                        varchar(50) encode zstd,
    fct_free_text_4                        varchar(50) encode zstd,
    fct_free_text_5                        varchar(50) encode zstd,
    fct_free_text_6                        varchar(50) encode zstd,
    fct_free_text_7                        varchar(50) encode zstd,
    fct_free_text_8                        varchar(50) encode zstd,
    fct_free_text_9                        varchar(50) encode zstd,
    fct_free_text_10                       varchar(50) encode zstd,
    fct_free_text_11                       varchar(50) encode zstd,
    fct_free_text_12                       varchar(50) encode zstd,
    fct_free_text_13                       varchar(50) encode zstd,
    fct_free_text_14                       varchar(50) encode zstd,
    fct_free_text_15                       varchar(50) encode zstd,
    fct_free_text_16                       varchar(50) encode zstd,
    fct_free_text_17                       varchar(50) encode zstd,
    fct_free_text_18                       varchar(50) encode zstd,
    fct_free_text_19                       varchar(50) encode zstd,
    fct_free_text_20                       varchar(50) encode zstd,
    cdr_dt                                 date encode az64,
    cdr_dt_month                           integer,
    cdr_dt_num                             integer,
    cdr_time_stamp_gmt                     timestamp encode az64,
    cdr_dt_month_gmt                       integer encode az64,
    cdr_dt_num_gmt                         integer encode az64,
    cdr_dt_hour_gmt                        integer encode az64,
    filename                               varchar(100) encode zstd,
    batch_id                               integer encode az64,
    created_date                           timestamp encode az64,
    rec_checksum                           varchar(32) encode zstd
)
    diststyle key
    sortkey (cdr_dt_month, cdr_dt_num, cdr_type);
