create table temp_fact_rrbs_voice
(
    voice_call_cdr                    integer encode az64,
    network_id                        integer encode az64,
    call_type                         integer encode az64,
    call_feature                      integer encode az64,
    tariffplan_id                     integer encode az64,
    service_id                        integer encode az64,
    cli                               bigint encode az64,
    dialed_number                     varchar(65535),
    charged_party_number              bigint encode az64,
    imsi                              bigint encode az64,
    serving_node                      bigint encode az64,
    mcc                               integer encode az64,
    mnc                               integer encode az64,
    lac                               integer encode az64,
    calling_cell_id                   integer encode az64,
    cellzone_code                     varchar(65535),
    cellzone_name                     varchar(65535),
    original_dialed_number            bigint encode az64,
    destination_zone                  integer encode az64,
    destination_area_code             bigint encode az64,
    destinationzone_name              varchar(65535),
    roaming_area_code                 varchar(65535),
    roaming_zone_name                 varchar(65535),
    roam_flag                         integer encode az64,
    roam_area_number                  integer encode az64,
    granted_time                      integer encode az64,
    granted_money                     numeric(22, 6) encode az64,
    call_duration                     integer encode az64,
    chargeable_used_time              integer encode az64,
    call_date                         timestamp encode az64,
    call_termination_time             timestamp encode az64,
    initial_account_balance           numeric(22, 6) encode az64,
    talk_charge                       numeric(22, 6) encode az64,
    balance                           numeric(22, 6) encode az64,
    free_minutes_account_balance      numeric(22, 6) encode az64,
    account_id                        integer encode az64,
    dept_id                           integer encode az64,
    free_zone_id                      integer encode az64,
    trace_id                          varchar(65535),
    last_topup_type                   integer encode az64,
    bundle_code                       varchar(65535),
    free_zone_expiry_date             varchar(65535),
    ringing_duration                  varchar(65535),
    ring_indicator                    varchar(65535),
    national_bundle_code              varchar(65535),
    national_used_minutes             varchar(65535),
    national_charge                   varchar(65535),
    pool_number                       varchar(65535),
    bundle_used_seconds               varchar(65535),
    bundle_call_charge                varchar(65535),
    bundle_balance                    varchar(65535),
    bundle_plan_id                    varchar(65535),
    final_unit_indicator              varchar(65535),
    ncall_free_units                  varchar(65535),
    local_roam_country_code           varchar(65535),
    cdr_time_stamp                    timestamp encode az64,
    bucket_type                       integer encode az64,
    conversion_unit                   varchar(65535),
    intial_free_units                 integer encode az64,
    subscriber_type                   integer encode az64,
    call_forwarding_indicator         integer encode az64,
    cdr_sequence_number               integer encode az64,
    sub_acct_id                       integer encode az64,
    announcement_time                 integer encode az64,
    family_id                         integer encode az64,
    idp_time                          varchar(65535),
    cs_free_mins                      varchar(65535),
    free_units_detected               integer encode az64,
    multileg_charging_flag            integer encode az64,
    extension_record                  integer encode az64,
    connect_number                    varchar(65535),
    dialed_number1                    varchar(65535),
    service_description               varchar(65535),
    alternate_plan_id                 varchar(65535),
    serving_node_name                 varchar(65535),
    fixed_charge                      integer encode az64,
    fixed_charge_resource_impact      varchar(65535),
    bundle_version_name               varchar(65535),
    flh_reward_slab_id                integer encode az64,
    bundle_version_id                 integer encode az64,
    rate_id                           varchar(65535),
    pricing_plan_id                   varchar(65535),
    pocket_id                         varchar(65535),
    consumed_promo_amount             varchar(65535),
    pervious_call_trace_id            varchar(65535),
    termination_cause                 integer encode az64,
    non_chargeable_unit               integer encode az64,
    call_forward_msisdn               varchar(65535),
    service_type                      varchar(65535),
    used_time_in_previous_grant       integer encode az64,
    rlh_charging_indicator            integer encode az64,
    surcharge_consumed                integer encode az64,
    excess_used_units_received        integer encode az64,
    failcause                         integer encode az64,
    roaming_partner_id                integer encode az64,
    bundle_units_used_in_overage_plan varchar(65535),
    fct_free_text_1                   varchar(65535),
    fct_free_text_2                   varchar(65535),
    fct_free_text_3                   varchar(65535),
    fct_free_text_4                   varchar(65535),
    fct_free_text_5                   varchar(65535),
    fct_free_text_6                   varchar(65535),
    fct_free_text_7                   varchar(65535),
    fct_free_text_8                   varchar(65535),
    fct_free_text_9                   varchar(65535),
    fct_free_text_10                  varchar(65535),
    fct_free_text_11                  varchar(65535),
    fct_free_text_12                  varchar(65535),
    fct_free_text_13                  varchar(65535),
    fct_free_text_14                  varchar(65535),
    fct_free_text_15                  varchar(65535),
    fct_free_text_16                  varchar(65535),
    fct_free_text_17                  varchar(65535),
    fct_free_text_18                  varchar(65535),
    fct_free_text_19                  varchar(65535),
    fct_free_text_20                  varchar(65535),
    call_date_month                   integer encode az64,
    call_date_dt                      date encode az64,
    call_date_num                     integer encode az64,
    call_date_hour                    integer encode az64,
    call_date_month_gmt               integer encode az64,
    call_date_time_gmt                timestamp encode az64,
    call_date_num_gmt                 integer encode az64,
    call_date_hour_gmt                integer encode az64,
    call_duration_min                 numeric(22, 4) encode az64,
    chargeable_used_time_min          numeric(22, 4) encode az64,
    roaming_partner_name              varchar(65535),
    filename                          varchar(65535),
    batch_id                          integer encode az64,
    created_date                      timestamp      not null encode az64,
    rec_checksum                      varchar(65535) not null
);

