create table temp_fact_rrbs_sms_latecdr
(
    cdr_types                       integer encode az64,
    network_id                      integer encode az64,
    call_type                       integer encode az64,
    plan_id                         integer encode az64,
    service_id                      integer encode az64,
    cli                             bigint encode az64,
    dialed_number                   varchar(100),
    imsi                            bigint encode az64,
    serving_node                    bigint encode az64,
    destination_area_code           integer encode az64,
    destination_zone_code           integer encode az64,
    destination_zone_name           varchar(100),
    roam_flag                       integer encode az64,
    roaming_node                    integer encode az64,
    roaming_area_code               integer encode az64,
    roaming_zone_name               varchar(100),
    sms_feature                     integer encode az64,
    number_of_sms_charged           integer encode az64,
    number_of_free_sms              integer encode az64,
    initial_account_balance         numeric(22, 6) encode az64,
    msg_cost                        numeric(22, 6) encode az64,
    balance                         numeric(22, 6) encode az64,
    free_sms_account_balance        numeric(22, 6) encode az64,
    instance_id_session_id          varchar(100),
    account_id                      integer encode az64,
    dept_id                         integer encode az64,
    free_zone_id                    integer encode az64,
    last_topup_type                 integer encode az64,
    bundle_code                     integer encode az64,
    free_zone_expiry_date           date encode az64,
    bundle_sms_charge               numeric(22, 6) encode az64,
    bundle_balance                  numeric(22, 6) encode az64,
    bundle_plan_id                  integer encode az64,
    nsms_free_units                 integer encode az64,
    local_roam_country_code         integer encode az64,
    msg_date                        timestamp encode az64,
    bucket_type                     integer encode az64,
    initial_free_units              numeric(22, 6) encode az64,
    subscriber_type                 integer encode az64,
    sub_acct_id                     bigint encode az64,
    family_id                       varchar(100),
    concat_message_flag             integer encode az64,
    concat_message_reference_number integer encode az64,
    concat_message_total_chunks     integer encode az64,
    concat_message_current_chunk    integer encode az64,
    trace_id                        varchar(100),
    idp_time                        varchar(100),
    extension_record                integer encode az64,
    call_indicator                  integer encode az64,
    serving_node_name               varchar(100),
    bundle_version_name             varchar(100),
    flh_reward_slab_id              integer encode az64,
    bundle_version_id               integer encode az64,
    rate_id                         integer encode az64,
    pricing_plan_id                 integer encode az64,
    pocket_id                       bigint encode az64,
    consumed_promo_amount           numeric(22, 6) encode az64,
    rlh_charging_indicator          integer encode az64,
    surcharge_consumed              varchar(100),
    roaming_partner_id              varchar(100),
    smsc_gt                         varchar(100),
    fct_free_text_1                 varchar(100),
    fct_free_text_2                 varchar(100),
    fct_free_text_3                 varchar(100),
    fct_free_text_4                 varchar(100),
    fct_free_text_5                 varchar(100),
    fct_free_text_6                 varchar(100),
    fct_free_text_7                 varchar(100),
    fct_free_text_8                 varchar(100),
    fct_free_text_9                 varchar(100),
    fct_free_text_10                varchar(100),
    fct_free_text_11                varchar(100),
    fct_free_text_12                varchar(100),
    fct_free_text_13                varchar(100),
    fct_free_text_14                varchar(100),
    fct_free_text_15                varchar(100),
    fct_free_text_16                varchar(100),
    fct_free_text_17                varchar(100),
    fct_free_text_18                varchar(100),
    fct_free_text_19                varchar(100),
    fct_free_text_20                varchar(100),
    msg_date_month                  integer encode az64,
    msg_date_dt                     date encode az64,
    msg_date_num                    integer encode az64,
    msg_date_hour                   integer encode az64,
    msg_date_month_gmt              integer encode az64,
    msg_date_num_gmt                integer encode az64,
    msg_date_hour_gmt               integer encode az64,
    msg_date_time_gmt               timestamp encode az64,
    free_zone_expiry_date_num       integer encode az64,
    roaming_partner_name            varchar(100),
    filename                        varchar(100),
    batch_id                        integer encode az64,
    created_date                    timestamp      not null encode az64,
    rec_checksum                    varchar(100) not null
);
