create table temp_fact_rrbs_balance_transfer_duplcdr
(
    cdr_type                               integer encode az64,
    network_id                             integer encode az64,
    service_id                             varchar(100),
    msisdn_no                              bigint encode az64,
    imsi                                   bigint encode az64,
    receiver_msisdn                        varchar(100),
    account_balance                        numeric(22, 6) encode az64,
    amount_transferred                     numeric(22, 6) encode az64,
    final_account_balance                  numeric(22, 6) encode az64,
    operation_code                         varchar(100),
    transaction_id                         varchar(100),
    bundle_code                            integer encode az64,
    threshold_amount                       varchar(100),
    bytes_charged                          varchar(100),
    cardid                                 varchar(100),
    friend_type                            varchar(100),
    reward_point_type                      varchar(100),
    reward_point                           varchar(100),
    over_write_bundle_code                 varchar(100),
    over_write_bucket_id                   varchar(100),
    over_write_bundle_subscriber_counter   varchar(100),
    subscriber_counter                     varchar(100),
    cdr_time_stamp                         timestamp encode az64,
    amount_ind                             varchar(100),
    reason                                 varchar(100),
    new_bparty_number                      varchar(100),
    existing_bparty_number                 varchar(100),
    dedicated_account_balance              numeric(22, 6) encode az64,
    amount_detected_from_dedicated_balance numeric(22, 6) encode az64,
    final_balance_in_dedicated_account     numeric(22, 6) encode az64,
    actual_credit_limit                    numeric(22, 6) encode az64,
    available_credit_limit                 numeric(22, 6) encode az64,
    amount_detected_from_credit            numeric(22, 6) encode az64,
    vat_amount                             numeric(22, 6) encode az64,
    da_track                               varchar(100),
    da_principal_amount                    varchar(100),
    pocket_id                              varchar(100),
    account_id                             varchar(100),
    channel_transaction_id                 varchar(100),
    reserved1                              varchar(100),
    reserved2                              varchar(100),
    reserved3                              varchar(100),
    reserved4                              varchar(100),
    reserved5                              varchar(100),
    reserved6                              varchar(100),
    cdr_dt                                 date encode az64,
    cdr_dt_month                           integer encode az64,
    cdr_dt_num                             integer encode az64,
    cdr_time_stamp_gmt                     timestamp encode az64,
    cdr_dt_month_gmt                       integer encode az64,
    cdr_dt_num_gmt                         integer encode az64,
    cdr_dt_hour_gmt                        integer encode az64,
    filename                               varchar(100) not null,
    batch_id                               integer encode az64,
    created_date                           timestamp      not null encode az64,
    rec_checksum                           varchar(100) not null
);
