create table fact_mno_o2_data
(
    sk_mno_o2_data         bigint default default_identity(158623, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type               varchar(2) encode zstd,
    cdr_id                 varchar(12) encode zstd,
    imsi                   bigint encode az64 distkey,
    msisdn                 varchar(16) encode zstd,
    imei                   varchar(21) encode zstd,
    location               varchar(5) encode zstd,
    apn_ni                 varchar(63) encode zstd,
    apn_oi                 varchar(37) encode zstd,
    charging_timestamp     timestamp encode az64,
    duration               integer encode az64,
    data_volume_download   integer encode az64,
    data_volume_upload     integer encode az64,
    data_volume_total      integer encode az64,
    username               varchar(63) encode zstd,
    network_element_id     varchar(39) encode zstd,
    ggsn_address           varchar(39) encode zstd,
    charging_id            varchar(10) encode zstd,
    fragment_number        varchar(7) encode zstd,
    fragment_indicator     varchar(1) encode zstd,
    recordsequencenumber   varchar(21) encode zstd,
    content_source         varchar(30) encode zstd,
    rate_class             varchar(6) encode zstd,
    charge                 numeric(22, 6) encode zstd,
    end_user_charge        numeric(22, 6) encode az64,
    fct_free_text_1        varchar(50) encode zstd,
    fct_free_text_2        varchar(50) encode zstd,
    fct_free_text_3        varchar(50) encode zstd,
    fct_free_text_4        varchar(50) encode zstd,
    fct_free_text_5        varchar(50) encode zstd,
    fct_free_text_6        varchar(50) encode zstd,
    fct_free_text_7        varchar(50) encode zstd,
    fct_free_text_8        varchar(50) encode zstd,
    fct_free_text_9        varchar(50) encode zstd,
    fct_free_text_10       varchar(50) encode zstd,
    fct_free_text_11       varchar(50) encode zstd,
    fct_free_text_12       varchar(50) encode zstd,
    fct_free_text_13       varchar(50) encode zstd,
    fct_free_text_14       varchar(50) encode zstd,
    fct_free_text_15       varchar(50) encode zstd,
    fct_free_text_16       varchar(50) encode zstd,
    fct_free_text_17       varchar(50) encode zstd,
    fct_free_text_18       varchar(50) encode zstd,
    fct_free_text_19       varchar(50) encode zstd,
    fct_free_text_20       varchar(50) encode zstd,
    data_usage             numeric(22, 6) encode az64,
    charging_dt            date encode zstd,
    charging_month         integer encode az64,
    charging_dt_num        integer encode az64,
    charging_dt_hour       integer encode az64,
    charging_timestamp_gmt timestamp encode az64,
    charging_month_gmt     integer encode az64,
    charging_dt_num_gmt    integer encode az64,
    charging_dt_hour_gmt   integer encode az64,
    duration_min           integer encode az64,
    filename               varchar(50) encode zstd,
    batch_id               integer encode az64,
    created_date           timestamp encode az64,
    rec_checksum           varchar(32) encode zstd
)
    diststyle key
    sortkey (charging_month, charging_dt_num);
