create table log_batch_files_mno
(
    batch_id                integer GENERATED BY DEFAULT AS identity(1,1) encode raw distkey, --default default_identity(662527, 0, ('1,1'::character varying)::text) encode raw distkey,
    file_source             varchar(50) encode zstd,
    target_system           varchar(100) encode zstd,
    file_id                 integer encode az64,
    file_name               varchar(50) encode raw,
    batch_from              timestamp encode az64,
    batch_to                timestamp encode az64,
    record_count            integer encode az64,
    dm_normal_count         integer encode az64,
    dm_latecdr_count        integer encode az64,
    ldm_latecdr_count       integer encode az64,
    dm_normal_dbdupl_count  integer encode az64,
    dm_latecdr_dbdupl_count integer encode az64,
    is_valid                varchar(20),
    batch_createtime        timestamp encode az64
)
    diststyle key
    sortkey (batch_id, file_name);