create table temp_fact_mno_o2_data_duplcdr
(
    cdr_type               varchar(100),
    cdr_id                 varchar(100),
    imsi                   bigint encode az64,
    msisdn                 varchar(100),
    imei                   varchar(100),
    location               varchar(100),
    apn_ni                 varchar(100),
    apn_oi                 varchar(100),
    charging_timestamp     timestamp encode az64,
    duration               integer encode az64,
    data_volume_download   integer encode az64,
    data_volume_upload     integer encode az64,
    data_volume_total      integer encode az64,
    username               varchar(100),
    network_element_id     varchar(100),
    ggsn_address           varchar(100),
    charging_id            varchar(100),
    fragment_number        varchar(100),
    fragment_indicator     varchar(100),
    recordsequencenumber   varchar(100),
    content_source         varchar(100),
    rate_class             varchar(100),
    charge                 numeric(22, 6) encode az64,
    end_user_charge        numeric(22, 6) encode az64,
    fct_free_text_1        varchar(50) encode zstd,
    fct_free_text_2        varchar(50) encode zstd,
    fct_free_text_3        varchar(50) encode zstd,
    fct_free_text_4        varchar(50) encode zstd,
    fct_free_text_5        varchar(50) encode zstd,
    fct_free_text_6        varchar(50) encode zstd,
    fct_free_text_7        varchar(50) encode zstd,
    fct_free_text_8        varchar(50) encode zstd,
    fct_free_text_9        varchar(50) encode zstd,
    fct_free_text_10       varchar(50) encode zstd,
    fct_free_text_11       varchar(50) encode zstd,
    fct_free_text_12       varchar(50) encode zstd,
    fct_free_text_13       varchar(50) encode zstd,
    fct_free_text_14       varchar(50) encode zstd,
    fct_free_text_15       varchar(50) encode zstd,
    fct_free_text_16       varchar(50) encode zstd,
    fct_free_text_17       varchar(50) encode zstd,
    fct_free_text_18       varchar(50) encode zstd,
    fct_free_text_19       varchar(50) encode zstd,
    fct_free_text_20       varchar(50) encode zstd,
    data_usage             numeric(22, 6) encode az64,
    charging_dt            date encode az64,
    charging_month         integer encode az64,
    charging_dt_num        integer encode az64,
    charging_dt_hour       integer encode az64,
    charging_timestamp_gmt timestamp encode az64,
    charging_month_gmt     integer encode az64,
    charging_dt_num_gmt    integer encode az64,
    charging_dt_hour_gmt   integer encode az64,
    duration_min           numeric(21, 6) encode az64,
    filename               varchar(100) not null,
    batch_id               integer encode az64,
    created_date           timestamp      not null encode az64,
    rec_checksum           varchar(100) not null
);

