create table fact_mno_o2
(
    sk_mno_o2                 bigint default default_identity(158614, 0, ('1,1'::character varying)::text) encode zstd,
    cdr_type                  smallint encode az64,
    cdr_id                    varchar(12) encode zstd,
    network_call_reference    varchar(10),
    subscriber_imsi           bigint encode az64 distkey,
    a_number                  varchar(21) encode zstd,
    b_number                  varchar(21) encode zstd,
    dialled_digits            varchar(21) encode zstd,
    location                  varchar(5) encode zstd,
    call_forwarding_flag      varchar(1),
    smsc_address              varchar(21) encode zstd,
    charging_timestamp        timestamp encode az64,
    duration                  integer encode az64,
    rate_class                varchar(6) encode zstd,
    charge                    numeric(22, 6) encode az64,
    fragment_number           varchar(3),
    last_fragment_indicator   varchar(1),
    record_sequence_number    varchar(21) encode zstd,
    provider_id               varchar(5) encode zstd,
    service_type              varchar(10) encode zstd,
    imei                      varchar(21) encode zstd,
    message_type              varchar(11) encode zstd,
    end_user_charge           numeric(22, 6) encode az64,
    premium_sms_delivery_flag smallint encode az64,
    lyca_number               varchar(21),
    fct_free_text_1                  varchar(50) encode zstd,
    fct_free_text_2                  varchar(50) encode zstd,
    fct_free_text_3                  varchar(50) encode zstd,
    fct_free_text_4                  varchar(50) encode zstd,
    fct_free_text_5                  varchar(50) encode zstd,
    fct_free_text_6                  varchar(50) encode zstd,
    fct_free_text_7                  varchar(50) encode zstd,
    fct_free_text_8                  varchar(50) encode zstd,
    fct_free_text_9                  varchar(50) encode zstd,
    fct_free_text_10                 varchar(50) encode zstd,
    fct_free_text_11                 varchar(50) encode zstd,
    fct_free_text_12                 varchar(50) encode zstd,
    fct_free_text_13                 varchar(50) encode zstd,
    fct_free_text_14                 varchar(50) encode zstd,
    fct_free_text_15                 varchar(50) encode zstd,
    fct_free_text_16                 varchar(50) encode zstd,
    fct_free_text_17                 varchar(50) encode zstd,
    fct_free_text_18                 varchar(50) encode zstd,
    fct_free_text_19                 varchar(50) encode zstd,
    fct_free_text_20                 varchar(50) encode zstd,
    charging_dt               date encode az64,
    charging_month            integer,
    charging_dt_num           integer,
    charging_dt_hour          integer encode az64,
    charging_timestamp_gmt    timestamp encode az64,
    charging_month_gmt        integer encode az64,
    charging_dt_num_gmt       integer encode az64,
    charging_dt_hour_gmt      integer encode az64,
    duration_min              integer encode az64,
    filename                  varchar(50) encode zstd,
    batch_id                  integer encode az64,
    created_date              timestamp encode az64,
    rec_checksum              varchar(32) encode zstd
)
    diststyle key
    sortkey (charging_month, charging_dt_num);
