--1

Create table uk_rrbs_dm.dim_rrbs_data_cdrType
(
sk_cdr_type int generated by default as identity (1,1),
cdrtype_id smallint,
cdrtype_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	cdrtype_id
	)
;

--2

Create table uk_rrbs_dm.dim_rrbs_data_serviceid
(
sk_serviceid int generated by default as identity (1,1),
service_id smallint,
serviceid_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	service_id
	)
;

--3

Create table uk_rrbs_dm.dim_rrbs_data_roamflag
(
sk_roamflag_id int generated by default as identity (1,1),
roamflag_id smallint,
roamflag_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	roamflag_id
	)
;

--4

Create table uk_rrbs_dm.dim_rrbs_data_subscriberType
(
sk_subscriberType int generated by default as identity (1,1),
subscriberType_id smallint,
subscriberType_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	subscriberType_id
	)
;


---------------------------------------------------------------------------

create table uk_rrbs_dm.codeText_rrbs_data
(
sk_codeText int generated by default as identity (1,1),
code_param varchar(20), -- Conversion Unit / Call Forwarding Indicator
code_param_id smallint, --0/1/2
code_param_val varchar(50),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
Diststyle all
SORTKEY (
	code_param
	)
;
---------------------------------------------------------------------------
