--1

Create table uk_rrbs_dm.dim_rrbs_topup_operationcode
(
sk_operationcode int generated by default as identity (1,1),
operationcode_id smallint,
operationcode_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	operationcode_id
	)
;


Create table uk_rrbs_dm.dim_rrbs_topup_serviceid
(
sk_serviceid int generated by default as identity (1,1),
service_id smallint,
serviceid_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	service_id
	)
;


Create table uk_rrbs_dm.dim_rrbs_topup_bundleCategory
(
sk_bundleCategory int generated by default as identity (1,1),
bundleCategory_id smallint,
bundleCategory_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	bundleCategory_id
	)
;

---------------------------------------------------------------------------

create table uk_rrbs_dm.codeText_rrbs_topup
(
sk_codeText int generated by default as identity (1,1),
code_param varchar(20), -- Conversion Unit / Call Forwarding Indicator
code_param_id smallint, --0/1/2
code_param_val varchar(50),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	code_param
	)
;
---------------------------------------------------------------------------