
--1.

create table uk_rrbs_dm.dim_rrbs_voice_callType
(
sk_calltype int generated by default as identity (1,1),
calltype_id smallint,
cdrtype_id smallint,
calltype_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	calltype_id
	)
;


--2.

Create table uk_rrbs_dm.dim_rrbs_voice_cdrType
(
sk_cdrtype int generated by default as identity (1,1),
cdrtype_id smallint,
cdrtype_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	cdrtype_id
	)
;


--3.

Create table uk_rrbs_dm.dim_rrbs_voice_callfeature
(
sk_callfeature int generated by default as identity (1,1),
callfeature_id smallint,
callfeature_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	callfeature_id
	)
;


--4.

Create table uk_rrbs_dm.dim_rrbs_voice_serviceid
(
sk_serviceid int generated by default as identity (1,1),
service_id smallint,
serviceid_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	service_id
	)
;


--5. Roam Flag is commeented out as it is to be included in CodeText table

--Create table uk_rrbs_dm.dim_rrbs_voice_roamflag
--(
--sk_roamflag int generated by default as identity (1,1),
--roamflag_id smallint,
--roamflag_val varchar(100),
--param_desc varchar(250),
--valid_from timestamp default sysdate not null,
--valid_to timestamp DEFAULT '9999-12-31',
--is_recent smallint,
--batch_id smallint
--)
--diststyle all
--SORTKEY (
--	roamflag_id
--	)
--;


--6.

Create table uk_rrbs_dm.dim_rrbs_voice_bucketType
(
sk_bucketType int generated by default as identity (1,1),
bucketType_id smallint,
bucketType_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	bucketType_id
	)
;


--7.

Create table uk_rrbs_dm.dim_rrbs_voice_subscriberType
(
sk_subscriberType int generated by default as identity (1,1),
subscriberType_id smallint,
subscriberType_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	subscriberType_id
	)
;


--8.

Create table uk_rrbs_dm.dim_rrbs_voice_failcause
(
sk_failcause int generated by default as identity (1,1),
failcause_id smallint,
failcause_val varchar(100),
param_desc varchar(250),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	failcause_id
	)
;

-----------------------------------------------------------------------------

create table uk_rrbs_dm.codeText_rrbs_Voice
(
sk_codeText int generated by default as identity (1,1),
code_param varchar(20), -- Conversion Unit / Call Forwarding Indicator
code_param_id smallint, --0/1/2
code_param_val varchar(50),
valid_from timestamp default sysdate not null,
valid_to timestamp DEFAULT '9999-12-31',
is_recent smallint,
batch_id smallint
)
diststyle all
SORTKEY (
	code_param
	)
;
----------------------------------------------------------------------------



