CREATE TABLE
if NOT EXISTS
uk_rrbs_dm.fact_rrbs_topup
(
sk_rrbs_topup BIGINT  GENERATED BY DEFAULT AS identity(1,1) encode zstd
,	operation_code	smallint encode raw
,	network_id	smallint encode raw
,	recharge_type	smallint encode zstd
,	msisdn	bigint encode zstd
,	imsi	bigint encode zstd
,	account_pin_number	bigint encode zstd
,	voucher_card_id	int encode zstd
,	special_topup_amount	decimal(10,4) encode zstd
,	transaction_id	character varying(50) encode zstd
,	new_balance	numeric(10,4) encode zstd
,	face_value	numeric(10,4) encode zstd
,	recharge_amount	numeric(10,4) encode zstd
,	promo_validity_date	Date encode zstd
,	free_minutes	int encode zstd
,	free_voucher_onnet_minutes	int encode zstd
,	free_minutes_expiry_date	date encode zstd
,	free_sms	int encode zstd
,	free_voucher_onnet_sms	int encode zstd
,	free_sms_expiry_date	date encode zstd
,	free_offnet_minutes	int encode zstd
,	free_voucher_offnet_minutes	int encode zstd
,	free_offnet_minutes_expiry_date	date encode zstd
,	free_offnet_sms	int encode zstd
,	free_voucher_offnet_sms	int encode zstd
,	free_offnet_sms_expiry_date	date encode zstd
,	free_offnet2_minutes	int encode zstd
,	free_vouchercard_offnet2_minutes	int encode zstd
,	free_offnet2_minutes_expiry_date	date encode zstd
,	free_offnet2_sms	int encode zstd
,	free_vouchercard_offnet2_sms	int encode zstd
,	free_offnet2_sms_expiry_date	date encode zstd
,	free_offnet3_minutes	int encode zstd
,	free_vouchercard_offnet3_minutes	int encode zstd
,	free_offnet3_minutes_expiry_date	date encode zstd
,	free_offnet3_sms	int encode zstd
,	free_vouchercard_offnet3_sms	int encode zstd
,	free_offnet3_sms_expiry_date	date encode lzo
,	free_data	bigint encode zstd
,	free_voucher_data	bigint encode zstd
,	free_data_expirydate	date encode zstd
,	account_validity_date	date encode zstd
,	lyca_voucher_card_id	character varying(50) encode zstd
,	planid	smallint encode zstd
,	topup_counter	smallint encode zstd
,	bundle_code	int encode zstd
,	imei	character varying(25) encode zstd
,	voucher_onnet_mins_expdt	date encode zstd
,	voucher_onnet_sms_expdt	date encode zstd
,	voucher_offnet_mins_expdt1	date encode zstd
,	voucher_offnet_sms_expdt1	date encode zstd
,	voucher_offnet_mins_expdt2	date encode zstd
,	voucher_offnet_sms_expdt2	date encode zstd
,	voucher_offnet_mins_expdt3	date encode zstd
,	voucher_offnet_sms_expdt3	date encode lzo
,	voucher_free_dataexp	date encode zstd
,	retailer_msisdn	character varying(21) encode zstd
,	staff_msisdn	character varying(21) encode zstd
,	wlm_topupmode	character varying(50) encode zstd
,	face_value_1	decimal(10,4) encode zstd
,	promo_validity_days	int encode zstd
,	oldplanid	int encode zstd
,	onnet_mt_mins	int encode zstd
,	voucher_onnet_mt_mins	int encode zstd
,	onnet_mt_sms	int encode zstd
,	voucher_onnet_mt_sms	int encode zstd
,	onnet_mt_exp_dt	date encode lzo
,	voucher_onnet_mt_expiry_date	date encode lzo
,	offnet_mt_mins	int encode zstd
,	voucher_offnet_mt_mins	int encode zstd
,	offnet_mt_sms	int encode zstd
,	voucher_offnet_mt_sms	int encode zstd
,	offnet_mt_exp_dt	date encode lzo
,	voucher_offnet_mt_expiry_date	date encode lzo
,	bundle_name	character varying(100) encode zstd
,	old_account_balance	decimal(10,4) encode zstd
,	parent_msisdn	character varying(25) encode zstd
,	rrbs_transaction_id	character varying(50) encode zstd
,	override_bundle	int encode zstd
,	vouchernetworkid	smallint encode zstd
,	accid	character varying(10) encode zstd
,	deptid	character varying(10) encode zstd
,	bundle_catery	smallint encode zstd
,	plan_validity_days	smallint encode zstd
,	account_id	int encode zstd
,	sim_number	bigint encode zstd
,	cdr_time_stamp	timestamp encode zstd
,	reservation	smallint encode zstd
,	discount_promo_code	character varying(50) encode zstd
,	discount_promo_amount	decimal(10,4) encode zstd
,	primary_bundle_code	int encode zstd
,	family_account_id	character varying(50) encode zstd
,	tax	decimal(10,4) encode zstd
,	number_of_installments	int encode zstd
,	oba_bundle_flag	smallint encode zstd
,	oba_due_amount	decimal(10,4) encode zstd
,	parent_bundle_code	int encode zstd
,	bundle_unit_type	smallint encode zstd
,	contract_start_date	date encode zstd
,	contract_end_date	date encode zstd
,	flh_flag	smallint encode zstd
,	exibs_retailer_transaction_id	character varying(50) encode zstd
,	operation_flag	smallint encode zstd
,	vat_amount	decimal(10,4) encode zstd
,	special_discount_code	character varying(50) encode zstd
,	special_discount_amount	decimal(10,4) encode lzo
,	number_of_installments_discounts_applied	character varying(50) encode zstd
,	actual_bundle_cost	decimal(10,4) encode zstd
,	reservation_reference_transaction_id	character varying(50) encode zstd
,	bundle_expiry_type	smallint encode zstd
,	bundle_balance	decimal(10,4) encode zstd
,	muv_indicator	smallint encode zstd
,	bundle_group_type	smallint encode zstd
,	sequence_number	smallint encode zstd
,	amount_refunded	decimal(10,4) encode zstd
,	forcible_cancellation	character varying(50) encode zstd
,	payment_mode_indicator	character varying(50) encode zstd
,	amount	decimal(20,4) encode zstd
,	version_id	smallint encode zstd
,	refund_entity_type	smallint encode zstd
,	refund_provided_to	character varying(50) encode zstd
,	topup_validity_days	int encode zstd
,	reserve_amount	decimal(10,4) encode zstd
,	preloaded_bundle_flag	smallint encode zstd
,	staff_indicator	smallint encode zstd
,	child_addition_discount	decimal(10,4) encode zstd
,	payg_family_indicator	smallint encode zstd
,	payg_prorate_flag	smallint encode zstd
,	payg_child_index	smallint encode zstd
,	parent_msisdn1	character varying(50) encode zstd
,	payg_member_count	int encode zstd
,	direct_addon_flag	smallint encode zstd
,	action_flag	smallint encode zstd
,	"timestamp"	character varying(50) encode zstd
,	sim_with_bundle_code	int encode zstd
,	taxation_details	character varying(50) encode zstd
,	reserved	character varying(50) encode zstd
,	bundle_purchase_date	timestamp encode zstd
,	bundle_start_date	timestamp encode zstd
,	renewal_payment_mode	smallint encode zstd
,	iot_bundle_flag	smallint encode zstd
,	veekbundleflag	smallint encode zstd
,	validity_overridden	smallint encode zstd
,	link_type	smallint encode zstd
,	overwrite_bundle_cost_flag	smallint encode zstd
,	order_id	character varying(50) encode zstd
,	pocket_id	character varying(50) encode zstd
,	da_track	decimal(10,4) encode zstd
,	da_principal_amount	decimal(10,4) encode zstd
,	is_loan_request	smallint encode zstd
,	migrated_ortel_subscriber_flag	smallint encode zstd
,	reward_purchased	smallint encode zstd
,	feebuffer	character varying(50) encode zstd
,	tax_buffer	character varying(50) encode zstd
,	paymentgateway	character varying(50) encode zstd
,	zipcode	character varying(50) encode zstd
,	professional_channel_name	character varying(50) encode zstd
,	topupcriteriaflag	smallint encode zstd
,	nus_id	character varying(50) encode zstd
,	nus_applied	smallint encode zstd
,	slotid	character varying(50) encode zstd
,	reserved_bundle_cost	character varying(50) encode zstd
,	filename	character varying(50) not null encode zstd
,	batch_id int4 not null encode zstd
,	created_date	timestamp without time zone not null encode zstd
)
DISTSTYLE KEY
 DISTKEY (imsi)
 sortkey
 (
--recharge_date, this attribute is missing from raw file, but required in Daily Dash Board query
network_id,
operation_code

 )