CREATE TABLE factagg_user_rrbs_topup_monthly (
      sk_id                     bigint generated by default as identity (1,1) encode az64
    , msisdn                    bigint encode az64
    , user_type                 varchar(30) encode zstd
    , bundle_code               varchar(20) encode zstd
    , imsi                      bigint encode az64
    , bundle_name               varchar(100) encode zstd
    , network_id                smallint
    , cdr_dt_month              integer encode az64
    , cdr_dt_year               integer encode az64
    , created_date_time         timestamp  default sysdate encode
    , created_date              date default sysdate
)
diststyle even
sortkey
(cdr_dt_year, cdr_dt_month)
;